// Definisi gambar panduan: layar mana yang dipotret, akun contoh mana, langkah menuju layar itu, dan penunjuk bernomor (teks keterangan + cara menemukan elemennya).
// Sumber kebenaran teks gambar (judul, alt, keterangan). Ubah teks di sini lalu jalankan `node scripts/panduan/ambil.mjs --teks`; ubah tata letak/elemen lalu ambil ulang gambarnya.
// Cara membaca cara menemukan elemen (`cari`, `layar`, `ponsel`, `klik`, `gulir`): lihat pembantu di ambil.mjs (selector, label, teks, tag, mengandung, dalam, nth, naik, pad).
// Akun contoh mode lokal: 10231 (Penegak Ahmad Fauzi), 10008 (Penegak berjabatan Dewan), pembina, admin. Semua data adalah data contoh.
// Awalan id = peran panduan: umum, penegak, dewan, pembina, admin. Setiap gambar dipotret dua kali: layar (laptop/PC/tablet) dan ponsel.
// Opsi `data: 'panduan'` = memakai basis data lokal tambahan ?data=panduan (src/lokal/dataPanduan.js: agenda, materi, TKK, pelantikan, Saka, sesi ujian, Bina Damping,
// Pinsa tertugas, pra-uji hidup dengan satu pengajuan). Tanpa opsi itu gambar memakai data contoh bawaan, di mana halaman-halaman tersebut masih kosong.
// Opsi `tinggi: { ponsel: N }` = tinggi gambar ponsel (piksel) untuk halaman panjang; `dialog: true` = memotret jendela ajakan data diri (bukan menutupnya).

const MENU = 'nav[aria-label="Menu utama"]'; // di laptop = bilah samping, di ponsel = menu bawah (hanya yang terlihat yang dipakai)

export const DEFINISI = [
  // ---------- Umum ----------
  {
    id: 'umum-menu',
    akun: '10231',
    judul: 'Mengenal tampilan SIGARDA',
    alt: 'Halaman Beranda dengan menu, tombol Notifikasi, tombol Bantuan, dan nama akun diberi nomor.',
    penanda: [
      { teks: 'Menu utama. Di laptop, PC, dan tablet menu ada di bilah kiri; di ponsel ada di baris paling bawah dan dapat digeser ke kiri atau kanan bila menunya banyak.', layar: { selector: 'aside[aria-label="Menu samping"]', pad: 0 }, ponsel: { selector: MENU, pad: 0 } },
      { teks: 'Notifikasi (ikon lonceng): kabar dari aplikasi, misalnya pengajuan uji, jadwal ujian, dan pengingat.', cari: { teks: 'Notifikasi', dalam: MENU, naik: 1 } },
      { teks: 'Bantuan (tanda tanya): panduan ini. Tersedia untuk semua peran.', cari: { teks: 'Bantuan', dalam: MENU, naik: 1 } },
      { teks: 'Akun Anda. Sentuh nama untuk mengganti PIN atau keluar dari akun.', cari: { label: 'Akun Ahmad Fauzi' } },
    ],
  },
  {
    id: 'umum-akun',
    akun: '10231',
    judul: 'Menu akun: ganti PIN dan keluar',
    alt: 'Menu akun terbuka menampilkan Pengaturan akun (ganti PIN) dan Keluar.',
    langkah: [{ klik: { label: 'Akun Ahmad Fauzi' } }],
    penanda: [
      { teks: 'Pengaturan akun: ganti PIN dan isi nomor WhatsApp.', cari: { teks: 'Pengaturan akun', mengandung: true, tag: 'button' } },
      { teks: 'Keluar: akhiri sesi di perangkat ini. Selalu tekan Keluar bila memakai HP atau komputer bersama.', cari: { teks: 'Keluar', tag: 'button' } },
    ],
  },
  {
    id: 'umum-notifikasi',
    akun: '10231',
    data: 'panduan',
    judul: 'Notifikasi',
    alt: 'Halaman Notifikasi dengan tombol Tandai semua dibaca, pengaturan notifikasi di perangkat, dan daftar kabar terbaru.',
    langkah: [{ klik: { teks: 'Notifikasi', mengandung: true, tag: 'button', dalam: MENU } }, { tunggu: 2500 }],
    penanda: [
      { teks: 'Tandai semua dibaca: membersihkan lencana angka di menu Notifikasi.', cari: { teks: 'Tandai semua dibaca', tag: 'button' } },
      { teks: 'Aktifkan notifikasi supaya kabar sampai ke perangkat ini walau aplikasi tertutup. Keluar dari akun menghentikannya di perangkat ini saja.', cari: { teks: 'Aktifkan notifikasi', tag: 'button' } },
      { teks: 'Kapan notifikasi muncul: daftar kejadian yang memicu kabar.', cari: { teks: 'Kapan notifikasi muncul?', tag: 'summary' } },
      { teks: 'Satu kabar. Titik di kiri menandakan belum dibaca; sentuh untuk membuka halaman yang bersangkutan.', cari: { selector: 'ul[aria-label="Daftar notifikasi"] li', nth: 0 } },
    ],
  },
  {
    id: 'umum-bantuan',
    akun: '10231',
    data: 'panduan',
    tinggi: { ponsel: 1000 },
    judul: 'Menu Bantuan',
    alt: 'Halaman Bantuan dengan tombol cetak, pilihan peran, pilihan gambar contoh, dan daftar isi panduan.',
    langkah: [{ klikMenu: 'Bantuan' }, { tutupDialog: true }],
    penanda: [
      { teks: 'Cetak atau simpan PDF: menghasilkan salinan panduan yang dapat dibagikan.', cari: { teks: 'Cetak atau simpan PDF', tag: 'button' } },
      { teks: 'Pilih peran: panduan Penegak, Dewan Ambalan, Pembina, atau Admin. Semua peran boleh membaca panduan peran lain.', cari: { selector: '[role=tablist][aria-label="Pilih peran"]' } },
      { teks: 'Gambar contoh: Ikuti layar (otomatis), Ponsel, atau Laptop. Hanya satu tampilan yang diunduh.', cari: { selector: '[role=group][aria-labelledby="label-mode-gambar"]', naik: 1 } },
      { teks: 'Daftar isi: sentuh judul bagian untuk melompat ke bagian itu.', layar: { selector: 'nav[aria-label="Daftar isi panduan"]' }, ponsel: { teks: 'Daftar isi', mengandung: true, tag: 'button', dalam: 'main' } },
    ],
  },
  // ---------- Penegak ----------
  {
    id: 'penegak-beranda',
    akun: '10231',
    tinggi: { ponsel: 1100 },
    judul: 'Beranda Penegak',
    alt: 'Beranda Penegak menampilkan lingkaran progres, kartu SKU Bantara, kehadiran latihan Jumat, dan iuran.',
    penanda: [
      { teks: 'Ringkasan Anda: nama, kelas, sangga, tingkat, dan lingkaran persen progres SKU.', cari: { teks: 'Selamat datang,', induk: 'section' } },
      { teks: 'Kartu SKU Bantara dan Laksana: jumlah butir lulus dan yang sedang diproses. Tombol "Lihat butir" membuka daftar lengkapnya.', cari: { teks: 'SKU Penegak Bantara', induk: '.panel' } },
      { teks: 'Kehadiran latihan Jumat pada semester ini. Batas minimal 75% dipakai sebagai dasar penilaian SKU tentang kehadiran.', cari: { teks: 'Kehadiran latihan Jumat', induk: '.panel' } },
      { teks: 'Iuran bumbung kepramukaan: total gudep dan iuran Anda sendiri.', cari: { teks: 'Iuran bumbung kepramukaan', induk: '.panel' } },
    ],
  },
  {
    id: 'penegak-sku',
    akun: '10231',
    tinggi: { ponsel: 1000 },
    judul: 'Poin SKU',
    alt: 'Halaman Poin SKU dengan tab Bantara dan Laksana, progres, peta butir, penyaring status, dan daftar butir.',
    langkah: [{ klikMenu: 'Poin SKU' }],
    penanda: [
      { teks: 'Tab tingkat: Bantara dan Laksana. Laksana terkunci sampai seluruh butir Bantara lulus.', cari: { teks: 'Bantara', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Progres: jumlah butir lulus, dalam proses, dan belum.', cari: { teks: 'butir lulus', mengandung: true, dalam: 'main', induk: '.panel' } },
      { teks: 'Peta butir: kotak bernomor tiap butir. Hijau = lulus, kuning = dalam proses, krem = belum. Sentuh untuk melompat ke butirnya.', cari: { teks: 'Peta 23 butir SKU Bantara', mengandung: true, induk: '.panel' } },
      { teks: 'Penyaring: tampilkan semua butir, yang belum, yang sedang diproses, atau yang lulus.', cari: { teks: 'Semua', tag: 'button', dalam: 'main', naik: 1 } },
    ],
  },
  {
    id: 'penegak-absensi',
    akun: '10231',
    tinggi: { ponsel: 1100 },
    judul: 'Absensi latihan Jumat',
    alt: 'Halaman Absensi dengan pilihan tahun ajaran dan semester, ringkasan hadir, izin, sakit, alpa, dan riwayat pertemuan.',
    langkah: [{ klikMenu: 'Absensi' }],
    penanda: [
      { teks: 'Pilih tahun ajaran dan semester yang ingin dilihat.', cari: { selector: 'main select', naik: 1, nth: 0, pad: 4 } },
      { teks: 'Ringkasan: jumlah hadir, izin, sakit, alpa, dan persentase kehadiran.', cari: { teks: 'Kehadiran', dalam: 'main', nth: 0, induk: '.panel' } },
      { teks: 'Riwayat tiap pertemuan Jumat dan status kehadiran Anda.', cari: { selector: 'main ul.panel', nth: 0, pad: 2 } },
    ],
  },
  {
    id: 'penegak-iuran',
    akun: '10231',
    tinggi: { ponsel: 1100 },
    judul: 'Iuran bumbung kepramukaan',
    alt: 'Halaman Iuran dengan tombol Rekap, ringkasan gudep, dan iuran saya per pertemuan.',
    langkah: [{ klikMenu: 'Iuran' }],
    penanda: [
      { teks: 'Rekap: pilih tahun ajaran dan semester untuk melihat ringkasan iuran gudep.', cari: { teks: 'Rekap', tag: 'button', dalam: 'main' } },
      { teks: 'Ringkasan gudep: total iuran, jumlah pertemuan, dan rata-rata per pertemuan.', cari: { teks: 'Total gudep', mengandung: true, induk: '.panel' } },
      { teks: 'Iuran saya: riwayat beriuran tiap Jumat. Menyimpan iuran secara rutin dinilai pada butir SKU tentang iuran.', cari: { teks: 'Iuran saya', induk: '.panel' } },
    ],
  },
  {
    id: 'penegak-datadiri',
    akun: '10231',
    dialog: true,
    judul: 'Melengkapi data diri',
    alt: 'Jendela Lengkapi data dirimu dengan isian nomor WhatsApp, tanggal lahir, alamat, tombol Simpan data diri, dan Isi nanti.',
    penanda: [
      { teks: 'Yang masih perlu dilengkapi disebutkan di sini. Boleh dilewati; akan ditanyakan lagi lain kali sampai lengkap.', cari: { teks: 'Yang masih perlu dilengkapi', mengandung: true, dalam: '[role=dialog]' } },
      { teks: 'Nomor WhatsApp: dipakai Pembina atau Dewan Ambalan untuk menghubungi Anda bila diperlukan.', cari: { teks: 'Nomor WhatsApp', dalam: '[role=dialog]', naik: 1 } },
      { teks: 'Jenis kelamin dan agama yang sudah tercatat tidak dapat diubah sendiri; hubungi Pembina atau Admin bila keliru.', cari: { teks: 'Jenis kelamin', dalam: '[role=dialog]', naik: 1 } },
    ],
  },
  {
    id: 'penegak-agenda',
    akun: '10231',
    data: 'panduan',
    tinggi: { ponsel: 1000 },
    judul: 'Agenda kegiatan Ambalan',
    alt: 'Halaman Agenda berisi daftar kegiatan Ambalan dengan hitung mundur H-n di sisi kanan tiap kegiatan.',
    langkah: [{ klikMenu: 'Agenda' }],
    penanda: [
      { teks: 'Satu kegiatan: judul, jenis, tanggal, tahun ajaran, dan keterangan. Urutannya dari yang paling dekat.', cari: { selector: 'main li', nth: 0 } },
      { teks: 'Hitung mundur (H-7 = tujuh hari lagi). Pengingat H-30, H-7, dan H-1 dikirim lewat Notifikasi.', cari: { selector: 'main li span.rounded-full', nth: 0 } },
      { teks: 'Bila namamu disebut ("Penegak terkait"), kamu ikut diberi pengingat untuk kegiatan itu.', cari: { teks: '1 Penegak terkait', mengandung: true, induk: 'li' } },
    ],
  },
  {
    id: 'penegak-tkk',
    akun: '10007',
    data: 'panduan',
    tinggi: { layar: 900, ponsel: 1400 },
    judul: 'TKK (Tanda Kecakapan Khusus)',
    alt: 'Halaman TKK dengan kemajuan menuju syarat Garuda, tombol Ajukan TKK, TKK Krida, dan daftar TKK yang sudah lulus.',
    langkah: [{ klikMenu: 'TKK' }],
    penanda: [
      { teks: 'Kemajuan menuju syarat Garuda: total TKK, TKK Madya ke atas, dan TKK wajib bertingkat Utama.', cari: { teks: 'Kemajuan menuju syarat Garuda', induk: '.panel' } },
      { teks: 'Ajukan TKK: sudah lulus uji TKK? Ajukan agar Pembina mencatatnya resmi; kamu diberi tahu lewat Notifikasi saat ditinjau.', cari: { teks: 'Ajukan TKK', tag: 'button' } },
      { teks: 'TKK Krida: piagam Krida yang dibutuhkan portofolio Garuda (minimal 2).', cari: { teks: 'TKK Krida (0)', tag: 'h2' } },
      { teks: 'TKK yang sudah lulus, lengkap dengan tingkat, tanggal, penguji, dan bidangnya.', cari: { selector: 'main ul.panel > li', nth: 0 } },
    ],
  },
  {
    id: 'penegak-cetak',
    akun: '10231',
    tinggi: { ponsel: 1000 },
    judul: 'Cetak kartu SKU dan surat',
    alt: 'Halaman Cetak dokumen dengan pilihan tingkat Bantara atau Laksana, jenis dokumen, tombol cetak, dan pratinjau kartu SKU.',
    langkah: [{ klikMenu: 'Cetak' }],
    penanda: [
      { teks: 'Pilih tingkat: Bantara atau Laksana.', cari: { teks: 'Bantara', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Pilih dokumen: Kartu SKU, Surat Tanda Lulus (setelah seluruh butir satu tingkat lulus), atau Surat pengantar agama.', cari: { teks: 'Kartu SKU', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Cetak atau simpan PDF: pilih "Simpan sebagai PDF" pada kotak dialog cetak peramban.', cari: { teks: 'Cetak atau simpan PDF', tag: 'button' } },
      { teks: 'Pratinjau dokumen persis seperti hasil cetak, lengkap dengan kop gugus depan dan kode QR tiap butir lulus.', cari: { teks: 'KARTU KEMAJUAN SKU PENEGAK BANTARA', mengandung: true, naik: 3 } },
    ],
  },
  {
    id: 'penegak-materi',
    akun: '10231',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Materi belajar SKU',
    alt: 'Halaman Materi dengan pilihan tingkat, pilihan butir SKU, kolom cari materi, daftar isi, dan isi materi.',
    langkah: [{ klikMenu: 'Materi' }],
    penanda: [
      { teks: 'Tingkat: Semua, Bantara, atau Laksana.', cari: { teks: 'Bantara', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Butir SKU: tampilkan materi yang terkait satu butir saja.', cari: { teks: 'Butir SKU', dalam: 'main', naik: 1 } },
      { teks: 'Cari materi menurut judul atau bagian.', cari: { teks: 'Cari materi', dalam: 'main', naik: 1 } },
      { teks: 'Daftar isi: sentuh judul untuk berpindah antarmateri dan antarbagian.', layar: { teks: 'DAFTAR ISI', mengandung: true, dalam: 'main', induk: 'div' }, ponsel: { teks: 'Daftar isi', mengandung: true, tag: 'button', dalam: 'main' } },
    ],
  },
  {
    id: 'penegak-portofolio',
    akun: '10007',
    data: 'panduan',
    tinggi: { ponsel: 1300 },
    judul: 'Portofolio Calon Garuda',
    alt: 'Dashboard Calon Penegak Garuda dengan lencana kesiapan, ringkasan dokumen siap, peta 26 dokumen, dan jurnal terbaru.',
    langkah: [{ klikMenu: 'Garuda' }],
    penanda: [
      { teks: 'Kesiapan portofolio: jumlah dokumen yang sudah siap dari 26 dokumen.', cari: { teks: 'Dashboard Calon Penegak Garuda', induk: 'section' } },
      { teks: 'Ringkasan: dokumen Siap, Sedang disiapkan, dan Belum ada.', cari: { teks: 'dokumen siap', mengandung: true, dalam: 'main', nth: 1, induk: '.panel' } },
      { teks: 'Peta 26 dokumen: sentuh nomor untuk mengisi status, tautan Google Drive, dan catatan dokumen itu.', cari: { teks: 'Peta 26 dokumen', mengandung: true, dalam: 'main', naik: 1 } },
      { teks: 'Jurnal terbaru: setiap perubahan tercatat otomatis dan terlihat oleh Pembina.', cari: { teks: 'Jurnal terbaru', dalam: 'main', induk: '.panel' } },
    ],
  },
  {
    id: 'penegak-spg',
    akun: '10007',
    data: 'panduan',
    tinggi: { ponsel: 1300 },
    judul: 'SPG (Syarat Pramuka Garuda)',
    alt: 'Halaman SPG dengan jumlah butir terpenuhi, rincian Terpenuhi, Proses, Belum, peta 13 butir, dan daftar butir.',
    langkah: [{ klikMenu: 'SPG' }],
    penanda: [
      { teks: 'Kemajuan: berapa dari 13 butir syarat yang sudah terpenuhi.', cari: { teks: 'butir terpenuhi', mengandung: true, dalam: 'main', induk: '.panel' } },
      { teks: 'Terpenuhi (hijau), Proses (kuning, menunggu ditetapkan Pembina), dan Belum.', cari: { teks: 'Terpenuhi', dalam: 'main', nth: 0, naik: 2 } },
      { teks: 'Peta 13 butir: sentuh nomor untuk melompat ke butirnya.', cari: { teks: 'Peta 13 butir SPG', mengandung: true, naik: 1 } },
      { teks: 'Satu butir: status dan dasarnya, misalnya hitungan otomatis aplikasi atau kelengkapan dokumen portofolio.', cari: { teks: 'UUD 1945 dan UU Gerakan Pramuka', dalam: 'main', induk: 'li' } },
    ],
  },
  {
    id: 'penegak-pra-uji',
    akun: '10118',
    data: 'panduan',
    judul: 'Pra-uji: antrian penilai',
    alt: 'Halaman Pra-uji SKU dengan antrian satu Penegak yang menunggu dinilai dan tombol Nilai.',
    langkah: [{ klikMenu: 'Pra-uji' }],
    penanda: [
      { teks: 'Antrian pra-uji saya: pengajuan Penegak yang menunggu penilaianmu sebagai Pinsa atau Bina Damping.', cari: { teks: 'Antrian pra-uji saya', tag: 'h2' } },
      { teks: 'Butir yang diajukan, tahap pra-uji, dan jadwal uji resmi Pembina.', cari: { teks: 'Butir 6', mengandung: true, dalam: 'main', naik: 2 } },
      { teks: 'Nilai: pilih Lulus (diteruskan ke tahap berikutnya) atau Belum lulus (catatan perbaikan wajib). Pra-uji hanya rekomendasi; hasil resmi tetap dari Pembina.', cari: { teks: 'Nilai', tag: 'button' } },
    ],
  },
  {
    id: 'penegak-sangga',
    akun: '10008',
    data: 'panduan',
    tinggi: { ponsel: 1300 },
    judul: 'Sangga dan Bina Damping',
    alt: 'Halaman Sangga dan Bina Damping dengan pilihan rombel, daftar Bina Damping, peringatan, dan tabel pengaturan sangga dan Pinsa.',
    langkah: [{ klikMenu: 'Sangga' }],
    penanda: [
      { teks: 'Pilih rombel yang ingin dilihat atau diatur.', cari: { teks: 'Rombel', tag: 'label', dalam: 'main' } },
      { teks: 'Bina Damping rombel: dua Penegak berjabatan yang mendampingi rombel ini pada tahun ajaran berjalan.', cari: { teks: 'Bina Damping rombel X-01', mengandung: true, dalam: 'main', naik: 1 } },
      { teks: 'Perlu diperhatikan: peringatan jumlah Bina Damping dan sangga; tidak menghalangi penyimpanan.', cari: { teks: 'Perlu diperhatikan (tidak menghalangi penyimpanan):', dalam: 'main', naik: 1 } },
      { teks: 'Isi kolom Sangga dan centang Pinsa (Pimpinan Sangga) untuk satu Penegak per sangga.', cari: { selector: 'main table', nth: 0 } },
    ],
  },
  // ---------- Dewan Ambalan (Penegak berjabatan, akun 10008) ----------
  {
    id: 'dewan-tampilan',
    akun: '10008',
    judul: 'Berpindah antara tampilan Penegak dan Dewan',
    alt: 'Beranda dengan bilah pemilih tampilan Penegak dan Dewan di bagian atas.',
    penanda: [
      { teks: 'Bilah pilihan tampilan. Hanya muncul bagi Penegak yang diberi jabatan Dewan Ambalan oleh Pembina atau Admin.', cari: { label: 'Tampilan akun' } },
      { teks: 'Tampilan Penegak: menu Anda sebagai Penegak biasa (SKU sendiri, absensi, iuran).', cari: { teks: 'Penegak', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } },
      { teks: 'Tampilan Dewan: menu untuk mengurus ambalan (Dashboard, Absensi, Iuran, Tindak Lanjut, dan lainnya). Pilihan ini diingat per akun.', cari: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } },
    ],
  },
  {
    id: 'dewan-dashboard',
    akun: '10008',
    judul: 'Dashboard Dewan Ambalan',
    alt: 'Dashboard Dewan Ambalan dengan kartu antrian pengujian dan progres per rombel.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Dashboard' }],
    penanda: [
      { teks: 'Pilihan tampilan: pastikan di posisi Dewan.', cari: { label: 'Tampilan akun' } },
      { teks: 'Antrian pengujian SKU yang menunggu. Tombol "Buka antrian" membuka daftar pengajuan Penegak yang perlu dinilai.', cari: { teks: 'Antrian pengujian SKU', induk: 'div.rounded-lg, section' } },
      { teks: 'Progres tiap rombel: rata-rata SKU Bantara dan Laksana, serta jumlah Penegak yang menunggu uji.', cari: { teks: 'Progres per rombel', naik: 1 } },
    ],
  },
  {
    id: 'dewan-absensi',
    akun: '10008',
    tinggi: { ponsel: 1500 },
    judul: 'Rekap absensi latihan Jumat',
    alt: 'Halaman Absensi tampilan Dewan dengan tab Rekap dan Catat absensi, penyaring, ringkasan kehadiran, dan tabel per Penegak.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Absensi' }],
    penanda: [
      { teks: 'Tab Rekap (melihat hasil) dan Catat absensi (mengisi kehadiran tiap Jumat).', cari: { teks: 'Rekap', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Unduh Excel: rekap kehadiran untuk laporan atau arsip.', cari: { teks: 'Unduh Excel (.xlsx)', tag: 'button' } },
      { teks: 'Ringkasan: jumlah pertemuan, rata-rata kehadiran, dan berapa Penegak yang di atas atau di bawah batas 75%.', cari: { teks: 'Pertemuan terlaksana', mengandung: true, induk: '.panel' } },
      { teks: 'Kehadiran tiap Penegak (H = hadir, I = izin, S = sakit, A = alpa). Baris merah muda = kehadiran di bawah batas minimal.', cari: { selector: 'main table', nth: 0, pad: 2 } },
    ],
  },
  {
    id: 'dewan-tindaklanjut',
    akun: '10008',
    judul: 'Tindak Lanjut: Penegak yang lama tidak bergerak',
    alt: 'Halaman Tindak Lanjut dengan daftar Penegak dan tombol Buka WhatsApp di tiap baris.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Tindak Lanjut' }],
    penanda: [
      { teks: 'Penjelasan: daftar Penegak yang sudah lebih dari 8 hari tidak ada pergerakan (SKU, absensi, atau iuran).', cari: { teks: 'hal perlu tindak lanjut', mengandung: true } },
      { teks: 'Satu baris = satu Penegak, lengkap dengan kelas, sangga, dan alasan (mis. iuran, sudah berapa hari).', cari: { selector: 'main li', nth: 0 } },
      { teks: 'Buka WhatsApp: mengingatkan Penegak lewat pesan siap kirim. Anda memilih sendiri kontaknya dan menekan kirim.', cari: { teks: 'Buka WhatsApp', nth: 0 } },
    ],
  },
  // ---------- Pembina ----------
  {
    id: 'pembina-dashboard',
    akun: 'pembina',
    judul: 'Dashboard Pembina',
    alt: 'Dashboard Pembina dengan kartu antrian pengujian, pilihan tampilkan semua rombel, dan kartu progres tiap rombel.',
    tinggi: { ponsel: 1100 },
    langkah: [{ klikMenu: 'Dashboard' }],
    penanda: [
      { teks: 'Antrian pengujian: jumlah pengajuan yang menunggu Anda. Tombol "Buka antrian" membuka daftarnya.', cari: { teks: 'Antrian pengujian SKU', induk: 'div.rounded-lg, section' } },
      { teks: 'Bawaannya hanya rombel yang Anda tangani tahun ajaran ini. Centang untuk menampilkan semua rombel.', cari: { teks: 'Tampilkan semua rombel', naik: 0 } },
      { teks: 'Kartu tiap rombel: siapa pengujinya, rata-rata progres SKU, dan berapa yang menunggu atau sedang diuji.', cari: { teks: 'X-01', induk: 'li' } },
    ],
  },
  {
    id: 'pembina-antrian',
    akun: 'pembina',
    judul: 'Antrian pengujian SKU',
    alt: 'Halaman Antrian pengujian dengan daftar pengajuan Penegak, butir SKU, tanggal, dan tombol Nilai, Alihkan, Lihat peserta.',
    langkah: [{ klikMenu: 'Antrian' }],
    penanda: [
      { teks: 'Bawaannya hanya pengajuan yang ditujukan kepada Anda atau antrian rombel Anda. Centang untuk melihat semua penguji.', cari: { teks: 'Tampilkan semua penguji', naik: 1 } },
      { teks: 'Satu pengajuan: nama Penegak, butir SKU yang diuji, status "Menunggu uji", dan tanggal pengujian.', cari: { selector: 'main li', nth: 0 } },
      { teks: 'Nilai: membuka lembar penilaian butir itu. Hasil resmi dicatat dengan PIN Anda.', cari: { teks: 'Nilai', tag: 'button', nth: 0 } },
      { teks: 'Alihkan: memindahkan pengajuan ke penguji lain yang berhak. Lihat peserta: membuka halaman SKU Penegak itu.', cari: { teks: 'Alihkan', tag: 'button', nth: 0 } },
    ],
  },
  {
    id: 'pembina-peserta',
    akun: 'pembina',
    judul: 'Peserta: mencari dan melihat Penegak',
    alt: 'Halaman Peserta dengan kotak cari, penyaring rombel dan status, serta daftar Penegak beserta progres SKU-nya.',
    penanda: [
      { teks: 'Cari nama atau NIS.', cari: { selector: 'main input', nth: 0, pad: 3 } },
      { teks: 'Penyaring: rombel saya, status (aktif, nonaktif, alumni), sangga, kelas, peran, jenis kelamin, dan agama.', cari: { teks: 'Hanya rombel saya', mengandung: true, naik: 1 } },
      { teks: 'Satu Penegak: kelas, sangga, agama, tingkat, dan dua batang progres (Bantara dan Laksana). Ketuk untuk membuka detail SKU-nya.', cari: { teks: 'Ahmad Fauzi', dalam: 'main', induk: 'li, a, button' } },
    ],
    langkah: [{ klikMenu: 'Peserta' }],
  },
  {
    id: 'pembina-penugasan',
    akun: 'pembina',
    tinggi: { ponsel: 1150 },
    judul: 'Penugasan penguji per rombel',
    alt: 'Halaman Penugasan penguji dengan pilihan tahun ajaran, tab kelas, dan tabel penguji per rombel yang dicentang.',
    langkah: [{ klikMenu: 'Penugasan' }],
    penanda: [
      { teks: 'Pilih tahun ajaran. Tombol "Salin dari ..." di sebelahnya menyalin penugasan tahun sebelumnya.', cari: { teks: 'Tahun ajaran', induk: 'div', naik: 0, pad: 4, nth: 0 } },
      { teks: 'Peringatan: rombel berisi Penegak tetapi belum punya penguji. Rombel itu memakai aturan bawaan sampai ditugaskan.', cari: { teks: 'belum punya penguji', mengandung: true, naik: 1 } },
      { teks: 'Tab kelas X, XI, dan XII.', cari: { teks: 'Kelas X', tag: 'button', naik: 1 } },
      { teks: 'Tabel penugasan: ketuk sel untuk menugaskan atau mencabut penguji pada rombel itu. Baris bawah menunjukkan jumlah Penegak dan penguji per rombel.', cari: { selector: 'main table', nth: 0, pad: 2 } },
    ],
  },
  {
    id: 'pembina-pengurus',
    akun: 'pembina',
    judul: 'Kepengurusan Dewan Ambalan',
    alt: 'Halaman Kepengurusan dengan daftar pengurus saat ini, tombol Tambah pengurus, dan ganti kepengurusan lewat berkas Excel.',
    tinggi: { ponsel: 1250 },
    langkah: [{ klikMenu: 'Pengurus' }],
    penanda: [
      { teks: 'Tambah pengurus: memberi jabatan Dewan (mis. Pradana, Sekretaris) kepada seorang Penegak aktif.', cari: { teks: 'Tambah pengurus', tag: 'button' } },
      { teks: 'Pengurus saat ini. Pensil mengubah jabatan, tempat sampah mencabutnya. Jabatan dicabut otomatis bila Penegak nonaktif atau alumni.', cari: { teks: 'Kepengurusan saat ini', mengandung: true, naik: 2 } },
      { teks: 'Setelah Musyawarah Ambalan: unduh berkas Excel berisi pengurus saat ini, ubah, lalu unggah lagi untuk mengganti seluruh kepengurusan sekaligus.', cari: { teks: 'Ganti kepengurusan lewat berkas Excel', induk: 'div.rounded-lg, section' } },
    ],
  },
  {
    id: 'pembina-periksa',
    akun: 'pembina',
    judul: 'Periksa Data',
    alt: 'Halaman Periksa Data dengan kartu kategori masalah, tombol Perbaiki, dan tautan Lihat baris.',
    langkah: [{ klikMenu: 'Periksa Data' }],
    penanda: [
      { teks: 'Ringkasan jumlah hal yang perlu diperiksa.', cari: { teks: 'hal perlu diperiksa', mengandung: true } },
      { teks: 'Kartu bercentang hijau = tidak ada masalah; kartu berjam = ada yang perlu dilengkapi, lengkap dengan jumlahnya.', cari: { teks: 'Belum ada Nomor Tanda Anggota (NTA)', induk: '.panel, div.rounded-lg, section, article' } },
      { teks: 'Lihat baris: menampilkan siapa saja yang bermasalah. Perbaiki: pintasan ke menu yang tepat untuk memperbaikinya.', cari: { teks: 'Lihat 10 baris', nth: 0 } },
    ],
  },
  {
    id: 'pembina-agenda',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1000 },
    judul: 'Agenda kegiatan tahunan',
    alt: 'Halaman Agenda dengan tombol Tambah kegiatan dan daftar kegiatan lengkap dengan hitung mundur, tombol ubah dan hapus.',
    langkah: [{ klikMenu: 'Agenda' }],
    penanda: [
      { teks: 'Tambah kegiatan: Musyawarah Ambalan, pelantikan, perkemahan, dan kegiatan lain. Pengingat H-30, H-7, dan H-1 dikirim otomatis kepada pengurus dan Penegak yang terkait.', cari: { teks: '+ Tambah kegiatan', tag: 'button' } },
      { teks: 'Satu kegiatan: judul, jenis, tanggal, tahun ajaran, jumlah Penegak terkait, dan keterangan. Urutannya dari yang paling dekat.', cari: { selector: 'main li', nth: 0 } },
      { teks: 'Hitung mundur (mis. H-7 = tujuh hari lagi). Kegiatan yang sudah lewat tampil pudar.', cari: { selector: 'main li span.rounded-full', nth: 0 } },
      { teks: 'Pensil mengubah kegiatan dan tempat sampah di sebelahnya menghapusnya. Hanya Pembina dan Admin Gudep yang dapat mengubah agenda.', cari: { selector: 'main li button[title="Ubah"]', nth: 0, pad: 7 } },
    ],
  },
  {
    id: 'pembina-kelolaberanda',
    akun: 'pembina',
    tinggi: { ponsel: 1000 },
    judul: 'Kelola Beranda (halaman muka gudep)',
    alt: 'Halaman Kelola Beranda dengan tab Kontak, Berita, Prestasi, Galeri, Media Sosial, Pertanyaan Umum, dan formulir kontak.',
    langkah: [{ klikMenu: 'Kelola Beranda' }],
    penanda: [
      { teks: 'Lihat beranda publik: pratinjau halaman muka yang dapat dilihat siapa saja tanpa masuk.', cari: { teks: 'Lihat beranda publik', tag: 'a' } },
      { teks: 'Tab isi: Kontak, Berita, Prestasi, Galeri, Media Sosial, dan Pertanyaan Umum. Berita, Prestasi, dan Galeri dari Dewan menunggu persetujuan Pembina sebelum terbit.', cari: { teks: 'Kontak', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Formulir tab yang dipilih. Semua tautan harus diawali https://.', cari: { teks: 'Kontak dan jadwal', induk: 'div.rounded-lg, section' } },
    ],
  },
  {
    id: 'dewan-sidang',
    akun: '10008',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Sidang Dewan Kehormatan',
    alt: 'Halaman Sidang Dewan Kehormatan dengan tab Antrian, Riwayat, dan Pengaturan, serta daftar Penegak yang siap disidangkan dengan tombol Buka lembar sidang.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Sidang' }],
    penanda: [
      { teks: 'Tab: Antrian (siap disidangkan), Riwayat (sidang yang sudah diputuskan), dan Pengaturan.', cari: { teks: 'Antrian', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Siap disidangkan: Penegak yang seluruh butir SKU tingkatnya sudah lulus dan belum dinyatakan Layak dan Lulus.', cari: { teks: 'Siap disidangkan', tag: 'h2' } },
      { teks: 'Buka lembar sidang: mengisi keputusan Layak dan Lulus atau Ditunda/Remedi, lalu mencetak berita acara bertanda tangan dan berkode QR.', cari: { teks: 'Buka lembar sidang', tag: 'button', nth: 0 } },
    ],
  },
  {
    id: 'pembina-penilaian',
    akun: 'pembina',
    data: 'panduan',
    judul: 'Lembar penilaian butir SKU',
    alt: 'Jendela Penilaian poin SKU dengan keterangan Penegak dan butir, pilihan hasil pengujian, tanggal uji, predikat, dan tombol Simpan dan verifikasi.',
    langkah: [{ klikMenu: 'Antrian' }, { klik: { teks: 'Nilai', tag: 'button', dalam: 'main', nth: 1 } }, { tunggu: 1500 }],
    penanda: [
      { teks: 'Penegak dan butir yang dinilai, status saat ini, dan catatan dari Penegak.', cari: { teks: 'Status saat ini', mengandung: true, dalam: '[role=dialog]', naik: 1 } },
      { teks: 'Hasil pengujian: Lulus, Perlu diulang (wajib catatan perbaikan), Mulai uji, atau Kembalikan ke belum diuji (wajib alasan).', cari: { teks: 'Hasil pengujian', dalam: '[role=dialog]', naik: 1 } },
      { teks: 'Tanggal uji dan predikat penilaian.', cari: { teks: 'Tanggal uji', dalam: '[role=dialog]', naik: 1 } },
      { teks: 'Simpan dan verifikasi: hasil resmi baru tercatat setelah Anda memasukkan PIN sendiri.', cari: { teks: 'Simpan dan verifikasi', tag: 'button', dalam: '[role=dialog]' } },
    ],
  },
  {
    id: 'dewan-sesi',
    akun: 'pembina',
    data: 'panduan',
    judul: 'Sesi ujian bersama',
    alt: 'Halaman Sesi ujian dengan tombol Sesi baru dan kartu sesi Ujian bersama SKU Bantara berstatus Terjadwal.',
    langkah: [{ klikMenu: 'Sesi ujian' }],
    penanda: [
      { teks: 'Sesi baru: pilih butir SKU, pesertanya, tanggal, dan tempat untuk satu ujian bersama.', cari: { teks: 'Sesi baru', tag: 'button' } },
      { teks: 'Satu sesi: nama, status (Terjadwal, Berlangsung, Selesai), jadwal, dan tempat.', cari: { teks: 'Ujian bersama SKU Bantara', induk: 'li' } },
      { teks: 'Progres: jumlah peserta, butir yang diuji, dan persentase yang sudah selesai. Penilaian tetap memakai lembar instrumen dan PIN penguji.', cari: { teks: '2 peserta', mengandung: true, induk: 'li' } },
    ],
  },
  {
    id: 'pembina-instrumen',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Instrumen penilaian SKU',
    alt: 'Halaman Instrumen Penilaian SKU dengan tab Instrumen dan Pengaturan, jumlah butir, pencarian, penyaring, dan daftar butir dengan tombol Buat.',
    langkah: [{ klikMenu: 'Instrumen' }],
    penanda: [
      { teks: 'Tab: Instrumen (daftar butir) dan Pengaturan.', cari: { teks: 'Instrumen', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Ringkasan: berapa butir sudah ditetapkan (dipakai), masih draf, atau belum ada instrumennya.', cari: { teks: 'Ditetapkan (dipakai)', dalam: 'main', naik: 2 } },
      { teks: 'Cari butir atau isi instrumen. Penyaring tingkat dan status ada di sebelahnya; Unduh Excel menyimpan daftar yang tampil.', cari: { selector: 'main input[type=search], main input[placeholder*="Cari butir"]', naik: 1 } },
      { teks: 'Buat atau ubah instrumen satu butir: kriteria, bobot, dan panduan penguji. Isi instrumen hanya terlihat penguji.', cari: { teks: 'Buat', tag: 'button', dalam: 'main', nth: 0 } },
    ],
  },
  {
    id: 'pembina-pelantikan',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1300 },
    judul: 'Pelantikan dan Saka',
    alt: 'Halaman Pelantikan dan Saka dengan tab Pelantikan dan Saka, formulir Catat pelantikan, dan daftar Penegak yang layak dilantik.',
    langkah: [{ klikMenu: 'Pelantikan' }],
    penanda: [
      { teks: 'Tab: Pelantikan (Bantara dan Laksana) dan Saka (keanggotaan Satuan Karya).', cari: { teks: 'Pelantikan', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Catat pelantikan: pilih tingkat, tanggal, tempat, dan kegiatan di Agenda (opsional) sesudah upacara terlaksana.', cari: { teks: 'Catat pelantikan', tag: 'h2' } },
      { teks: 'Daftar Penegak yang sudah menyelesaikan seluruh butir SKU tingkat itu. Centang yang dilantik; satu upacara dicatat sekaligus.', cari: { teks: 'Penegak (', mengandung: true, dalam: 'main' } },
    ],
  },
  {
    id: 'pembina-pra-uji',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1300 },
    judul: 'Pra-uji berjenjang',
    alt: 'Halaman Pra-uji SKU untuk Pembina dengan sakelar Pra-uji hidup, cakupan pra-uji, dan daftar pengajuan yang menunggu dengan tombol Lewati tahap.',
    langkah: [{ klikMenu: 'Pra-uji' }],
    penanda: [
      { teks: 'Sakelar pra-uji: hidup berarti pengajuan Penegak disaring Pinsa dan Bina Damping dulu, lalu diuji resmi Pembina. Dewan Ambalan tidak menguji resmi.', cari: { teks: 'Pra-uji: hidup', induk: '.panel' } },
      { teks: 'Cakupan pra-uji: persentase pengajuan yang melewati pra-uji dalam periode pilihan.', cari: { teks: 'Cakupan pra-uji', induk: '.panel' } },
      { teks: 'Menunggu pra-uji: pengajuan yang sedang di tangan Pinsa atau Bina Damping.', cari: { teks: 'Menunggu pra-uji (', mengandung: true, tag: 'h2' } },
      { teks: 'Lewati tahap: bila penilai berhalangan, teruskan ke tahap berikutnya atau langsung ke uji resmi Pembina.', cari: { teks: 'Lewati tahap', tag: 'button', nth: 0 } },
    ],
  },
  {
    id: 'pembina-perlindungan',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1500 },
    judul: 'Perlindungan anggota (Safe From Harm)',
    alt: 'Halaman Perlindungan Anggota dengan isian penerima laporan gugus depan dan tombol Simpan penerima laporan, lalu catatan anggota dewasa.',
    langkah: [{ klikMenu: 'Perlindungan' }],
    penanda: [
      { teks: 'Penerima laporan gugus depan: nama, kontak, dan prosedur yang ditampilkan kepada semua anggota di menu Akun saya. Aplikasi tidak menyimpan laporan kejadian (bersifat rahasia).', cari: { teks: 'Penerima laporan gugus depan', tag: 'h2', induk: '.panel' } },
      { teks: 'Simpan penerima laporan.', cari: { teks: 'Simpan penerima laporan', tag: 'button' } },
      { teks: 'Catatan anggota dewasa: pelatihan, pakta integritas, dan rekam jejak tiap Pembina dan Admin.', cari: { teks: 'Catatan anggota dewasa', tag: 'h2' } },
    ],
  },
  {
    id: 'dewan-iuran',
    akun: '10008',
    data: 'panduan',
    tinggi: { layar: 640, ponsel: 760 },
    judul: 'Mencatat iuran Jumat',
    alt: 'Halaman Iuran tampilan Dewan dengan tab Catat, Rekap, Kas, dan Asisten, serta pemilih tanggal latihan Jumat dan tombol Jumat sebelumnya.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Iuran' }, { klik: { teks: 'Jumat sebelumnya', mengandung: true, tag: 'button' } }, { tunggu: 3500 }],
    penanda: [
      { teks: 'Tab: Catat (mencatat iuran), Rekap (ringkasan), Kas (penutupan kas fisik), dan Asisten (asisten bendahara).', cari: { teks: 'Catat', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Tanggal latihan Jumat. Iuran dicatat pada sesi absensi hari itu, jadi sesinya harus sudah dibuat di menu Absensi.', cari: { teks: 'Tanggal latihan (Jumat)', dalam: 'main', naik: 1 } },
      { teks: 'Pindah antar Jumat: sebelumnya, berikutnya, atau langsung ke Jumat terakhir.', cari: { teks: 'Jumat terakhir', tag: 'button' } },
    ],
  },
  {
    id: 'dewan-peserta',
    akun: '10008',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Peserta: daftar Penegak',
    alt: 'Halaman Peserta tampilan Dewan dengan kolom cari, penyaring rombel, status, sangga, kelas, peran, jenis kelamin, agama, dan daftar Penegak dengan bilah progres SKU.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Peserta' }],
    penanda: [
      { teks: 'Cari menurut nama atau NIS.', cari: { selector: 'main input', nth: 0, naik: 1 } },
      { teks: 'Hanya rombel saya: membatasi daftar pada rombel tugas Anda. Hilangkan centang untuk melihat semua Penegak.', cari: { teks: 'Hanya rombel saya', mengandung: true, tag: 'label' } },
      { teks: 'Penyaring status, sangga, kelas, peran, jenis kelamin, dan agama. Bersihkan filter mengembalikan semuanya.', cari: { teks: 'Bersihkan filter', tag: 'button' } },
      { teks: 'Satu Penegak: kelas, sangga, peran, dan bilah progres Bantara dan Laksana. Sentuh untuk membuka detail SKU dan riwayatnya.', cari: { selector: 'main ul li, main li', nth: 0 } },
    ],
  },
  {
    id: 'dewan-portofolio',
    akun: '10008',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Portofolio: rekap kesiapan Calon Garuda',
    alt: 'Halaman Portofolio Penegak Garuda dengan tombol Unduh Excel, ringkasan angka, penyaring, dan tabel kesiapan tiap Calon Garuda dengan tombol Tinjau.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Portofolio' }],
    penanda: [
      { teks: 'Unduh Excel: rekap kesiapan seluruh Calon Garuda dalam satu berkas.', cari: { teks: 'Unduh Excel', mengandung: true, tag: 'button' } },
      { teks: 'Ringkasan: jumlah Calon Garuda, kesiapan rata-rata, dokumen siap, dan portofolio yang sudah lengkap.', cari: { teks: 'Portofolio lengkap', dalam: 'main', naik: 2 } },
      { teks: 'Satu Calon Garuda: persentase kesiapan dan jumlah dokumen siap. Tombol Tinjau di ujung baris (di ponsel, geser tabel ke samping) membuka 26 dokumen untuk diperiksa dan diberi catatan; Dewan Ambalan menilai, tidak mengisi milik Penegak.', cari: { selector: 'main tbody tr', nth: 0 } },
    ],
  },
  {
    id: 'dewan-periksa',
    akun: '10008',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Periksa Data: data yang perlu dilengkapi',
    alt: 'Halaman Periksa Data tampilan Dewan dengan ringkasan jumlah hal yang perlu diperiksa dan daftar kategori data.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Periksa Data' }],
    penanda: [
      { teks: 'Ringkasan: berapa hal yang perlu diperiksa di seluruh gudep.', cari: { teks: 'hal perlu diperiksa', mengandung: true, dalam: 'main' } },
      { teks: 'Satu kategori: data yang belum lengkap atau keliru (mis. kelas belum baku, belum ada NTA). Dewan Ambalan hanya melihat; perbaikan oleh Pembina atau Admin.', cari: { selector: 'main details, main section.panel, main .panel', nth: 0 } },
    ],
  },
  {
    id: 'dewan-bina-damping',
    akun: '10008',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Bina Damping rombel',
    alt: 'Halaman Sangga dan Bina Damping tampilan Dewan dengan tab Sangga dan Bina Damping, pilihan kelas dan rombel, dan daftar Bina Damping.',
    langkah: [{ klik: { teks: 'Dewan', tag: 'button', dalam: '[aria-label="Tampilan akun"]' } }, { tutupDialog: true }, { klikMenu: 'Sangga' }, { klik: { teks: 'Bina Damping', tag: 'button', dalam: 'main' } }, { tunggu: 3500 }],
    penanda: [
      { teks: 'Tab: Sangga (susunan sangga dan Pinsa) dan Bina Damping (penunjukan pendamping rombel).', cari: { teks: 'Bina Damping', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Pilih tahun ajaran dan kelas. Tiap rombel didampingi dua Bina Damping: Penegak berjabatan Dewan yang sedikitnya Calon Laksana; yang sudah Laksana didahulukan.', cari: { selector: 'main select', nth: 0, naik: 2 } },
    ],
  },
  {
    id: 'pembina-sangga',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1300 },
    judul: 'Sangga dan Pinsa',
    alt: 'Halaman Sangga dan Bina Damping untuk Pembina dengan tab Sangga dan Bina Damping, pilihan kelas dan rombel, peringatan, dan tabel Penegak dengan kolom Sangga dan Pinsa.',
    langkah: [{ klikMenu: 'Sangga' }],
    penanda: [
      { teks: 'Tab Sangga (mengatur sangga dan Pinsa) dan tab Bina Damping (menunjuk pendamping rombel).', cari: { teks: 'Bina Damping', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Pilih kelas dan rombel yang diatur.', cari: { teks: 'Rombel', tag: 'label', dalam: 'main' } },
      { teks: 'Peringatan jumlah Bina Damping dan sangga; tidak menghalangi penyimpanan.', cari: { teks: 'Perlu diperhatikan (tidak menghalangi penyimpanan):', dalam: 'main', naik: 1 } },
      { teks: 'Isi nama sangga tiap Penegak dan centang satu Pinsa (Pimpinan Sangga) per sangga; Pinsa minimal Calon Laksana.', cari: { selector: 'main table', nth: 0 } },
    ],
  },
  {
    id: 'pembina-raport',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1300 },
    judul: 'Nilai raport ekstrakurikuler',
    alt: 'Halaman Nilai Raport Ekstrakurikuler dengan pilihan tahun ajaran dan semester, tab Penilaian dan Pengaturan, ringkasan, penyaring, tombol Unduh Excel dan Cetak, serta tabel nilai.',
    langkah: [{ klikMenu: 'Raport' }],
    penanda: [
      { teks: 'Pilih tahun ajaran dan semester, lalu tab Penilaian atau Pengaturan (bobot dan deskripsi).', cari: { teks: 'Penilaian', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Ringkasan: jumlah Penegak, yang belum dinilai, draf saran, dan final.', cari: { teks: 'Belum dinilai', dalam: 'main', nth: 0, naik: 2 } },
      { teks: 'Unduh Excel per kelas atau cetak lembar raport; keduanya mengikuti penyaring di atasnya.', cari: { teks: 'Unduh Excel per kelas', tag: 'button' } },
      { teks: 'Tabel nilai: kehadiran, capaian SKU, sikap, skor, dan predikat. Deskripsi hanya saran; keputusan akhir ada pada Pembina.', layar: { selector: 'main table', nth: 0 }, ponsel: { selector: 'main ul.panel', nth: 0 } },
    ],
  },
  {
    id: 'pembina-laporan',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { layar: 1000, ponsel: 1500 },
    judul: 'Laporan tahunan gugus depan',
    alt: 'Halaman Laporan dengan pilihan Tahun Ajaran atau Tahun Kalender, tombol Susun laporan, dan hasil rekap laporan.',
    langkah: [{ klikMenu: 'Laporan' }, { klik: { teks: 'Susun laporan', tag: 'button' } }, { tunggu: 3500 }],
    penanda: [
      { teks: 'Pilih periode: Tahun Ajaran (Juli-Juni) atau Tahun Kalender (Januari-Desember), lalu tahunnya.', cari: { teks: 'Tahun Ajaran (Juli-Juni)', tag: 'button', naik: 1 } },
      { teks: 'Susun laporan: menghimpun rekap keanggotaan, pencapaian SKU, kehadiran, iuran, dan agenda untuk periode itu.', cari: { teks: 'Susun laporan', tag: 'button' } },
      { teks: 'Ringkasan hasil: Penegak aktif, pengurus Dewan, kegiatan pada periode, dan rata-rata kehadiran.', cari: { teks: 'Penegak aktif', dalam: 'main', naik: 2 } },
      { teks: 'Unduh Excel (banyak lembar) atau cetak/simpan PDF untuk diserahkan ke Kwartir Ranting dengan tembusan Kwartir Cabang.', cari: { teks: 'Unduh Excel (.xlsx)', tag: 'button', naik: 1 } },
    ],
  },
  {
    id: 'pembina-kelolamateri',
    akun: 'pembina',
    data: 'panduan',
    tinggi: { ponsel: 1100 },
    judul: 'Kelola materi belajar',
    alt: 'Halaman Kelola materi dengan tombol Tambah materi, ringkasan butir SKU yang sudah punya materi, dan daftar materi dengan tombol geser, ubah, dan hapus.',
    langkah: [{ klikMenu: 'Kelola Materi' }],
    penanda: [
      { teks: 'Tambah materi: lampirkan PDF dari Google Drive, beri judul dan daftar isi, lalu hubungkan dengan butir SKU.', cari: { teks: 'Tambah materi', tag: 'button' } },
      { teks: 'Ringkasan: berapa butir SKU yang sudah punya materi. "Lihat butir yang belum punya materi" membantu melengkapi.', cari: { teks: 'materi terhubung ke', mengandung: true, induk: 'div' } },
      { teks: 'Satu materi: judul, butir SKU terkait, jumlah bagian daftar isi, dan tautan Google Drive.', cari: { selector: 'main li', nth: 1 } },
      { teks: 'Geser urutan (panah), ubah (pensil), atau hapus (tong sampah). Urutan ini yang tampil di menu Materi semua pengguna.', cari: { selector: 'main li:nth-of-type(2) button', nth: 0, naik: 1 } },
    ],
  },
  // ---------- Admin Gudep ----------
  {
    id: 'admin-dashboard',
    akun: 'admin',
    tinggi: { ponsel: 1100 },
    judul: 'Dashboard Admin Gudep',
    alt: 'Dashboard Admin dengan ringkasan jumlah anggota, absensi, dan kelulusan SKU.',
    langkah: [{ klikMenu: 'Dashboard' }],
    penanda: [
      { teks: 'Ringkasan jumlah anggota: Penegak, Calon Bantara, Calon Laksana, dan lainnya.', cari: { teks: 'Anggota penegak', mengandung: true, induk: 'div.rounded-lg, section, .panel' } },
      { teks: 'Ringkasan kehadiran latihan Jumat dan kelulusan SKU seluruh gudep.', cari: { teks: 'Absensi latihan Jumat', dalam: 'main', induk: 'section' } },
    ],
  },
  {
    id: 'admin-anggota',
    akun: 'admin',
    tinggi: { ponsel: 1150 },
    judul: 'Data anggota',
    alt: 'Halaman Data anggota dengan tab Penegak, Dewan, Pembina, Admin Gudep, tombol Import Excel, Tambah anggota, dan daftar anggota.',
    langkah: [{ klikMenu: 'Anggota' }],
    penanda: [
      { teks: 'Unduh template Excel: berkas kosong berisi kolom yang dibutuhkan untuk impor.', cari: { teks: 'Unduh template Excel', tag: 'button' } },
      { teks: 'Import Excel: menambahkan banyak Penegak sekaligus dari berkas template yang sudah diisi.', cari: { teks: 'Import Excel', tag: 'button' } },
      { teks: 'Tambah anggota satu per satu. Admin cukup mengisi nama, NIS, dan rombel; data lainnya diisi Penegak sendiri.', cari: { teks: 'Tambah anggota', tag: 'button' } },
      { teks: 'Tab jenis anggota: Penegak, Dewan (akun lama), Pembina, Admin Gudep, dan Penugasan.', cari: { teks: 'Penegak', tag: 'button', dalam: 'main', naik: 1 } },
      { teks: 'Status: mengubah anggota menjadi aktif, nonaktif, atau alumni. Pensil mengubah data, tempat sampah menghapus.', cari: { teks: 'Status', tag: 'button', dalam: 'main', nth: 0 } },
    ],
  },
  {
    id: 'admin-naikkelas',
    akun: 'admin',
    tinggi: { ponsel: 1250 },
    judul: 'Naik kelas',
    alt: 'Halaman Naik kelas dengan jumlah aktif, nonaktif, alumni, pilihan tahun ajaran, tombol unduh dan unggah berkas Excel, dan tabel rombel baru serta aksi.',
    langkah: [{ klikMenu: 'Naik Kelas' }],
    penanda: [
      { teks: 'Jumlah anggota aktif, nonaktif (tidak melanjutkan Pramuka, masih siswa), dan alumni (lulus).', cari: { teks: 'Nonaktif', dalam: 'main', nth: 0, naik: 2 } },
      { teks: 'Tahun ajaran yang baru dimulai. Unduh berkas Excel, isi rombel baru dan aksi tiap Penegak, lalu unggah; atau pakai "Isian bawaan".', cari: { teks: 'Tahun ajaran yang baru dimulai', induk: 'div.rounded-lg, section' } },
      { teks: 'Tabel per Penegak: rombel baru dan aksi (Lanjut, Tidak lanjut, atau Lulus). Hasilnya dipratinjau lebih dulu sebelum diterapkan, dan dapat dibatalkan.', cari: { selector: 'main table', nth: 0, pad: 2 } },
    ],
  },
  {
    id: 'admin-gudep',
    akun: 'admin',
    tinggi: { ponsel: 1250 },
    judul: 'Data Gudep',
    alt: 'Halaman Data Gudep dengan isian identitas gugus depan dan ambalan, serta alamat dan kwartir.',
    langkah: [{ klikMenu: 'Data Gudep' }],
    penanda: [
      { teks: 'Fungsi halaman: isian ini dipakai pada kop surat, tanda tangan, nomor surat, dan semua dokumen cetak. Ubah di sini setiap ada pergantian pengurus atau pejabat.', cari: { teks: 'Identitas gugus depan, ambalan, dan pejabatnya', mengandung: true } },
      { teks: 'Identitas gugus depan dan ambalan: nama gudep, ambalan, sekolah, nomor gudep, dan kode surat.', cari: { teks: 'Identitas Gugus Depan dan Ambalan', induk: 'div.rounded-lg, section' } },
      { teks: 'Alamat, kontak, dan kwartir yang tercetak pada kop surat.', cari: { teks: 'Alamat, kontak, dan kwartir', induk: 'div.rounded-lg, section' } },
    ],
  },
  {
    id: 'admin-periksa',
    akun: 'admin',
    judul: 'Periksa Data (Admin)',
    alt: 'Halaman Periksa Data dengan kartu kategori masalah dan tombol Perbaiki.',
    langkah: [{ klikMenu: 'Periksa Data' }],
    penanda: [
      { teks: 'Tiap kartu = satu jenis masalah data, lengkap dengan jumlah temuannya.', cari: { teks: 'Belum ada Nomor Tanda Anggota (NTA)', induk: '.panel, div.rounded-lg, section, article' } },
      { teks: 'Perbaiki: langsung menuju menu tempat Admin dapat memperbaikinya. Sebagian perbaikan hanya dapat dilakukan Admin.', cari: { teks: 'Perbaiki', tag: 'button', nth: 0 } },
      { teks: 'Lihat baris: daftar rincian anggota yang bermasalah.', cari: { teks: 'Lihat 10 baris', nth: 0 } },
    ],
  },
];
