-- ============================================================================
-- PERIKSA PEMASANGAN SIGARDA (HANYA MEMBACA)
--
-- Memastikan database Supabase Anda sudah memuat semua migrasi: tabel, kolom, batasan, indeks, kebijakan akses (RLS), pemicu, dan fungsi (isinya dibandingkan
-- dengan versi terbaru), serta lingkungan notifikasi (pg_net, pg_cron, konfigurasi push). Tidak mengubah apa pun; aman dijalankan kapan saja dan berulang.
-- Dibuat otomatis oleh scripts/buat-periksa.mjs dari skema terbaru: jangan diubah tangan.
--
-- Cara: Supabase > SQL Editor > New query > tempel seluruh isi berkas ini > Run.
--
-- Cara membaca hasil: baris "== RINGKASAN ==" (satu per kategori) lalu daftar yang BERMASALAH. Semua kategori berstatus OK = database mutakhir.
--   KURANG = objek belum ada (migrasi belum dijalankan); BEDA = ada tetapi isinya bukan versi terbaru (jalankan ulang migrasi yang menimpanya, urut sesuai README);
--   HAK BEDA / RLS BEDA = hak akses tidak sama. Sesudah menjalankan migrasi, jalankan skrip ini lagi sampai semuanya OK.
-- Edge Function (sigarda, notif-push) TIDAK dapat diperiksa dari SQL: lihat baris "PERIKSA MANUAL".
-- ============================================================================
with
h_tabel(nama, rls, sel) as (values
    ('absensi_hadir', true, true),
    ('absensi_sesi', true, true),
    ('agenda', true, true),
    ('asisten_iuran', true, true),
    ('bina_damping', true, false),
    ('dokumen_terbit', true, true),
    ('dokumen_urut', true, true),
    ('garuda_berkas_token', true, false),
    ('guru_agama', true, true),
    ('instrumen', true, true),
    ('instrumen_kriteria', true, true),
    ('instrumen_panduan', true, true),
    ('instrumen_penguji', true, true),
    ('iuran', true, true),
    ('iuran_kas', true, true),
    ('iuran_log', true, true),
    ('keepalive_konfigurasi', true, false),
    ('kegiatan_usulan', true, true),
    ('kepengurusan_log', true, true),
    ('login_gagal', true, false),
    ('materi', true, true),
    ('naik_kelas_batch', true, true),
    ('naik_kelas_log', true, true),
    ('notifikasi', true, true),
    ('pelantikan', true, true),
    ('pengaturan', true, true),
    ('pengukuhan_dewan', true, true),
    ('penugasan_log', true, true),
    ('penugasan_peserta', true, true),
    ('penugasan_rombel', true, true),
    ('pf_item', true, true),
    ('portofolio', true, true),
    ('portofolio_jurnal', true, true),
    ('profiles', true, true),
    ('push_konfigurasi', true, false),
    ('push_langganan', true, false),
    ('raport', true, true),
    ('saka_anggota', true, true),
    ('sertifikat_tingkat', true, false),
    ('sesi_ujian', true, true),
    ('sesi_ujian_butir', true, true),
    ('sesi_ujian_peserta', true, true),
    ('sidang_dk', true, true),
    ('sidang_urut', true, true),
    ('sku_butir', true, true),
    ('sku_penilaian', true, true),
    ('sku_pra_uji', true, true),
    ('sku_progress', true, true),
    ('sku_riwayat', true, true),
    ('sku_unit', true, true),
    ('tkk_capaian', true, true),
    ('tkk_katalog', true, true),
    ('tkk_krida', true, true)
),
h_kolom(tabel, kolom, tipe) as (values
    ('absensi_hadir', 'oleh', 'uuid'),
    ('absensi_hadir', 'peserta_id', 'uuid'),
    ('absensi_hadir', 'status', 'text'),
    ('absensi_hadir', 'tanggal', 'date'),
    ('absensi_hadir', 'waktu', 'timestamp with time zone'),
    ('absensi_sesi', 'dibuat_oleh', 'uuid'),
    ('absensi_sesi', 'dibuat_pada', 'timestamp with time zone'),
    ('absensi_sesi', 'tanggal', 'date'),
    ('agenda', 'dibuat_oleh', 'uuid'),
    ('agenda', 'dibuat_pada', 'timestamp with time zone'),
    ('agenda', 'diubah_pada', 'timestamp with time zone'),
    ('agenda', 'id', 'bigint'),
    ('agenda', 'jenis', 'text'),
    ('agenda', 'judul', 'text'),
    ('agenda', 'keterangan', 'text'),
    ('agenda', 'lewati_batas', 'boolean'),
    ('agenda', 'peserta_terkait', 'ARRAY'),
    ('agenda', 'tahun_ajaran', 'text'),
    ('agenda', 'tanggal', 'date'),
    ('asisten_iuran', 'ditunjuk_oleh', 'uuid'),
    ('asisten_iuran', 'ditunjuk_pada', 'timestamp with time zone'),
    ('asisten_iuran', 'peserta_id', 'uuid'),
    ('bina_damping', 'ditetapkan_oleh', 'uuid'),
    ('bina_damping', 'ditetapkan_pada', 'timestamp with time zone'),
    ('bina_damping', 'penegak_id', 'uuid'),
    ('bina_damping', 'rombel', 'text'),
    ('bina_damping', 'tahun_ajaran', 'text'),
    ('dokumen_terbit', 'dibuat_oleh', 'uuid'),
    ('dokumen_terbit', 'dibuat_oleh_jabatan', 'text'),
    ('dokumen_terbit', 'dibuat_oleh_nama', 'text'),
    ('dokumen_terbit', 'dibuat_pada', 'timestamp with time zone'),
    ('dokumen_terbit', 'dicabut_alasan', 'text'),
    ('dokumen_terbit', 'dicabut_oleh', 'uuid'),
    ('dokumen_terbit', 'dicabut_pada', 'timestamp with time zone'),
    ('dokumen_terbit', 'id', 'bigint'),
    ('dokumen_terbit', 'jenis', 'text'),
    ('dokumen_terbit', 'kode', 'text'),
    ('dokumen_terbit', 'nomor', 'text'),
    ('dokumen_terbit', 'nomor_urut', 'integer'),
    ('dokumen_terbit', 'payload', 'jsonb'),
    ('dokumen_terbit', 'penanda_tangan_jabatan', 'text'),
    ('dokumen_terbit', 'penanda_tangan_nama', 'text'),
    ('dokumen_terbit', 'penerbit', 'text'),
    ('dokumen_terbit', 'peserta_id', 'uuid'),
    ('dokumen_terbit', 'peserta_nama', 'text'),
    ('dokumen_terbit', 'tanggal', 'date'),
    ('dokumen_terbit', 'token', 'text'),
    ('dokumen_urut', 'jenis', 'text'),
    ('dokumen_urut', 'tahun', 'integer'),
    ('dokumen_urut', 'terakhir', 'integer'),
    ('garuda_berkas_token', 'dibuat_oleh', 'uuid'),
    ('garuda_berkas_token', 'dibuat_oleh_nama', 'text'),
    ('garuda_berkas_token', 'dibuat_pada', 'timestamp with time zone'),
    ('garuda_berkas_token', 'dicabut_oleh', 'uuid'),
    ('garuda_berkas_token', 'dicabut_pada', 'timestamp with time zone'),
    ('garuda_berkas_token', 'id', 'bigint'),
    ('garuda_berkas_token', 'peserta_id', 'uuid'),
    ('garuda_berkas_token', 'token', 'text'),
    ('guru_agama', 'agama', 'text'),
    ('guru_agama', 'diubah_oleh', 'uuid'),
    ('guru_agama', 'diubah_pada', 'timestamp with time zone'),
    ('guru_agama', 'id', 'bigint'),
    ('guru_agama', 'keterangan', 'text'),
    ('guru_agama', 'nama', 'text'),
    ('instrumen', 'cara_uji', 'text'),
    ('instrumen', 'diubah_oleh', 'uuid'),
    ('instrumen', 'diubah_pada', 'timestamp with time zone'),
    ('instrumen', 'sku_id', 'text'),
    ('instrumen', 'status', 'text'),
    ('instrumen_kriteria', 'bobot', 'smallint'),
    ('instrumen_kriteria', 'id', 'bigint'),
    ('instrumen_kriteria', 'jenis', 'text'),
    ('instrumen_kriteria', 'sku_id', 'text'),
    ('instrumen_kriteria', 'sumber', 'text'),
    ('instrumen_kriteria', 'teks', 'text'),
    ('instrumen_kriteria', 'urutan', 'smallint'),
    ('instrumen_kriteria', 'wajib', 'boolean'),
    ('instrumen_panduan', 'kriteria_id', 'bigint'),
    ('instrumen_panduan', 'panduan', 'text'),
    ('instrumen_penguji', 'instruksi', 'text'),
    ('instrumen_penguji', 'sku_id', 'text'),
    ('iuran', 'jenis', 'text'),
    ('iuran', 'jumlah', 'integer'),
    ('iuran', 'oleh', 'uuid'),
    ('iuran', 'peserta_id', 'uuid'),
    ('iuran', 'tanggal', 'date'),
    ('iuran', 'waktu', 'timestamp with time zone'),
    ('iuran_kas', 'catatan', 'text'),
    ('iuran_kas', 'oleh', 'uuid'),
    ('iuran_kas', 'tanggal', 'date'),
    ('iuran_kas', 'total_fisik', 'integer'),
    ('iuran_kas', 'waktu', 'timestamp with time zone'),
    ('iuran_log', 'id', 'bigint'),
    ('iuran_log', 'jenis', 'text'),
    ('iuran_log', 'jumlah_baru', 'integer'),
    ('iuran_log', 'jumlah_lama', 'integer'),
    ('iuran_log', 'oleh', 'uuid'),
    ('iuran_log', 'peserta_id', 'uuid'),
    ('iuran_log', 'tanggal', 'date'),
    ('iuran_log', 'waktu', 'timestamp with time zone'),
    ('keepalive_konfigurasi', 'diubah', 'timestamp with time zone'),
    ('keepalive_konfigurasi', 'id', 'boolean'),
    ('keepalive_konfigurasi', 'kunci', 'text'),
    ('keepalive_konfigurasi', 'pesan_terakhir', 'text'),
    ('keepalive_konfigurasi', 'ping_id', 'bigint'),
    ('keepalive_konfigurasi', 'ping_terakhir', 'timestamp with time zone'),
    ('keepalive_konfigurasi', 'status_terakhir', 'integer'),
    ('keepalive_konfigurasi', 'url', 'text'),
    ('kegiatan_usulan', 'agenda_id', 'bigint'),
    ('kegiatan_usulan', 'catatan', 'text'),
    ('kegiatan_usulan', 'catatan_tinjauan', 'text'),
    ('kegiatan_usulan', 'diajukan_oleh', 'uuid'),
    ('kegiatan_usulan', 'diajukan_oleh_nama', 'text'),
    ('kegiatan_usulan', 'diajukan_pada', 'timestamp with time zone'),
    ('kegiatan_usulan', 'diping_pada', 'timestamp with time zone'),
    ('kegiatan_usulan', 'ditinjau_oleh', 'uuid'),
    ('kegiatan_usulan', 'ditinjau_oleh_nama', 'text'),
    ('kegiatan_usulan', 'ditinjau_pada', 'timestamp with time zone'),
    ('kegiatan_usulan', 'dokumen_url', 'text'),
    ('kegiatan_usulan', 'id', 'bigint'),
    ('kegiatan_usulan', 'jenis', 'text'),
    ('kegiatan_usulan', 'status', 'text'),
    ('kegiatan_usulan', 'tahun_ajaran', 'text'),
    ('kegiatan_usulan', 'tanggal_usul', 'date'),
    ('kepengurusan_log', 'alasan', 'text'),
    ('kepengurusan_log', 'id', 'bigint'),
    ('kepengurusan_log', 'jabatan_baru', 'text'),
    ('kepengurusan_log', 'jabatan_lama', 'text'),
    ('kepengurusan_log', 'nis', 'text'),
    ('kepengurusan_log', 'oleh', 'uuid'),
    ('kepengurusan_log', 'oleh_nama', 'text'),
    ('kepengurusan_log', 'peserta_id', 'uuid'),
    ('kepengurusan_log', 'peserta_nama', 'text'),
    ('kepengurusan_log', 'tindakan', 'text'),
    ('kepengurusan_log', 'waktu', 'timestamp with time zone'),
    ('login_gagal', 'diperbarui', 'timestamp with time zone'),
    ('login_gagal', 'jumlah', 'integer'),
    ('login_gagal', 'terkunci_sampai', 'timestamp with time zone'),
    ('login_gagal', 'username', 'text'),
    ('materi', 'bagian', 'jsonb'),
    ('materi', 'butir', 'ARRAY'),
    ('materi', 'deskripsi', 'text'),
    ('materi', 'dibuat', 'date'),
    ('materi', 'dibuat_oleh', 'uuid'),
    ('materi', 'file_id', 'text'),
    ('materi', 'id', 'uuid'),
    ('materi', 'judul', 'text'),
    ('materi', 'resource_key', 'text'),
    ('materi', 'tautan', 'text'),
    ('materi', 'urutan', 'integer'),
    ('naik_kelas_batch', 'dibatalkan_oleh', 'uuid'),
    ('naik_kelas_batch', 'dibatalkan_pada', 'timestamp with time zone'),
    ('naik_kelas_batch', 'id', 'bigint'),
    ('naik_kelas_batch', 'oleh', 'uuid'),
    ('naik_kelas_batch', 'oleh_nama', 'text'),
    ('naik_kelas_batch', 'ringkasan', 'jsonb'),
    ('naik_kelas_batch', 'tahun_ajaran', 'text'),
    ('naik_kelas_batch', 'waktu', 'timestamp with time zone'),
    ('naik_kelas_log', 'aksi', 'text'),
    ('naik_kelas_log', 'batch_id', 'bigint'),
    ('naik_kelas_log', 'catatan', 'text'),
    ('naik_kelas_log', 'dari_kelas', 'text'),
    ('naik_kelas_log', 'dari_lulus_ta', 'text'),
    ('naik_kelas_log', 'dari_status', 'text'),
    ('naik_kelas_log', 'dari_status_pada', 'date'),
    ('naik_kelas_log', 'id', 'bigint'),
    ('naik_kelas_log', 'ke_kelas', 'text'),
    ('naik_kelas_log', 'ke_status', 'text'),
    ('naik_kelas_log', 'nis', 'text'),
    ('naik_kelas_log', 'oleh', 'uuid'),
    ('naik_kelas_log', 'oleh_nama', 'text'),
    ('naik_kelas_log', 'peserta_id', 'uuid'),
    ('naik_kelas_log', 'peserta_nama', 'text'),
    ('naik_kelas_log', 'waktu', 'timestamp with time zone'),
    ('notifikasi', 'dibaca_pada', 'timestamp with time zone'),
    ('notifikasi', 'dibuat', 'timestamp with time zone'),
    ('notifikasi', 'id', 'bigint'),
    ('notifikasi', 'isi', 'text'),
    ('notifikasi', 'jenis', 'text'),
    ('notifikasi', 'judul', 'text'),
    ('notifikasi', 'kunci', 'text'),
    ('notifikasi', 'penerima_id', 'uuid'),
    ('notifikasi', 'push_status', 'text'),
    ('notifikasi', 'tautan', 'jsonb'),
    ('pelantikan', 'agenda_id', 'bigint'),
    ('pelantikan', 'catatan', 'text'),
    ('pelantikan', 'dicatat_oleh', 'uuid'),
    ('pelantikan', 'dicatat_pada', 'timestamp with time zone'),
    ('pelantikan', 'id', 'bigint'),
    ('pelantikan', 'peserta_id', 'uuid'),
    ('pelantikan', 'tanggal', 'date'),
    ('pelantikan', 'tempat', 'text'),
    ('pelantikan', 'tingkat', 'text'),
    ('pengaturan', 'diubah_oleh', 'uuid'),
    ('pengaturan', 'diubah_pada', 'timestamp with time zone'),
    ('pengaturan', 'kunci', 'text'),
    ('pengaturan', 'nilai', 'jsonb'),
    ('pengukuhan_dewan', 'catatan', 'text'),
    ('pengukuhan_dewan', 'diubah_oleh', 'uuid'),
    ('pengukuhan_dewan', 'diubah_pada', 'timestamp with time zone'),
    ('pengukuhan_dewan', 'nomor_sk', 'text'),
    ('pengukuhan_dewan', 'rekomendasi_nomor', 'text'),
    ('pengukuhan_dewan', 'rekomendasi_tanggal', 'date'),
    ('pengukuhan_dewan', 'tahun_ajaran', 'text'),
    ('pengukuhan_dewan', 'tanggal_sk', 'date'),
    ('penugasan_log', 'catatan', 'text'),
    ('penugasan_log', 'id', 'bigint'),
    ('penugasan_log', 'oleh', 'uuid'),
    ('penugasan_log', 'oleh_nama', 'text'),
    ('penugasan_log', 'penguji_id', 'uuid'),
    ('penugasan_log', 'penguji_nama', 'text'),
    ('penugasan_log', 'peserta_id', 'uuid'),
    ('penugasan_log', 'peserta_nama', 'text'),
    ('penugasan_log', 'rombel', 'text'),
    ('penugasan_log', 'tahun_ajaran', 'text'),
    ('penugasan_log', 'tindakan', 'text'),
    ('penugasan_log', 'waktu', 'timestamp with time zone'),
    ('penugasan_peserta', 'ditetapkan_oleh', 'uuid'),
    ('penugasan_peserta', 'ditetapkan_pada', 'timestamp with time zone'),
    ('penugasan_peserta', 'penguji_id', 'uuid'),
    ('penugasan_peserta', 'peserta_id', 'uuid'),
    ('penugasan_peserta', 'tahun_ajaran', 'text'),
    ('penugasan_rombel', 'ditetapkan_oleh', 'uuid'),
    ('penugasan_rombel', 'ditetapkan_pada', 'timestamp with time zone'),
    ('penugasan_rombel', 'penguji_id', 'uuid'),
    ('penugasan_rombel', 'rombel', 'text'),
    ('penugasan_rombel', 'tahun_ajaran', 'text'),
    ('pf_item', 'id', 'text'),
    ('portofolio', 'catatan', 'text'),
    ('portofolio', 'catatan_penguji', 'text'),
    ('portofolio', 'catatan_penguji_oleh', 'uuid'),
    ('portofolio', 'diperbarui', 'timestamp with time zone'),
    ('portofolio', 'item_id', 'text'),
    ('portofolio', 'peserta_id', 'uuid'),
    ('portofolio', 'status', 'text'),
    ('portofolio', 'tautan', 'text'),
    ('portofolio_jurnal', 'id', 'bigint'),
    ('portofolio_jurnal', 'item_id', 'text'),
    ('portofolio_jurnal', 'oleh', 'uuid'),
    ('portofolio_jurnal', 'peserta_id', 'uuid'),
    ('portofolio_jurnal', 'teks', 'text'),
    ('portofolio_jurnal', 'waktu', 'timestamp with time zone'),
    ('profiles', 'agama', 'text'),
    ('profiles', 'calon_garuda', 'date'),
    ('profiles', 'dibuat', 'date'),
    ('profiles', 'id', 'uuid'),
    ('profiles', 'jabatan', 'text'),
    ('profiles', 'jabatan_dewan', 'text'),
    ('profiles', 'jenis_kelamin', 'text'),
    ('profiles', 'kelas', 'text'),
    ('profiles', 'lulus_ta', 'text'),
    ('profiles', 'nama', 'text'),
    ('profiles', 'nis', 'text'),
    ('profiles', 'nta', 'text'),
    ('profiles', 'pin_direset_oleh', 'uuid'),
    ('profiles', 'pin_direset_pada', 'timestamp with time zone'),
    ('profiles', 'pin_diubah', 'timestamp with time zone'),
    ('profiles', 'pinsa', 'boolean'),
    ('profiles', 'role', 'text'),
    ('profiles', 'sangga', 'text'),
    ('profiles', 'status', 'text'),
    ('profiles', 'status_pada', 'date'),
    ('profiles', 'username', 'text'),
    ('profiles', 'wajib_ganti_pin', 'boolean'),
    ('profiles', 'whatsapp', 'text'),
    ('push_konfigurasi', 'diubah', 'timestamp with time zone'),
    ('push_konfigurasi', 'id', 'boolean'),
    ('push_konfigurasi', 'kunci_publik', 'text'),
    ('push_konfigurasi', 'rahasia', 'text'),
    ('push_konfigurasi', 'url', 'text'),
    ('push_langganan', 'agen', 'text'),
    ('push_langganan', 'auth', 'text'),
    ('push_langganan', 'dibuat', 'timestamp with time zone'),
    ('push_langganan', 'diperbarui', 'timestamp with time zone'),
    ('push_langganan', 'endpoint', 'text'),
    ('push_langganan', 'id', 'bigint'),
    ('push_langganan', 'p256dh', 'text'),
    ('push_langganan', 'penerima_id', 'uuid'),
    ('raport', 'capaian_lulus', 'smallint'),
    ('raport', 'capaian_target', 'smallint'),
    ('raport', 'catatan_predikat', 'text'),
    ('raport', 'deskripsi', 'text'),
    ('raport', 'diubah_oleh', 'uuid'),
    ('raport', 'diubah_pada', 'timestamp with time zone'),
    ('raport', 'hadir', 'smallint'),
    ('raport', 'karakter', 'ARRAY'),
    ('raport', 'kehadiran_persen', 'smallint'),
    ('raport', 'pertemuan', 'smallint'),
    ('raport', 'peserta_id', 'uuid'),
    ('raport', 'predikat_akhir', 'text'),
    ('raport', 'predikat_hitung', 'text'),
    ('raport', 'semester', 'text'),
    ('raport', 'sikap', 'smallint'),
    ('raport', 'skk', 'smallint'),
    ('raport', 'skor', 'smallint'),
    ('raport', 'status', 'text'),
    ('raport', 'tahun_ajaran', 'text'),
    ('raport', 'tingkat', 'text'),
    ('saka_anggota', 'catatan', 'text'),
    ('saka_anggota', 'dicatat_oleh', 'uuid'),
    ('saka_anggota', 'dicatat_pada', 'timestamp with time zone'),
    ('saka_anggota', 'id', 'bigint'),
    ('saka_anggota', 'peserta_id', 'uuid'),
    ('saka_anggota', 'saka', 'text'),
    ('saka_anggota', 'status', 'text'),
    ('saka_anggota', 'surat_url', 'text'),
    ('saka_anggota', 'tanggal_masuk', 'date'),
    ('saka_anggota', 'tanggal_selesai', 'date'),
    ('sertifikat_tingkat', 'diterbitkan_oleh', 'uuid'),
    ('sertifikat_tingkat', 'diterbitkan_pada', 'timestamp with time zone'),
    ('sertifikat_tingkat', 'peserta_id', 'uuid'),
    ('sertifikat_tingkat', 'tingkat', 'text'),
    ('sertifikat_tingkat', 'token', 'text'),
    ('sesi_ujian', 'catatan', 'text'),
    ('sesi_ujian', 'dibuat_oleh', 'uuid'),
    ('sesi_ujian', 'dibuat_pada', 'timestamp with time zone'),
    ('sesi_ujian', 'id', 'integer'),
    ('sesi_ujian', 'nama', 'text'),
    ('sesi_ujian', 'status', 'text'),
    ('sesi_ujian', 'tanggal', 'date'),
    ('sesi_ujian', 'tempat', 'text'),
    ('sesi_ujian_butir', 'butir_id', 'text'),
    ('sesi_ujian_butir', 'sesi_id', 'integer'),
    ('sesi_ujian_peserta', 'peserta_id', 'uuid'),
    ('sesi_ujian_peserta', 'sesi_id', 'integer'),
    ('sidang_dk', 'butir_belum', 'ARRAY'),
    ('sidang_dk', 'capaian_lulus', 'integer'),
    ('sidang_dk', 'capaian_total', 'integer'),
    ('sidang_dk', 'catatan', 'text'),
    ('sidang_dk', 'dibuat_oleh', 'uuid'),
    ('sidang_dk', 'dibuat_pada', 'timestamp with time zone'),
    ('sidang_dk', 'id', 'integer'),
    ('sidang_dk', 'keputusan', 'text'),
    ('sidang_dk', 'ketua_nama', 'text'),
    ('sidang_dk', 'ketua_sebutan', 'text'),
    ('sidang_dk', 'kode', 'text'),
    ('sidang_dk', 'magang', 'text'),
    ('sidang_dk', 'nomor_ba', 'text'),
    ('sidang_dk', 'nomor_urut', 'integer'),
    ('sidang_dk', 'nta', 'text'),
    ('sidang_dk', 'peserta_id', 'uuid'),
    ('sidang_dk', 'tanggal', 'date'),
    ('sidang_dk', 'tingkat', 'text'),
    ('sidang_dk', 'token', 'text'),
    ('sidang_dk', 'tugas_adat', 'text'),
    ('sidang_dk', 'tugas_adat_ket', 'text'),
    ('sidang_urut', 'tahun', 'integer'),
    ('sidang_urut', 'terakhir', 'integer'),
    ('sku_butir', 'id', 'text'),
    ('sku_butir', 'no', 'integer'),
    ('sku_butir', 'teks', 'text'),
    ('sku_butir', 'tingkat', 'text'),
    ('sku_penilaian', 'catatan', 'text'),
    ('sku_penilaian', 'diganti', 'boolean'),
    ('sku_penilaian', 'hasil', 'text'),
    ('sku_penilaian', 'id', 'bigint'),
    ('sku_penilaian', 'penguji_id', 'uuid'),
    ('sku_penilaian', 'peserta_id', 'uuid'),
    ('sku_penilaian', 'rincian', 'jsonb'),
    ('sku_penilaian', 'saran', 'text'),
    ('sku_penilaian', 'skor', 'smallint'),
    ('sku_penilaian', 'sku_id', 'text'),
    ('sku_penilaian', 'tanggal_uji', 'date'),
    ('sku_penilaian', 'wajib_ok', 'boolean'),
    ('sku_penilaian', 'waktu', 'timestamp with time zone'),
    ('sku_pra_uji', 'catatan', 'text'),
    ('sku_pra_uji', 'catatan_peserta', 'text'),
    ('sku_pra_uji', 'dibuat', 'timestamp with time zone'),
    ('sku_pra_uji', 'diputuskan_pada', 'timestamp with time zone'),
    ('sku_pra_uji', 'id', 'bigint'),
    ('sku_pra_uji', 'jadwal', 'date'),
    ('sku_pra_uji', 'penilai_id', 'uuid'),
    ('sku_pra_uji', 'penilai_nama', 'text'),
    ('sku_pra_uji', 'peserta_id', 'uuid'),
    ('sku_pra_uji', 'sku_id', 'text'),
    ('sku_pra_uji', 'status', 'text'),
    ('sku_pra_uji', 'tahap', 'text'),
    ('sku_progress', 'catatan', 'text'),
    ('sku_progress', 'catatan_peserta', 'text'),
    ('sku_progress', 'diubah', 'timestamp with time zone'),
    ('sku_progress', 'diverifikasi_pada', 'timestamp with time zone'),
    ('sku_progress', 'jadwal', 'date'),
    ('sku_progress', 'nilai', 'text'),
    ('sku_progress', 'penguji_id', 'uuid'),
    ('sku_progress', 'peserta_id', 'uuid'),
    ('sku_progress', 'sku_id', 'text'),
    ('sku_progress', 'status', 'text'),
    ('sku_progress', 'tanggal_uji', 'date'),
    ('sku_progress', 'verifikasi', 'text'),
    ('sku_progress', 'verifikasi_token', 'text'),
    ('sku_riwayat', 'id', 'bigint'),
    ('sku_riwayat', 'oleh', 'uuid'),
    ('sku_riwayat', 'peserta_id', 'uuid'),
    ('sku_riwayat', 'sku_id', 'text'),
    ('sku_riwayat', 'teks', 'text'),
    ('sku_riwayat', 'waktu', 'timestamp with time zone'),
    ('sku_unit', 'agama', 'text'),
    ('sku_unit', 'butir_id', 'text'),
    ('sku_unit', 'butir_no', 'integer'),
    ('sku_unit', 'id', 'text'),
    ('sku_unit', 'sub', 'integer'),
    ('sku_unit', 'tingkat', 'text'),
    ('tkk_capaian', 'bukti_url', 'text'),
    ('tkk_capaian', 'catatan', 'text'),
    ('tkk_capaian', 'dicatat_oleh', 'uuid'),
    ('tkk_capaian', 'dicatat_pada', 'timestamp with time zone'),
    ('tkk_capaian', 'id', 'bigint'),
    ('tkk_capaian', 'melatih', 'text'),
    ('tkk_capaian', 'penguji1', 'text'),
    ('tkk_capaian', 'penguji2', 'text'),
    ('tkk_capaian', 'peserta_id', 'uuid'),
    ('tkk_capaian', 'tanggal', 'date'),
    ('tkk_capaian', 'tingkat', 'text'),
    ('tkk_capaian', 'tkk_id', 'text'),
    ('tkk_katalog', 'agama', 'text'),
    ('tkk_katalog', 'bidang', 'smallint'),
    ('tkk_katalog', 'golongan', 'text'),
    ('tkk_katalog', 'id', 'text'),
    ('tkk_katalog', 'nama', 'text'),
    ('tkk_katalog', 'sumber', 'text'),
    ('tkk_katalog', 'urut', 'smallint'),
    ('tkk_krida', 'bukti_url', 'text'),
    ('tkk_krida', 'catatan', 'text'),
    ('tkk_krida', 'dicatat_oleh', 'uuid'),
    ('tkk_krida', 'dicatat_pada', 'timestamp with time zone'),
    ('tkk_krida', 'id', 'bigint'),
    ('tkk_krida', 'nama', 'text'),
    ('tkk_krida', 'peserta_id', 'uuid'),
    ('tkk_krida', 'saka', 'text'),
    ('tkk_krida', 'tanggal', 'date')
),
h_batasan(tabel, nama, potongan) as (values
    ('absensi_hadir', 'absensi_hadir_oleh_fkey', null::text),
    ('absensi_hadir', 'absensi_hadir_peserta_id_fkey', null::text),
    ('absensi_hadir', 'absensi_hadir_pkey', null::text),
    ('absensi_hadir', 'absensi_hadir_status_check', null::text),
    ('absensi_hadir', 'absensi_hadir_tanggal_fkey', null::text),
    ('absensi_sesi', 'absensi_sesi_dibuat_oleh_fkey', null::text),
    ('absensi_sesi', 'absensi_sesi_pkey', null::text),
    ('absensi_sesi', 'absensi_sesi_tanggal_check', null::text),
    ('agenda', 'agenda_dibuat_oleh_fkey', null::text),
    ('agenda', 'agenda_jenis_check', null::text),
    ('agenda', 'agenda_judul_check', null::text),
    ('agenda', 'agenda_keterangan_check', null::text),
    ('agenda', 'agenda_pkey', null::text),
    ('agenda', 'agenda_tahun_ajaran_check', null::text),
    ('asisten_iuran', 'asisten_iuran_ditunjuk_oleh_fkey', null::text),
    ('asisten_iuran', 'asisten_iuran_peserta_id_fkey', null::text),
    ('asisten_iuran', 'asisten_iuran_pkey', null::text),
    ('bina_damping', 'bina_damping_ditetapkan_oleh_fkey', null::text),
    ('bina_damping', 'bina_damping_penegak_id_fkey', null::text),
    ('bina_damping', 'bina_damping_pkey', null::text),
    ('bina_damping', 'bina_damping_rombel_check', null::text),
    ('bina_damping', 'bina_damping_tahun_ajaran_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_dibuat_oleh_fkey', null::text),
    ('dokumen_terbit', 'dokumen_terbit_dicabut_alasan_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_dicabut_oleh_fkey', null::text),
    ('dokumen_terbit', 'dokumen_terbit_jenis_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_kode_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_nomor_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_nomor_key', null::text),
    ('dokumen_terbit', 'dokumen_terbit_penanda_tangan_jabatan_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_penanda_tangan_nama_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_penerbit_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_peserta_id_fkey', null::text),
    ('dokumen_terbit', 'dokumen_terbit_pkey', null::text),
    ('dokumen_terbit', 'dokumen_terbit_token_check', null::text),
    ('dokumen_terbit', 'dokumen_terbit_token_key', null::text),
    ('dokumen_urut', 'dokumen_urut_pkey', null::text),
    ('garuda_berkas_token', 'garuda_berkas_token_dibuat_oleh_fkey', null::text),
    ('garuda_berkas_token', 'garuda_berkas_token_dicabut_oleh_fkey', null::text),
    ('garuda_berkas_token', 'garuda_berkas_token_peserta_id_fkey', null::text),
    ('garuda_berkas_token', 'garuda_berkas_token_pkey', null::text),
    ('garuda_berkas_token', 'garuda_berkas_token_token_check', null::text),
    ('garuda_berkas_token', 'garuda_berkas_token_token_key', null::text),
    ('guru_agama', 'guru_agama_agama_check', null::text),
    ('guru_agama', 'guru_agama_diubah_oleh_fkey', null::text),
    ('guru_agama', 'guru_agama_keterangan_check', null::text),
    ('guru_agama', 'guru_agama_nama_check', null::text),
    ('guru_agama', 'guru_agama_pkey', null::text),
    ('instrumen', 'instrumen_cara_uji_check', null::text),
    ('instrumen', 'instrumen_diubah_oleh_fkey', null::text),
    ('instrumen', 'instrumen_pkey', null::text),
    ('instrumen', 'instrumen_sku_id_fkey', null::text),
    ('instrumen', 'instrumen_status_check', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_bobot_check', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_jenis_check', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_pkey', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_sku_id_fkey', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_sku_id_urutan_key', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_sumber_check', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_teks_check', null::text),
    ('instrumen_kriteria', 'instrumen_kriteria_urutan_check', null::text),
    ('instrumen_panduan', 'instrumen_panduan_kriteria_id_fkey', null::text),
    ('instrumen_panduan', 'instrumen_panduan_panduan_check', null::text),
    ('instrumen_panduan', 'instrumen_panduan_pkey', null::text),
    ('instrumen_penguji', 'instrumen_penguji_instruksi_check', null::text),
    ('instrumen_penguji', 'instrumen_penguji_pkey', null::text),
    ('instrumen_penguji', 'instrumen_penguji_sku_id_fkey', null::text),
    ('iuran', 'iuran_jenis_check', null::text),
    ('iuran', 'iuran_jumlah_check', null::text),
    ('iuran', 'iuran_oleh_fkey', null::text),
    ('iuran', 'iuran_peserta_id_fkey', null::text),
    ('iuran', 'iuran_pkey', null::text),
    ('iuran', 'iuran_tanggal_fkey', null::text),
    ('iuran_kas', 'iuran_kas_catatan_check', null::text),
    ('iuran_kas', 'iuran_kas_oleh_fkey', null::text),
    ('iuran_kas', 'iuran_kas_pkey', null::text),
    ('iuran_kas', 'iuran_kas_tanggal_fkey', null::text),
    ('iuran_kas', 'iuran_kas_total_fisik_check', null::text),
    ('iuran_log', 'iuran_log_oleh_fkey', null::text),
    ('iuran_log', 'iuran_log_peserta_id_fkey', null::text),
    ('iuran_log', 'iuran_log_pkey', null::text),
    ('keepalive_konfigurasi', 'keepalive_konfigurasi_id_check', null::text),
    ('keepalive_konfigurasi', 'keepalive_konfigurasi_kunci_check', null::text),
    ('keepalive_konfigurasi', 'keepalive_konfigurasi_pkey', null::text),
    ('keepalive_konfigurasi', 'keepalive_konfigurasi_url_check', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_agenda_id_fkey', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_catatan_check', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_catatan_tinjauan_check', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_diajukan_oleh_fkey', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_ditinjau_oleh_fkey', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_dokumen_url_check', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_jenis_check', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_pkey', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_status_check', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_tahun_ajaran_check', null::text),
    ('kegiatan_usulan', 'kegiatan_usulan_tolak_wajib_catatan', null::text),
    ('kepengurusan_log', 'kepengurusan_log_alasan_check', null::text),
    ('kepengurusan_log', 'kepengurusan_log_oleh_fkey', null::text),
    ('kepengurusan_log', 'kepengurusan_log_peserta_id_fkey', null::text),
    ('kepengurusan_log', 'kepengurusan_log_pkey', null::text),
    ('kepengurusan_log', 'kepengurusan_log_tindakan_check', null::text),
    ('login_gagal', 'login_gagal_pkey', null::text),
    ('materi', 'materi_bagian_check', null::text),
    ('materi', 'materi_deskripsi_check', null::text),
    ('materi', 'materi_dibuat_oleh_fkey', null::text),
    ('materi', 'materi_file_id_check', null::text),
    ('materi', 'materi_file_id_key', null::text),
    ('materi', 'materi_judul_check', null::text),
    ('materi', 'materi_pkey', null::text),
    ('materi', 'materi_resource_key_check', null::text),
    ('materi', 'materi_tautan_check', null::text),
    ('naik_kelas_batch', 'naik_kelas_batch_dibatalkan_oleh_fkey', null::text),
    ('naik_kelas_batch', 'naik_kelas_batch_oleh_fkey', null::text),
    ('naik_kelas_batch', 'naik_kelas_batch_pkey', null::text),
    ('naik_kelas_batch', 'naik_kelas_batch_tahun_ajaran_check', null::text),
    ('naik_kelas_log', 'naik_kelas_log_aksi_check', null::text),
    ('naik_kelas_log', 'naik_kelas_log_batch_id_fkey', null::text),
    ('naik_kelas_log', 'naik_kelas_log_catatan_check', null::text),
    ('naik_kelas_log', 'naik_kelas_log_dari_status_check', null::text),
    ('naik_kelas_log', 'naik_kelas_log_ke_status_check', null::text),
    ('naik_kelas_log', 'naik_kelas_log_oleh_fkey', null::text),
    ('naik_kelas_log', 'naik_kelas_log_peserta_id_fkey', null::text),
    ('naik_kelas_log', 'naik_kelas_log_pkey', null::text),
    ('notifikasi', 'notifikasi_isi_check', null::text),
    ('notifikasi', 'notifikasi_jenis_check', '''tes'''),
    ('notifikasi', 'notifikasi_judul_check', null::text),
    ('notifikasi', 'notifikasi_kunci_check', null::text),
    ('notifikasi', 'notifikasi_penerima_id_fkey', null::text),
    ('notifikasi', 'notifikasi_pkey', null::text),
    ('notifikasi', 'notifikasi_push_status_check', null::text),
    ('pelantikan', 'pelantikan_agenda_id_fkey', null::text),
    ('pelantikan', 'pelantikan_catatan_check', null::text),
    ('pelantikan', 'pelantikan_dicatat_oleh_fkey', null::text),
    ('pelantikan', 'pelantikan_peserta_id_fkey', null::text),
    ('pelantikan', 'pelantikan_pkey', null::text),
    ('pelantikan', 'pelantikan_satu_per_tingkat', null::text),
    ('pelantikan', 'pelantikan_tanggal_check', null::text),
    ('pelantikan', 'pelantikan_tempat_check', null::text),
    ('pelantikan', 'pelantikan_tingkat_check', null::text),
    ('pengaturan', 'pengaturan_diubah_oleh_fkey', null::text),
    ('pengaturan', 'pengaturan_kunci_check', null::text),
    ('pengaturan', 'pengaturan_pkey', null::text),
    ('pengukuhan_dewan', 'pengukuhan_dewan_catatan_check', null::text),
    ('pengukuhan_dewan', 'pengukuhan_dewan_diubah_oleh_fkey', null::text),
    ('pengukuhan_dewan', 'pengukuhan_dewan_nomor_sk_check', null::text),
    ('pengukuhan_dewan', 'pengukuhan_dewan_pkey', null::text),
    ('pengukuhan_dewan', 'pengukuhan_dewan_rekomendasi_nomor_check', null::text),
    ('pengukuhan_dewan', 'pengukuhan_dewan_tahun_ajaran_check', null::text),
    ('pengukuhan_dewan', 'pengukuhan_rekomendasi_pasangan', null::text),
    ('penugasan_log', 'penugasan_log_catatan_check', null::text),
    ('penugasan_log', 'penugasan_log_oleh_fkey', null::text),
    ('penugasan_log', 'penugasan_log_penguji_id_fkey', null::text),
    ('penugasan_log', 'penugasan_log_peserta_id_fkey', null::text),
    ('penugasan_log', 'penugasan_log_pkey', null::text),
    ('penugasan_log', 'penugasan_log_tindakan_check', null::text),
    ('penugasan_peserta', 'penugasan_peserta_ditetapkan_oleh_fkey', null::text),
    ('penugasan_peserta', 'penugasan_peserta_penguji_id_fkey', null::text),
    ('penugasan_peserta', 'penugasan_peserta_peserta_id_fkey', null::text),
    ('penugasan_peserta', 'penugasan_peserta_pkey', null::text),
    ('penugasan_peserta', 'penugasan_peserta_tahun_ajaran_check', null::text),
    ('penugasan_rombel', 'penugasan_rombel_ditetapkan_oleh_fkey', null::text),
    ('penugasan_rombel', 'penugasan_rombel_penguji_id_fkey', null::text),
    ('penugasan_rombel', 'penugasan_rombel_pkey', null::text),
    ('penugasan_rombel', 'penugasan_rombel_rombel_check', null::text),
    ('penugasan_rombel', 'penugasan_rombel_tahun_ajaran_check', null::text),
    ('pf_item', 'pf_item_pkey', null::text),
    ('portofolio', 'portofolio_catatan_penguji_oleh_fkey', null::text),
    ('portofolio', 'portofolio_item_id_fkey', null::text),
    ('portofolio', 'portofolio_peserta_id_fkey', null::text),
    ('portofolio', 'portofolio_pkey', null::text),
    ('portofolio', 'portofolio_status_check', null::text),
    ('portofolio_jurnal', 'portofolio_jurnal_oleh_fkey', null::text),
    ('portofolio_jurnal', 'portofolio_jurnal_peserta_id_fkey', null::text),
    ('portofolio_jurnal', 'portofolio_jurnal_pkey', null::text),
    ('profiles', 'profil_admin', null::text),
    ('profiles', 'profil_jabatan_dewan', 'peserta'),
    ('profiles', 'profil_nta', null::text),
    ('profiles', 'profil_penguji', null::text),
    ('profiles', 'profil_peserta', null::text),
    ('profiles', 'profil_pinsa', null::text),
    ('profiles', 'profiles_agama_check', null::text),
    ('profiles', 'profiles_id_fkey', null::text),
    ('profiles', 'profiles_jabatan_check', null::text),
    ('profiles', 'profiles_jabatan_dewan_check', 'char_length'),
    ('profiles', 'profiles_jenis_kelamin_check', null::text),
    ('profiles', 'profiles_lulus_ta_check', null::text),
    ('profiles', 'profiles_nama_check', null::text),
    ('profiles', 'profiles_nis_key', null::text),
    ('profiles', 'profiles_pin_direset_oleh_fkey', null::text),
    ('profiles', 'profiles_pkey', null::text),
    ('profiles', 'profiles_role_check', null::text),
    ('profiles', 'profiles_status_check', null::text),
    ('profiles', 'profiles_username_check', null::text),
    ('profiles', 'profiles_username_key', null::text),
    ('profiles', 'profiles_whatsapp_check', null::text),
    ('push_konfigurasi', 'push_konfigurasi_id_check', null::text),
    ('push_konfigurasi', 'push_konfigurasi_kunci_publik_check', null::text),
    ('push_konfigurasi', 'push_konfigurasi_pkey', null::text),
    ('push_konfigurasi', 'push_konfigurasi_rahasia_check', null::text),
    ('push_konfigurasi', 'push_konfigurasi_url_check', null::text),
    ('push_langganan', 'push_langganan_agen_check', null::text),
    ('push_langganan', 'push_langganan_auth_check', null::text),
    ('push_langganan', 'push_langganan_endpoint_check', null::text),
    ('push_langganan', 'push_langganan_endpoint_key', null::text),
    ('push_langganan', 'push_langganan_p256dh_check', null::text),
    ('push_langganan', 'push_langganan_penerima_id_fkey', null::text),
    ('push_langganan', 'push_langganan_pkey', null::text),
    ('raport', 'raport_capaian_lulus_check', null::text),
    ('raport', 'raport_capaian_target_check', null::text),
    ('raport', 'raport_catatan_predikat_check', null::text),
    ('raport', 'raport_deskripsi_check', null::text),
    ('raport', 'raport_diubah_oleh_fkey', null::text),
    ('raport', 'raport_final', null::text),
    ('raport', 'raport_hadir_check', null::text),
    ('raport', 'raport_karakter_check', null::text),
    ('raport', 'raport_kehadiran_persen_check', null::text),
    ('raport', 'raport_pertemuan_check', null::text),
    ('raport', 'raport_peserta_id_fkey', null::text),
    ('raport', 'raport_pkey', null::text),
    ('raport', 'raport_predikat_akhir_check', null::text),
    ('raport', 'raport_predikat_hitung_check', null::text),
    ('raport', 'raport_semester_check', null::text),
    ('raport', 'raport_sikap_check', null::text),
    ('raport', 'raport_skk_check', null::text),
    ('raport', 'raport_skor_check', null::text),
    ('raport', 'raport_status_check', null::text),
    ('raport', 'raport_tahun_ajaran_check', null::text),
    ('raport', 'raport_tingkat_check', null::text),
    ('saka_anggota', 'saka_anggota_catatan_check', null::text),
    ('saka_anggota', 'saka_anggota_dicatat_oleh_fkey', null::text),
    ('saka_anggota', 'saka_anggota_peserta_id_fkey', null::text),
    ('saka_anggota', 'saka_anggota_pkey', null::text),
    ('saka_anggota', 'saka_anggota_saka_check', null::text),
    ('saka_anggota', 'saka_anggota_status_check', null::text),
    ('saka_anggota', 'saka_anggota_surat_url_check', null::text),
    ('saka_anggota', 'saka_anggota_tanggal_masuk_check', null::text),
    ('saka_anggota', 'saka_selesai_konsisten', null::text),
    ('sertifikat_tingkat', 'sertifikat_tingkat_diterbitkan_oleh_fkey', null::text),
    ('sertifikat_tingkat', 'sertifikat_tingkat_peserta_id_fkey', null::text),
    ('sertifikat_tingkat', 'sertifikat_tingkat_peserta_id_tingkat_key', null::text),
    ('sertifikat_tingkat', 'sertifikat_tingkat_pkey', null::text),
    ('sertifikat_tingkat', 'sertifikat_tingkat_tingkat_check', null::text),
    ('sertifikat_tingkat', 'sertifikat_tingkat_token_check', null::text),
    ('sesi_ujian', 'sesi_ujian_catatan_check', null::text),
    ('sesi_ujian', 'sesi_ujian_dibuat_oleh_fkey', null::text),
    ('sesi_ujian', 'sesi_ujian_nama_check', null::text),
    ('sesi_ujian', 'sesi_ujian_pkey', null::text),
    ('sesi_ujian', 'sesi_ujian_status_check', null::text),
    ('sesi_ujian', 'sesi_ujian_tanggal_check', null::text),
    ('sesi_ujian', 'sesi_ujian_tempat_check', null::text),
    ('sesi_ujian_butir', 'sesi_ujian_butir_butir_id_fkey', null::text),
    ('sesi_ujian_butir', 'sesi_ujian_butir_pkey', null::text),
    ('sesi_ujian_butir', 'sesi_ujian_butir_sesi_id_fkey', null::text),
    ('sesi_ujian_peserta', 'sesi_ujian_peserta_peserta_id_fkey', null::text),
    ('sesi_ujian_peserta', 'sesi_ujian_peserta_pkey', null::text),
    ('sesi_ujian_peserta', 'sesi_ujian_peserta_sesi_id_fkey', null::text),
    ('sidang_dk', 'sidang_dk_catatan_check', null::text),
    ('sidang_dk', 'sidang_dk_dibuat_oleh_fkey', null::text),
    ('sidang_dk', 'sidang_dk_keputusan_check', null::text),
    ('sidang_dk', 'sidang_dk_kode_check', null::text),
    ('sidang_dk', 'sidang_dk_magang_check', null::text),
    ('sidang_dk', 'sidang_dk_nomor_ba_check', null::text),
    ('sidang_dk', 'sidang_dk_nta_check', null::text),
    ('sidang_dk', 'sidang_dk_peserta_id_fkey', null::text),
    ('sidang_dk', 'sidang_dk_pkey', null::text),
    ('sidang_dk', 'sidang_dk_tingkat_check', null::text),
    ('sidang_dk', 'sidang_dk_token_check', null::text),
    ('sidang_dk', 'sidang_dk_token_key', null::text),
    ('sidang_dk', 'sidang_dk_tugas_adat_check', null::text),
    ('sidang_dk', 'sidang_dk_tugas_adat_ket_check', null::text),
    ('sidang_urut', 'sidang_urut_pkey', null::text),
    ('sku_butir', 'sku_butir_pkey', null::text),
    ('sku_butir', 'sku_butir_tingkat_check', null::text),
    ('sku_penilaian', 'sku_penilaian_hasil_check', null::text),
    ('sku_penilaian', 'sku_penilaian_penguji_id_fkey', null::text),
    ('sku_penilaian', 'sku_penilaian_peserta_id_fkey', null::text),
    ('sku_penilaian', 'sku_penilaian_pkey', null::text),
    ('sku_penilaian', 'sku_penilaian_saran_check', null::text),
    ('sku_penilaian', 'sku_penilaian_skor_check', null::text),
    ('sku_penilaian', 'sku_penilaian_sku_id_fkey', null::text),
    ('sku_pra_uji', 'sku_pra_uji_belum_catatan', null::text),
    ('sku_pra_uji', 'sku_pra_uji_catatan_check', null::text),
    ('sku_pra_uji', 'sku_pra_uji_catatan_peserta_check', null::text),
    ('sku_pra_uji', 'sku_pra_uji_penilai_id_fkey', null::text),
    ('sku_pra_uji', 'sku_pra_uji_peserta_id_fkey', null::text),
    ('sku_pra_uji', 'sku_pra_uji_pkey', null::text),
    ('sku_pra_uji', 'sku_pra_uji_sku_id_fkey', null::text),
    ('sku_pra_uji', 'sku_pra_uji_status_check', null::text),
    ('sku_pra_uji', 'sku_pra_uji_tahap_check', null::text),
    ('sku_progress', 'sku_progress_nilai_check', null::text),
    ('sku_progress', 'sku_progress_penguji_id_fkey', null::text),
    ('sku_progress', 'sku_progress_peserta_id_fkey', null::text),
    ('sku_progress', 'sku_progress_pkey', null::text),
    ('sku_progress', 'sku_progress_sku_id_fkey', null::text),
    ('sku_progress', 'sku_progress_status_check', null::text),
    ('sku_progress', 'sku_progress_verifikasi_token_check', null::text),
    ('sku_riwayat', 'sku_riwayat_oleh_fkey', null::text),
    ('sku_riwayat', 'sku_riwayat_peserta_id_fkey', null::text),
    ('sku_riwayat', 'sku_riwayat_pkey', null::text),
    ('sku_unit', 'sku_unit_butir_id_fkey', null::text),
    ('sku_unit', 'sku_unit_pkey', null::text),
    ('tkk_capaian', 'tkk_capaian_bukti_url_check', null::text),
    ('tkk_capaian', 'tkk_capaian_catatan_check', null::text),
    ('tkk_capaian', 'tkk_capaian_dicatat_oleh_fkey', null::text),
    ('tkk_capaian', 'tkk_capaian_melatih_check', null::text),
    ('tkk_capaian', 'tkk_capaian_penguji1_check', null::text),
    ('tkk_capaian', 'tkk_capaian_penguji2_check', null::text),
    ('tkk_capaian', 'tkk_capaian_peserta_id_fkey', null::text),
    ('tkk_capaian', 'tkk_capaian_pkey', null::text),
    ('tkk_capaian', 'tkk_capaian_satu_per_tingkat', null::text),
    ('tkk_capaian', 'tkk_capaian_tanggal_check', null::text),
    ('tkk_capaian', 'tkk_capaian_tingkat_check', null::text),
    ('tkk_capaian', 'tkk_capaian_tkk_id_fkey', null::text),
    ('tkk_katalog', 'tkk_katalog_agama_check', null::text),
    ('tkk_katalog', 'tkk_katalog_bidang_check', null::text),
    ('tkk_katalog', 'tkk_katalog_golongan_check', null::text),
    ('tkk_katalog', 'tkk_katalog_id_check', null::text),
    ('tkk_katalog', 'tkk_katalog_nama_check', null::text),
    ('tkk_katalog', 'tkk_katalog_pkey', null::text),
    ('tkk_katalog', 'tkk_katalog_sumber_check', null::text),
    ('tkk_krida', 'tkk_krida_bukti_url_check', null::text),
    ('tkk_krida', 'tkk_krida_catatan_check', null::text),
    ('tkk_krida', 'tkk_krida_dicatat_oleh_fkey', null::text),
    ('tkk_krida', 'tkk_krida_nama_check', null::text),
    ('tkk_krida', 'tkk_krida_peserta_id_fkey', null::text),
    ('tkk_krida', 'tkk_krida_pkey', null::text),
    ('tkk_krida', 'tkk_krida_saka_check', null::text),
    ('tkk_krida', 'tkk_krida_tanggal_check', null::text)
),
h_indeks(tabel, nama) as (values
    ('absensi_hadir', 'absensi_hadir_oleh_idx'),
    ('absensi_hadir', 'absensi_hadir_peserta_id_idx'),
    ('absensi_hadir', 'absensi_hadir_pkey'),
    ('absensi_sesi', 'absensi_sesi_pkey'),
    ('agenda', 'agenda_pkey'),
    ('agenda', 'agenda_tahun_ajaran_idx'),
    ('agenda', 'agenda_tanggal_idx'),
    ('asisten_iuran', 'asisten_iuran_pkey'),
    ('bina_damping', 'bina_damping_penegak_idx'),
    ('bina_damping', 'bina_damping_pkey'),
    ('bina_damping', 'bina_damping_satu_rombel_idx'),
    ('dokumen_terbit', 'dokumen_terbit_kode_idx'),
    ('dokumen_terbit', 'dokumen_terbit_nomor_key'),
    ('dokumen_terbit', 'dokumen_terbit_peserta_idx'),
    ('dokumen_terbit', 'dokumen_terbit_pkey'),
    ('dokumen_terbit', 'dokumen_terbit_token_key'),
    ('dokumen_urut', 'dokumen_urut_pkey'),
    ('garuda_berkas_token', 'garuda_berkas_token_aktif_unik'),
    ('garuda_berkas_token', 'garuda_berkas_token_peserta_idx'),
    ('garuda_berkas_token', 'garuda_berkas_token_pkey'),
    ('garuda_berkas_token', 'garuda_berkas_token_token_key'),
    ('guru_agama', 'guru_agama_pkey'),
    ('guru_agama', 'guru_agama_unik'),
    ('instrumen', 'instrumen_pkey'),
    ('instrumen_kriteria', 'instrumen_kriteria_pkey'),
    ('instrumen_kriteria', 'instrumen_kriteria_sku_id_idx'),
    ('instrumen_kriteria', 'instrumen_kriteria_sku_id_urutan_key'),
    ('instrumen_panduan', 'instrumen_panduan_pkey'),
    ('instrumen_penguji', 'instrumen_penguji_pkey'),
    ('iuran', 'iuran_oleh_idx'),
    ('iuran', 'iuran_peserta_id_idx'),
    ('iuran', 'iuran_pkey'),
    ('iuran_kas', 'iuran_kas_pkey'),
    ('iuran_log', 'iuran_log_oleh_idx'),
    ('iuran_log', 'iuran_log_peserta_idx'),
    ('iuran_log', 'iuran_log_pkey'),
    ('iuran_log', 'iuran_log_tanggal_idx'),
    ('keepalive_konfigurasi', 'keepalive_konfigurasi_pkey'),
    ('kegiatan_usulan', 'kegiatan_usulan_menunggu_unik'),
    ('kegiatan_usulan', 'kegiatan_usulan_pkey'),
    ('kegiatan_usulan', 'kegiatan_usulan_tahun_ajaran_idx'),
    ('kepengurusan_log', 'kepengurusan_log_pkey'),
    ('kepengurusan_log', 'kepengurusan_log_waktu_idx'),
    ('login_gagal', 'login_gagal_pkey'),
    ('materi', 'materi_file_id_key'),
    ('materi', 'materi_pkey'),
    ('naik_kelas_batch', 'naik_kelas_batch_pkey'),
    ('naik_kelas_log', 'naik_kelas_log_batch_idx'),
    ('naik_kelas_log', 'naik_kelas_log_oleh_idx'),
    ('naik_kelas_log', 'naik_kelas_log_peserta_idx'),
    ('naik_kelas_log', 'naik_kelas_log_pkey'),
    ('notifikasi', 'notifikasi_kunci_unik'),
    ('notifikasi', 'notifikasi_penerima_idx'),
    ('notifikasi', 'notifikasi_pkey'),
    ('pelantikan', 'pelantikan_agenda_idx'),
    ('pelantikan', 'pelantikan_pkey'),
    ('pelantikan', 'pelantikan_satu_per_tingkat'),
    ('pelantikan', 'pelantikan_tanggal_idx'),
    ('pengaturan', 'pengaturan_pkey'),
    ('pengukuhan_dewan', 'pengukuhan_dewan_pkey'),
    ('penugasan_log', 'penugasan_log_pkey'),
    ('penugasan_log', 'penugasan_log_ta_idx'),
    ('penugasan_peserta', 'penugasan_peserta_penguji_idx'),
    ('penugasan_peserta', 'penugasan_peserta_pkey'),
    ('penugasan_rombel', 'penugasan_rombel_penguji_idx'),
    ('penugasan_rombel', 'penugasan_rombel_pkey'),
    ('pf_item', 'pf_item_pkey'),
    ('portofolio', 'portofolio_catatan_oleh_idx'),
    ('portofolio', 'portofolio_pkey'),
    ('portofolio_jurnal', 'portofolio_jurnal_oleh_idx'),
    ('portofolio_jurnal', 'portofolio_jurnal_peserta_id_idx'),
    ('portofolio_jurnal', 'portofolio_jurnal_pkey'),
    ('profiles', 'profil_pinsa_unik'),
    ('profiles', 'profil_pradana_pradani_unik'),
    ('profiles', 'profiles_nis_key'),
    ('profiles', 'profiles_pkey'),
    ('profiles', 'profiles_username_key'),
    ('push_konfigurasi', 'push_konfigurasi_pkey'),
    ('push_langganan', 'push_langganan_endpoint_key'),
    ('push_langganan', 'push_langganan_penerima_idx'),
    ('push_langganan', 'push_langganan_pkey'),
    ('raport', 'raport_pkey'),
    ('raport', 'raport_tahun_ajaran_semester_idx'),
    ('saka_anggota', 'saka_anggota_pkey'),
    ('saka_anggota', 'saka_peserta_unik'),
    ('sertifikat_tingkat', 'sertifikat_tingkat_peserta_id_tingkat_key'),
    ('sertifikat_tingkat', 'sertifikat_tingkat_pkey'),
    ('sesi_ujian', 'sesi_ujian_pkey'),
    ('sesi_ujian', 'sesi_ujian_tanggal_idx'),
    ('sesi_ujian_butir', 'sesi_ujian_butir_pkey'),
    ('sesi_ujian_peserta', 'sesi_ujian_peserta_peserta_id_idx'),
    ('sesi_ujian_peserta', 'sesi_ujian_peserta_pkey'),
    ('sidang_dk', 'sidang_dk_kode_idx'),
    ('sidang_dk', 'sidang_dk_layak'),
    ('sidang_dk', 'sidang_dk_nomor'),
    ('sidang_dk', 'sidang_dk_peserta_id_idx'),
    ('sidang_dk', 'sidang_dk_pkey'),
    ('sidang_dk', 'sidang_dk_tanggal_idx'),
    ('sidang_dk', 'sidang_dk_token_key'),
    ('sidang_urut', 'sidang_urut_pkey'),
    ('sku_butir', 'sku_butir_pkey'),
    ('sku_penilaian', 'sku_penilaian_penguji_idx'),
    ('sku_penilaian', 'sku_penilaian_peserta_id_sku_id_idx'),
    ('sku_penilaian', 'sku_penilaian_pkey'),
    ('sku_pra_uji', 'sku_pra_uji_menunggu_unik'),
    ('sku_pra_uji', 'sku_pra_uji_penilai_idx'),
    ('sku_pra_uji', 'sku_pra_uji_peserta_idx'),
    ('sku_pra_uji', 'sku_pra_uji_pkey'),
    ('sku_pra_uji', 'sku_pra_uji_sku_idx'),
    ('sku_progress', 'sku_progress_penguji_idx'),
    ('sku_progress', 'sku_progress_pkey'),
    ('sku_progress', 'sku_progress_verifikasi_idx'),
    ('sku_progress', 'sku_progress_verifikasi_token_idx'),
    ('sku_riwayat', 'sku_riwayat_oleh_idx'),
    ('sku_riwayat', 'sku_riwayat_peserta_id_idx'),
    ('sku_riwayat', 'sku_riwayat_pkey'),
    ('sku_unit', 'sku_unit_pkey'),
    ('tkk_capaian', 'tkk_capaian_pkey'),
    ('tkk_capaian', 'tkk_capaian_satu_per_tingkat'),
    ('tkk_capaian', 'tkk_capaian_tkk_idx'),
    ('tkk_katalog', 'tkk_katalog_pkey'),
    ('tkk_krida', 'tkk_krida_pkey'),
    ('tkk_krida', 'tkk_krida_unik')
),
h_kebijakan(tabel, nama, potongan) as (values
    ('absensi_hadir', 'baca_absensi', null::text),
    ('absensi_sesi', 'baca_sesi', null::text),
    ('agenda', 'baca_agenda', null::text),
    ('asisten_iuran', 'baca_asisten_iuran', null::text),
    ('dokumen_terbit', 'baca_dokumen', null::text),
    ('dokumen_urut', 'baca_dokumen_urut', null::text),
    ('guru_agama', 'baca_guru_agama', null::text),
    ('instrumen', 'baca_instrumen', null::text),
    ('instrumen_kriteria', 'baca_instrumen_kriteria', null::text),
    ('instrumen_panduan', 'baca_instrumen_panduan', null::text),
    ('instrumen_penguji', 'baca_instrumen_penguji', null::text),
    ('iuran', 'baca_iuran', null::text),
    ('iuran_kas', 'baca_iuran_kas', null::text),
    ('iuran_log', 'baca_iuran_log', null::text),
    ('kegiatan_usulan', 'baca_kegiatan_usulan', null::text),
    ('kepengurusan_log', 'baca_kepengurusan_log', null::text),
    ('materi', 'baca_materi', null::text),
    ('naik_kelas_batch', 'baca_naik_kelas_batch', null::text),
    ('naik_kelas_log', 'baca_naik_kelas_log', null::text),
    ('notifikasi', 'baca_notifikasi', null::text),
    ('pelantikan', 'baca_pelantikan', null::text),
    ('pengaturan', 'baca_pengaturan', null::text),
    ('pengukuhan_dewan', 'baca_pengukuhan_dewan', null::text),
    ('penugasan_log', 'baca_penugasan_log', null::text),
    ('penugasan_peserta', 'baca_penugasan_peserta', null::text),
    ('penugasan_rombel', 'baca_penugasan', null::text),
    ('pf_item', 'baca_katalog_pf', null::text),
    ('portofolio', 'baca_portofolio', null::text),
    ('portofolio_jurnal', 'baca_jurnal', null::text),
    ('profiles', 'baca_profil', 'jabatan_dewan'),
    ('raport', 'baca_raport', null::text),
    ('saka_anggota', 'baca_saka_anggota', null::text),
    ('sesi_ujian', 'baca_sesi_ujian', null::text),
    ('sesi_ujian_butir', 'baca_sesi_ujian_butir', null::text),
    ('sesi_ujian_peserta', 'baca_sesi_ujian_peserta', null::text),
    ('sidang_dk', 'baca_sidang', null::text),
    ('sidang_urut', 'baca_sidang_urut', null::text),
    ('sku_butir', 'baca_katalog_butir', null::text),
    ('sku_penilaian', 'baca_penilaian', null::text),
    ('sku_pra_uji', 'baca_pra_uji', null::text),
    ('sku_progress', 'baca_progres', null::text),
    ('sku_riwayat', 'baca_riwayat', null::text),
    ('sku_unit', 'baca_katalog_unit', null::text),
    ('tkk_capaian', 'baca_tkk_capaian', null::text),
    ('tkk_katalog', 'baca_tkk_katalog', null::text),
    ('tkk_krida', 'baca_tkk_krida', null::text)
),
h_pemicu(tabel, nama) as (values
    ('absensi_hadir', 'tak_aktif_absensi_hadir'),
    ('asisten_iuran', 'tak_aktif_asisten_iuran'),
    ('dokumen_terbit', 'notif_dokumen'),
    ('iuran', 'tak_aktif_iuran'),
    ('iuran_log', 'tak_aktif_iuran_log'),
    ('notifikasi', 'notifikasi_push'),
    ('pelantikan', 'tak_aktif_pelantikan'),
    ('portofolio', 'tak_aktif_portofolio'),
    ('portofolio_jurnal', 'tak_aktif_portofolio_jurnal'),
    ('profiles', 'profiles_bina_damping_bersih'),
    ('profiles', 'profiles_pinsa_bersih'),
    ('profiles', 'tak_aktif_calon_garuda'),
    ('raport', 'tak_aktif_raport'),
    ('saka_anggota', 'tak_aktif_saka_anggota'),
    ('sesi_ujian_peserta', 'notif_sesi_peserta'),
    ('sesi_ujian_peserta', 'tak_aktif_sesi_peserta'),
    ('sku_penilaian', 'tak_aktif_sku_penilaian'),
    ('sku_pra_uji', 'notif_pra_uji'),
    ('sku_pra_uji', 'tak_aktif_sku_pra_uji'),
    ('sku_progress', 'notif_sku_progress'),
    ('sku_progress', 'tak_aktif_sku_progress'),
    ('sku_riwayat', 'tak_aktif_sku_riwayat'),
    ('tkk_capaian', 'tak_aktif_tkk_capaian'),
    ('tkk_krida', 'tak_aktif_tkk_krida')
),
h_fungsi(skema, nama, args, isi, au, an, sv) as (values
    ('public', 'sg_absen_buat_sesi', 'p_tanggal date', '692dd6864ff620207afac56ec70686d4', true, false, true),
    ('public', 'sg_absen_hapus_sesi', 'p_tanggal date', '80ec8f59b7aca96972748386b79bbb3a', true, false, true),
    ('public', 'sg_absen_set', 'p_tanggal date, p_peserta_id uuid, p_status text', '6d2fcefc401923074a34f91680043388', true, false, true),
    ('public', 'sg_absen_set_banyak', 'p_tanggal date, p_peserta_ids uuid[], p_status text, p_hanya_kosong boolean', 'daff9f5cc920cc6dc04fc033b3f9c24a', true, false, true),
    ('public', 'sg_agenda_hapus', 'p_id bigint', '660766b642565ad1fd9082cbcb3b4885', true, false, true),
    ('public', 'sg_agenda_simpan', 'p_id bigint, p_tahun_ajaran text, p_jenis text, p_judul text, p_tanggal date, p_keterangan text, p_peserta_terkait uuid[], p_lewati_batas boolean', '0cc4d6baf9be40f6602b743ab2d96a0f', true, false, true),
    ('public', 'sg_anggota_agama_atur', 'p_data jsonb', 'eaea93670bc4c9dee6ccaf2744f76bca', true, false, true),
    ('public', 'sg_anggota_jabatan_dewan_atur', 'p_data jsonb', 'dc598310f85e14eb04c8a698a1def9bd', true, false, true),
    ('public', 'sg_anggota_jk_atur', 'p_data jsonb', '075d5ed7bde1d3e71f7b7bd11c63e1be', true, false, true),
    ('public', 'sg_anggota_nta_atur', 'p_data jsonb', '6a7d7ee81a442c300cf95ee855dc4abd', true, false, true),
    ('public', 'sg_anggota_status_atur', 'p_id uuid, p_status text, p_rombel text, p_catatan text', 'c9b8f867097edccf79fee18d7b0fd3b3', true, false, true),
    ('public', 'sg_anggota_ubah', 'p_id uuid, p_nama text, p_kelas text, p_sangga text, p_agama text, p_calon_garuda boolean', '2ff1375aabc28fa36796d94247d22251', true, false, true),
    ('public', 'sg_asisten_iuran_atur', 'p_peserta_id uuid, p_aktif boolean', 'b1d2078fe7e40b647c437c8506b692a2', true, false, true),
    ('public', 'sg_bina_damping_atur', 'p_tahun_ajaran text, p_rombel text, p_penegak_ids uuid[]', '9fcf9b1d2bfb6a30f93d473d025b6362', true, false, true),
    ('public', 'sg_bina_damping_daftar', 'p_tahun_ajaran text', '6192bec6d1045e09354c74b1b55e56ea', true, false, true),
    ('public', 'sg_cadangan_admin', '', '8b1367705657de1813f8b53b6a5f3960', true, false, true),
    ('public', 'sg_cadangan_status', '', 'e34e4d8aa7c91e88de94cae963be5e12', true, false, true),
    ('public', 'sg_calon_garuda_daftar', '', '822a69512deba1421e075ec8851b3c69', true, false, true),
    ('public', 'sg_dewan_lama_arsipkan', 'p_ids uuid[], p_aktifkan boolean', 'efe4c91e1283dfd3cae39618ec01f0e1', true, false, true),
    ('public', 'sg_dokumen_cabut', 'p_id bigint, p_alasan text', '2472b484bbf68b53f7f9707f224f661d', true, false, true),
    ('public', 'sg_dokumen_surat_agama_terbit', 'p_peserta_id uuid, p_butir text[], p_guru_id bigint, p_guru_nama text, p_tanggal date, p_penerbit text, p_penanda_nama text, p_penanda_jabatan text, p_nomor_manual text, p_catatan text', '00a5345c00840968d0a829d8214f610f', true, false, true),
    ('public', 'sg_eskalasi_daftar', '', 'ca6bbf4a7560752377ac611d5277a9a2', true, false, true),
    ('public', 'sg_garuda_berkas_baca', 'p_peserta_id uuid', 'f1e6492621b059a7a470af5cd7222445', true, false, true),
    ('public', 'sg_garuda_token_baca', 'p_token text', 'ea1b53f2c778a808a3c69e6693516a45', true, true, true),
    ('public', 'sg_garuda_token_buat', 'p_peserta_id uuid', '3ae57637a983728992b71619025cb28d', true, false, true),
    ('public', 'sg_garuda_token_cabut', 'p_peserta_id uuid', '14a8657e316ffd60449be0de859d4ff1', true, false, true),
    ('public', 'sg_gudep_publik', '', 'd4d51e667d985fabf4786926ba04ef12', true, true, true),
    ('public', 'sg_gudep_simpan', 'p_nilai jsonb', 'ce7a1a6a3ab3ceb2da486db4f46abf2b', true, false, true),
    ('public', 'sg_guru_agama_hapus', 'p_id bigint', 'b8f2514c4d3356965bb5326386190290', true, false, true),
    ('public', 'sg_guru_agama_simpan', 'p_id bigint, p_agama text, p_nama text, p_keterangan text', 'e9047b883348e1e0f2c5ae9a78fa4d5f', true, false, true),
    ('public', 'sg_instrumen_pengaturan_simpan', 'p_nilai jsonb', 'd11b90ff0a7a9888d9094f2e5f8fd90f', true, false, true),
    ('public', 'sg_instrumen_simpan', 'p_sku_id text, p_cara_uji text, p_instruksi text, p_kriteria jsonb, p_status text', '714dde95449fd83eeff21231650ee00f', true, false, true),
    ('public', 'sg_instrumen_status', 'p_sku_ids text[], p_status text', 'feb244cffa9ae517cfd4689857b0f88e', true, false, true),
    ('public', 'sg_iuran_agregat', 'p_mulai date, p_akhir date', 'ed72c3d12ee018218d750d920837ba77', true, false, true),
    ('public', 'sg_iuran_kas_simpan', 'p_tanggal date, p_total integer, p_catatan text', '314490b31cf4ff0d74eaccc6765e6476', true, false, true),
    ('public', 'sg_iuran_lembar', 'p_tanggal date', 'cccc4ac2e8e284d57d7b137ceb2e505f', true, false, true),
    ('public', 'sg_iuran_pengaturan', '', '6806a13fd6e9bdee72e9b3852faf60c9', true, false, true),
    ('public', 'sg_iuran_pengaturan_simpan', 'p_nilai jsonb', '2e22b71ba3f54ae4966cd1cda23993f8', true, false, true),
    ('public', 'sg_iuran_ringkas', 'p_peserta_id uuid, p_tanggal date', '507724f4531ea89266bae03239ee546f', true, false, true),
    ('public', 'sg_iuran_set', 'p_tanggal date, p_peserta_id uuid, p_jumlah integer', '6a309736dde75be16a2cc0be2e867dc7', true, false, true),
    ('public', 'sg_iuran_set_banyak', 'p_tanggal date, p_peserta_ids uuid[], p_jumlah integer, p_hanya_kosong boolean', 'b2b49247410fe082652dab4324bba6ff', true, false, true),
    ('public', 'sg_iuran_susulan', 'p_peserta_id uuid, p_tanggal date, p_jumlah integer, p_pertemuan integer', '2128edb0df3313a5a2a72949c8a0a46e', true, false, true),
    ('public', 'sg_kegiatan_ping', 'p_id bigint', '0ddd8b5d58334eea4c19a7084633d366', true, false, true),
    ('public', 'sg_kegiatan_tinjau', 'p_id bigint, p_keputusan text, p_catatan text', '57c18aab7b31807e5f2531a3b3428e08', true, false, true),
    ('public', 'sg_kegiatan_usul', 'p_jenis text, p_tahun_ajaran text, p_tanggal_usul date, p_dokumen_url text, p_catatan text', '3ec98779d32e2170737c87f99b998646', true, false, true),
    ('public', 'sg_kepengurusan_terapkan', 'p_data jsonb, p_ganti boolean, p_terapkan boolean', 'ebd1a888b2608fe6976af66a49241b74', true, false, true),
    ('public', 'sg_kunci_cek_internal', 'p_username text', 'e77a8cb5230dabc09f41e31fb5c08328', false, false, true),
    ('public', 'sg_kunci_gagal_internal', 'p_username text', '76807010d063dd09cae2433d7a4ce101', false, false, true),
    ('public', 'sg_kunci_lepas_internal', 'p_username text', '673fd639183d48b79804ca5d0f37360e', false, false, true),
    ('public', 'sg_materi_geser', 'p_id uuid, p_arah integer', 'fc17d272c5015ee19a7ab2607604973a', true, false, true),
    ('public', 'sg_materi_hapus', 'p_id uuid', '8e7283663719bbc9e1671657101d9fc8', true, false, true),
    ('public', 'sg_materi_simpan', 'p_id uuid, p_judul text, p_deskripsi text, p_tautan text, p_file_id text, p_resource_key text, p_butir text[], p_bagian jsonb', '58134aed5484fc20f98fb8ffd69af81a', true, false, true),
    ('public', 'sg_naik_kelas', 'p_tahun_ajaran text, p_data jsonb, p_terapkan boolean', 'edd8f68b65ebbf13e31cb7de1018422f', true, false, true),
    ('public', 'sg_naik_kelas_batalkan', 'p_batch bigint', 'dfb062d886126d7262dd450afd780a7e', true, false, true),
    ('public', 'sg_notifikasi_tandai', 'p_ids bigint[]', 'aebf3598eee6126fb4287e021c928d45', true, false, true),
    ('public', 'sg_notifikasi_tes', '', '9cf97c96da7bb16825c10586d54befb5', true, false, true),
    ('public', 'sg_pelantikan_catat', 'p_tingkat text, p_tanggal date, p_tempat text, p_peserta_ids uuid[], p_agenda_id bigint, p_catatan text', 'b4f1d03d9acc789ab01597533f668e07', true, false, true),
    ('public', 'sg_pelantikan_hapus', 'p_id bigint', 'bdff44fa55d3ffefc36ca96530fc1fbb', true, false, true),
    ('public', 'sg_pemeriksaan_data', '', '9b7a6202eb8ad53940f325781ec1b7f1', true, false, true),
    ('public', 'sg_pendampingan_saya', '', '3f87bc66b0b53a6ff237e2ffcdbf1d8b', true, false, true),
    ('public', 'sg_pengaturan_simpan', 'p_kunci text, p_nilai jsonb', '86557f0c05a5fc4383ee782d2dc98730', true, false, true),
    ('public', 'sg_penguji_pilihan', 'p_sku_id text, p_peserta_id uuid', '29f88a695abd9c37b6c072d92ea79c15', true, false, true),
    ('public', 'sg_pengukuhan_dewan_hapus', 'p_tahun_ajaran text', 'a0cbfbc3fcc34a31219e1ba0175cbf90', true, false, true),
    ('public', 'sg_pengukuhan_dewan_simpan', 'p_tahun_ajaran text, p_nomor_sk text, p_tanggal_sk date, p_rekomendasi_nomor text, p_rekomendasi_tanggal date, p_catatan text', '3a6af06129df03f3666cbaa895d156ab', true, false, true),
    ('public', 'sg_penugasan_atur', 'p_tahun_ajaran text, p_penguji_id uuid, p_rombel text[], p_ada boolean', '6194df3da1fd50f58f45e8b8d3c884a5', true, false, true),
    ('public', 'sg_penugasan_peserta_atur', 'p_tahun_ajaran text, p_peserta_id uuid, p_penguji_ids uuid[], p_alasan text', '165c4098efd1ce6e46baccc00688909f', true, false, true),
    ('public', 'sg_penugasan_salin', 'p_dari text, p_ke text', '2087dc2732261e4f57ede372c8714f5f', true, false, true),
    ('public', 'sg_pf_catat_penguji', 'p_peserta_id uuid, p_item_id text, p_catatan text', '9e19fd9bfe0b75340d41664044714d7b', true, false, true),
    ('public', 'sg_pf_ubah', 'p_item_id text, p_status text, p_catatan text, p_tautan text', '2d0086521c8db8f32f7239edada8cdc9', true, false, true),
    ('public', 'sg_pra_uji_antrian', '', '2e28adbfee25f43052a58e843713f151', true, false, true),
    ('public', 'sg_pra_uji_catat', 'p_id bigint, p_hasil text, p_catatan text', '9d82bc1555f9d07bf00053e38356ea36', true, false, true),
    ('public', 'sg_pra_uji_lewati', 'p_id bigint, p_alasan text', 'e343c55bb7681f65576d946ed546437a', true, false, true),
    ('public', 'sg_pra_uji_sakelar', 'p_aktif boolean', '305dd698c326024c572f6c61810ce6f0', true, false, true),
    ('public', 'sg_profil_buat_internal', 'p_id uuid, p_username text, p_role text, p_nama text, p_nis text, p_kelas text, p_sangga text, p_agama text, p_jabatan text', 'f795b13bf8792f423bf5beee64502596', false, false, true),
    ('public', 'sg_profil_whatsapp_atur', 'p_whatsapp text', '75b1addd624c2cfdc6b413fc1047772f', true, false, true),
    ('public', 'sg_push_ambil_internal', 'p_ids bigint[]', '517768adc0f63fbfd33c931cba2f67bd', false, false, true),
    ('public', 'sg_push_hapus', 'p_endpoint text', '3bfc56f2dd0b08bfd80aa2d441a70005', true, false, true),
    ('public', 'sg_push_hasil_internal', 'p_hasil jsonb', '54be5034174b03ff852fa7d972ca8107', false, false, true),
    ('public', 'sg_push_kunci', '', 'd95319eaf912a5f6e63bea8d818eca5b', true, false, true),
    ('public', 'sg_push_ringkasan', '', '255e5afb2dbe7b8e37936cb178db0d76', true, false, true),
    ('public', 'sg_push_simpan', 'p_endpoint text, p_p256dh text, p_auth text, p_agen text', '17866fe2bd3c1befb1500884dafc5c66', true, false, true),
    ('public', 'sg_raport_hapus', 'p_peserta_id uuid, p_tahun_ajaran text, p_semester text', '838c05fb8914c9d526b0f6c4ee8b9bd1', true, false, true),
    ('public', 'sg_raport_pengaturan_simpan', 'p_nilai jsonb', '9ffb66c60733030d27505b6e5bf0fdbf', true, false, true),
    ('public', 'sg_raport_simpan', 'p_peserta_id uuid, p_tahun_ajaran text, p_semester text, p_tingkat text, p_sikap integer, p_karakter text[], p_skk integer, p_predikat_akhir text, p_catatan text, p_deskripsi text, p_final boolean', '33f88fe07d91c8f1f52289a0190d1bef', true, false, true),
    ('public', 'sg_rombel_perbarui', 'p_data jsonb', '3f4e10caf65fddb5bf56055b47cb83e3', true, false, true),
    ('public', 'sg_saka_hapus', 'p_id bigint', 'b5d52772be52f6dc65c386120e715f3d', true, false, true),
    ('public', 'sg_saka_simpan', 'p_id bigint, p_peserta_id uuid, p_saka text, p_tanggal_masuk date, p_status text, p_tanggal_selesai date, p_surat_url text, p_catatan text', 'e91b7a8d56805c95fa5e88872d5747db', true, false, true),
    ('public', 'sg_sangga_atur', 'p_rombel text, p_data jsonb', 'c263a8e73fbb34c07bbe6eec0dbc3f5a', true, false, true),
    ('public', 'sg_sangga_rombel', 'p_rombel text', '32d8738b41141cbd0f41f6303c39550f', true, false, true),
    ('public', 'sg_sertifikat_tingkat', 'p_peserta_id uuid, p_tingkat text', 'd8790433b66c950053b0075cbd962a9e', true, false, true),
    ('public', 'sg_sesi_hapus', 'p_id integer', '5530ad82be568dc096b339f3abb5bd7e', true, false, true),
    ('public', 'sg_sesi_simpan', 'p_id integer, p_nama text, p_tanggal date, p_tempat text, p_catatan text, p_status text, p_butir text[], p_peserta uuid[]', 'c3acc485a3c36a6e2e6b9ed9e917c614', true, false, true),
    ('public', 'sg_sesi_status', 'p_id integer, p_status text', '9b695d526674806ad99ff42440b205b7', true, false, true),
    ('public', 'sg_sidang_hapus', 'p_id integer', 'b6439dc43b15e046acc7cbc857ffa4bd', true, false, true),
    ('public', 'sg_sidang_simpan', 'p_peserta_id uuid, p_tingkat text, p_tanggal date, p_keputusan text, p_magang text, p_tugas_adat text, p_tugas_adat_ket text, p_catatan text, p_nomor_manual text, p_nta text', '15d63c81b8e75e6a0aa6ef1efcd317c1', true, false, true),
    ('public', 'sg_sidang_token', 'p_id integer', 'd9809bfcecf1d835ebcda9e0c2a36353', true, false, true),
    ('public', 'sg_sidang_urut_atur', 'p_tahun integer, p_berikutnya integer', '23004cfe6121555e069d04a17dfd2b3b', true, false, true),
    ('public', 'sg_sku_ajukan', 'p_sku_id text, p_jadwal date, p_penguji_id uuid, p_catatan text', 'cef9a40d3228559386b2b827978c2f7a', true, false, true),
    ('public', 'sg_sku_alihkan', 'p_peserta_id uuid, p_sku_id text, p_penguji_id uuid, p_alasan text', 'd8441494fd91fab7971da5945440808a', true, false, true),
    ('public', 'sg_sku_batal', 'p_sku_id text', 'bf7ff364b88b55795e5ee46b71b94ef6', true, false, true),
    ('public', 'sg_sku_catat_internal', 'p_oleh uuid, p_peserta_id uuid, p_sku_id text, p_hasil text, p_tanggal_uji date, p_nilai text, p_catatan text', 'b6461d85e0c32db50f5cdbb711f29cc3', false, false, true),
    ('public', 'sg_sku_catat_rubrik_internal', 'p_oleh uuid, p_peserta_id uuid, p_sku_id text, p_tanggal_uji date, p_rincian jsonb, p_hasil text, p_catatan text', 'c6d5ffe67336373377686c3dff7018fb', false, false, true),
    ('public', 'sg_tkk_ambang_simpan', 'p_nilai jsonb', 'cee4f0c9e6897092b615de80807b33f8', true, false, true),
    ('public', 'sg_tkk_catat', 'p_peserta_id uuid, p_tkk_id text, p_tingkat text, p_tanggal date, p_penguji1 text, p_penguji2 text, p_melatih text, p_bukti_url text, p_catatan text', '32094815d5c9a4acc519f5d2782296dd', true, false, true),
    ('public', 'sg_tkk_hapus', 'p_id bigint', '53d4e36ca52d310a755621cbbfed3304', true, false, true),
    ('public', 'sg_tkk_krida_hapus', 'p_id bigint', '8e0c48552cec33b5b0d2911a1fbea734', true, false, true),
    ('public', 'sg_tkk_krida_simpan', 'p_id bigint, p_peserta_id uuid, p_nama text, p_saka text, p_tanggal date, p_bukti_url text, p_catatan text', '49a42800639fcbb2d3d2d7523a4e27d8', true, false, true),
    ('public', 'sg_verifikasi_kode', 'p_kode text', 'd5b9ea7378969f40c9f30224b0b55701', true, true, true),
    ('public', 'sg_verifikasi_token', 'p_token text', '9a1280fc48f4fae7b633231675208c9f', true, true, true),
    ('sigarda', 'agenda_batas_musyawarah', 'p_tahun_ajaran text', 'a8ed6c9655b2939648ea389eb7446bfc', true, false, true),
    ('sigarda', 'agenda_proses', '', '35b6907f4a57c6c01e89897d86f6b8ea', true, false, true),
    ('sigarda', 'aktif', '', '2eb422b1490f1382697dfaf593fb9c30', true, false, true),
    ('sigarda', 'asisten_iuran', '', 'f63a3798bac3f7d117bfd2ca049e90d3', true, false, true),
    ('sigarda', 'batalkan_pengajuan_berjalan', 'p_peserta uuid, p_alasan text', 'e879547c059848875f7ac72bd9f71711', true, false, true),
    ('sigarda', 'bina_damping_bersihkan', '', '21abb95323400616dc15c02690e4a5e1', true, false, true),
    ('sigarda', 'bina_damping_rombel', 'p_rombel text', '475199f8ea852cd1e223a894b0fa6f80', true, false, true),
    ('sigarda', 'bisa_menguji', 'p_id uuid', '8d392f0a1a3eee600c9e4dded093b234', true, false, true),
    ('sigarda', 'dewan', '', '38c542daa846e9d3b311dba5606ec34d', true, false, true),
    ('sigarda', 'ditugaskan', 'p_peserta uuid, p_penguji uuid', '4e6cb8e3eb1ad33c5f6273a98521530a', true, false, true),
    ('sigarda', 'eskalasi_isi', 'p_jenis text, p_tingkat integer, p_mulai date', 'db6ff2c7550efcb9bd9933d903ceb73f', true, false, true),
    ('sigarda', 'eskalasi_judul', 'p_jenis text, p_tingkat integer', 'dc3400b1c89c7d0aa6c3154b92863ee7', true, false, true),
    ('sigarda', 'eskalasi_mulai_absensi', 'p_peserta uuid', '8e555e9196fc7e689c02411b157950e5', true, false, true),
    ('sigarda', 'eskalasi_mulai_iuran', 'p_peserta uuid', 'a27c78dac42956491f788288539f41d1', true, false, true),
    ('sigarda', 'eskalasi_mulai_sku', 'p_peserta uuid', 'c0f4f6dffd261d0798ee5f8b3933ef20', true, false, true),
    ('sigarda', 'eskalasi_proses', '', 'b325c1ca8649901f1ad708d3f7f6bccb', true, false, true),
    ('sigarda', 'eskalasi_tab', 'p_jenis text', 'c27c97e43f4bef7ada6e5739aa47799c', true, false, true),
    ('sigarda', 'eskalasi_tingkat', 'p_hari integer', '343e2fb00765f480824d5a906effb96d', true, false, true),
    ('sigarda', 'format_nomor', 'p_format text, p_no integer, p_tanggal date, p_tingkat text', 'fa65c6c53ae62fb654493e84351641d9', true, false, true),
    ('sigarda', 'garuda_berkas_json', 'p_peserta_id uuid', 'b0423aa6cae5226e9d189085c75e63f2', true, false, true),
    ('sigarda', 'hari_ini', '', 'e7e493311fd79a1f4646f0e0aa785a6c', true, false, true),
    ('sigarda', 'instrumen_aktif', 'p_sku text', '415dfd6be38b69d7d7542c37a3d80ddd', true, false, true),
    ('sigarda', 'instrumen_angka', 'p_jalur text[], p_bawaan integer', '8316206c166281a72f06f4c538adaef5', true, false, true),
    ('sigarda', 'instrumen_gerbang', '', 'bd519e5ec6cbbbd675a418adab295c4b', true, false, true),
    ('sigarda', 'instrumen_hitung', 'p_sku text, p_rincian jsonb', '9c39e590c52041819e79b4d1bab8e806', true, false, true),
    ('sigarda', 'iuran_angka', 'p_kunci text, p_bawaan integer', '37085b5faaf6911cf69dcd8d960aa3d7', true, false, true),
    ('sigarda', 'iuran_hitung', 'p_peserta uuid, p_tanggal date', 'c9a4e896cc80c910e64447a98161e2e0', true, false, true),
    ('sigarda', 'jabatan_baku', 'p_teks text', 'dc7f0853a3c48051f3e70756f41e10ab', true, false, true),
    ('sigarda', 'jabatan_dewan_lepas', 'p_id uuid, p_alasan text', '653a3810136bea0737c68e478ed9b94a', true, false, true),
    ('sigarda', 'jabatan_tunggal', 'p_jabatan text', 'd17968c2e9b2dd3155985e2cb244d37a', true, false, true),
    ('sigarda', 'keepalive_atur', 'p_url text, p_kunci text', 'c4a0749a8ca56a522f1e4868c335d5ce', true, false, true),
    ('sigarda', 'keepalive_catat', '', '0b9fb0b26147f3d054b8e29f51abc705', true, false, true),
    ('sigarda', 'keepalive_matikan', '', 'df2aba474f9daa01d13e1f8b170ad07e', true, false, true),
    ('sigarda', 'keepalive_periksa', '', '5bfeb22dd16bbed6451d695961a49c67', true, false, true),
    ('sigarda', 'keepalive_ping', '', 'cdf4dd17055b228f795a7ff38d801609', true, false, true),
    ('sigarda', 'kegiatan_bulan_tanggal', 'p_tahun_ajaran text, p_bulan integer', 'bbdb96b81637dae66b8ff0521a950b22', true, false, true),
    ('sigarda', 'kegiatan_judul_bawaan', 'p_jenis text', '3330155c0a403fd8a7382299d0e95ffc', true, false, true),
    ('sigarda', 'kegiatan_pengingat', '', '794390521f7c15dc92f24fbff4f461e9', true, false, true),
    ('sigarda', 'kelola_materi', '', '22746b2e8e2c713ffc3b62e58ca0ada0', true, false, true),
    ('sigarda', 'ketua_sidang', 'OUT o_nama text, OUT o_sebutan text', '77cc024bd979b6075118da89683bef36', true, false, true),
    ('sigarda', 'kode_verifikasi', 'p_bagian text[]', 'b89f95a95516e293f88dcea930c12a37', true, false, true),
    ('sigarda', 'layak_garuda', 'p_peserta uuid', '50aab069d9b40a3511857d4c0cbb060e', true, false, true),
    ('sigarda', 'musyawarah_pengingat', '', '004adf0ae83d931a3439bd2a3b6916e9', true, false, true),
    ('sigarda', 'notif_buat', 'p_penerima uuid, p_jenis text, p_judul text, p_isi text, p_tautan jsonb, p_kunci text', '2d4b9c87664dbaef0e753394276e2111', true, false, true),
    ('sigarda', 'notif_dokumen', '', 'fcab8ec142a2bef4502e4c47c06362f2', true, false, true),
    ('sigarda', 'notif_label_butir', 'p_sku text', '8e1a6536ff0083300c43803bd070524d', true, false, true),
    ('sigarda', 'notif_penerima_uji', 'p_peserta uuid, p_sku text, p_penguji uuid', 'a7bed1bd1c92a0155a3ee93e90f4a243', true, false, true),
    ('sigarda', 'notif_pengingat', '', '2da31964ab53ee673d2c75dfbac2c696', true, false, true),
    ('sigarda', 'notif_pra_uji', '', '33ddda520e00be7f42960e85a2d11921', true, false, true),
    ('sigarda', 'notif_sesi_peserta', '', '2909b9eace71da48f15c5d2f60ca8132', true, false, true),
    ('sigarda', 'notif_sku_progress', '', '611aff08b14d968c8884d204cd951cff', true, false, true),
    ('sigarda', 'pad_nomor', 'p_no integer, p_lebar integer', '77ef115939c7cf9938625cf80002395d', true, false, true),
    ('sigarda', 'pembina_atau_admin', '', '22746b2e8e2c713ffc3b62e58ca0ada0', true, false, true),
    ('sigarda', 'pembina_saja', '', '73bb98bb30d6159c60aa96459f866311', true, false, true),
    ('sigarda', 'pencatat_iuran', '', 'f29c1d039c7b4a84adbbaaa8406d923e', true, false, true),
    ('sigarda', 'pengaturan_teks', 'p_kunci text, p_bawaan text', '8b74362aa493e1367a0a686e6c736156', true, false, true),
    ('sigarda', 'penguji_boleh', 'p_peserta uuid, p_penguji uuid, p_sku text', '759f771d51f1ec436092378d25e3f456', true, false, true),
    ('sigarda', 'penguji_peran_ok', 'p_peserta uuid, p_penguji uuid, p_sku text', 'a93cd676b9f76b667f93be82856d2be0', true, false, true),
    ('sigarda', 'penguji_sah', 'p_peserta uuid, p_sku text', 'a9e34e51971e317ed8d5b70c142af16f', true, false, true),
    ('sigarda', 'pengurus', '', 'c81284ebb4a43450df4540f06320dfd5', true, false, true),
    ('sigarda', 'peran', '', '10d099e585f8539a1ed3ac00a7b2944d', true, false, true),
    ('sigarda', 'pinsa_bersihkan', '', 'd7775309d340c9f65690504f9081bf6c', true, false, true),
    ('sigarda', 'pra_uji_aktif', '', '53a24cb9cc4b0d5a68423240d264a643', true, false, true),
    ('sigarda', 'pra_uji_beritahu_lulus', 'p_peserta uuid, p_sku text, p_tujuan text, p_dilewati boolean', 'a30116fd6c39667003b94e21a4518b4b', true, false, true),
    ('sigarda', 'pra_uji_mulai', 'p_peserta uuid, p_sku text, p_jadwal date, p_catatan text', '6af2f0e7a78ec1469ead26bc3a88a5e2', true, false, true),
    ('sigarda', 'pra_uji_nama_tahap', 'p_tahap text', '7a3edeed9dad75df152510d7daf5b78d', true, false, true),
    ('sigarda', 'pra_uji_pengingat', '', '208bf5ce1f9b07eac4f53130f864a742', true, false, true),
    ('sigarda', 'pra_uji_penilai_daftar', 'p_peserta uuid, p_sku text, p_tahap text', 'ea43419cb1b6f6d8b2df94bd1706f42a', true, false, true),
    ('sigarda', 'pra_uji_penilai_ok', 'p_peserta uuid, p_sku text, p_tahap text, p_penilai uuid', '0271aefcdd141d20f067c0cfca28f11d', true, false, true),
    ('sigarda', 'pra_uji_tahap_berikut', 'p_peserta uuid, p_sku text, p_setelah text', 'd16faefec48f424bec2689b07256abfc', true, false, true),
    ('sigarda', 'pra_uji_teruskan', 'p_peserta uuid, p_sku text, p_setelah text, p_jadwal date, p_catatan_peserta text, p_oleh uuid', 'c4a934f2201a28e8e27a4b753ec208fa', true, false, true),
    ('sigarda', 'pradana_atau_pradani', '', '846151b2512ffb6abb7b3d2731889844', true, false, true),
    ('sigarda', 'push_antre', '', 'b68ca0b709655e7038b5b00ddbc0709b', true, false, true),
    ('sigarda', 'push_atur', 'p_url text, p_rahasia text, p_kunci_publik text', '5febc2b9dd109b21f39f4258c1ea23d2', true, false, true),
    ('sigarda', 'rapikan', 'p_teks text', '30ce5e7b72e6a44d0fa015dbb8d71ac2', true, false, true),
    ('sigarda', 'raport_angka', 'p_jalur text[], p_bawaan integer', '80bb601486f521d4bc7ee55b7c76303b', true, false, true),
    ('sigarda', 'raport_hitung', 'p_peserta uuid, p_ta text, p_semester text, p_tingkat text', '0e6e3605caa34b8d0afe01cc9351ef79', true, false, true),
    ('sigarda', 'raport_predikat', 'p_skor integer', '640d54c85043d9e032903a37ebbd01b4', true, false, true),
    ('sigarda', 'raport_skor', 'p_kehadiran integer, p_capaian_lulus integer, p_capaian_target integer, p_sikap integer', '79691bff129ea098d6ef4941695e100f', true, false, true),
    ('sigarda', 'rombel_baku', 'p_teks text', '634bc722903b13ffbc14bb3589e723b9', true, false, true),
    ('sigarda', 'rombel_sah', 'p_rombel text', 'f83bdc232c7bf45c9133be276b8f458d', true, false, true),
    ('sigarda', 'sangga_bisa_atur', 'p_rombel text', '15b39b3ecca2972c1702f4a5c39bb9fc', true, false, true),
    ('sigarda', 'sangga_peringatan', 'p_rombel text', 'a7971e0e1d50b14f0b5e2b5f875fe7ca', true, false, true),
    ('sigarda', 'surat_agama_aktif', 'p_peserta uuid, p_sku text', 'c5ca8fe860373548c7d44cc38fc9b828', true, false, true),
    ('sigarda', 'tahun_ajaran_kini', '', 'e25a73053fa01afd4e0fb1d67b5d5569', true, false, true),
    ('sigarda', 'tahun_ajaran_sah', 'p_ta text', '597fe9670e904f6b3dec28145aff51c9', true, false, true),
    ('sigarda', 'tingkat_penegak', 'p_id uuid', 'c05b472bbf73e0ff92e9e006ae406e46', true, false, true),
    ('sigarda', 'tingkat_rombel', 'p_rombel text', '3e2bc03e09633c86a0cd605915b451ee', true, false, true),
    ('sigarda', 'tingkat_selesai', 'p_peserta uuid, p_tingkat text', 'a06ae41b8394bdcbf3c10cdd7376d675', true, false, true),
    ('sigarda', 'token_acak', '', '32c1b75699fb4018bdd152d2d997939a', true, false, true),
    ('sigarda', 'tolak_calon_garuda_tak_aktif', '', 'e026efe17e19bf46212234375dcdfab4', true, false, true),
    ('sigarda', 'tolak_peserta_tak_aktif', '', 'c9142172fb11ed04291a060c0bc2924b', true, false, true),
    ('sigarda', 'wajib_admin', 'p_pesan text', '2bc605b354c81c8d4c0bf18167e4368a', true, false, true),
    ('sigarda', 'wajib_aktif', '', '237a4516ca8cbb434ec92997369ddbdf', true, false, true)
),
ada_fungsi as (
  select n.nspname as skema, p.proname as nama, pg_get_function_identity_arguments(p.oid) as args, md5(replace(p.prosrc, chr(13), '')) as isi,
         has_function_privilege('authenticated', p.oid, 'execute') as au, has_function_privilege('anon', p.oid, 'execute') as an, has_function_privilege('service_role', p.oid, 'execute') as sv
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname in ('public', 'sigarda') and p.prokind = 'f'
),
hasil(kategori, objek, status) as (
  select 'Tabel', t.nama,
         case when c.oid is null then 'KURANG'
              when c.relrowsecurity is distinct from t.rls then 'RLS BEDA'
              when has_table_privilege('authenticated', c.oid, 'select') is distinct from t.sel then 'HAK BEDA'
              else 'OK' end
  from h_tabel t left join pg_class c on c.relname = t.nama and c.relnamespace = 'public'::regnamespace and c.relkind = 'r'
  union all
  select 'Kolom', k.tabel || '.' || k.kolom,
         case when i.column_name is null then 'KURANG' when i.data_type <> k.tipe then 'BEDA (tipe ' || i.data_type || ')' else 'OK' end
  from h_kolom k left join information_schema.columns i on i.table_schema = 'public' and i.table_name = k.tabel and i.column_name = k.kolom
  union all
  select 'Batasan', b.tabel || '.' || b.nama,
         case when c.oid is null then 'KURANG'
              when b.potongan is not null and position(b.potongan in pg_get_constraintdef(c.oid)) = 0 then 'BEDA'
              else 'OK' end
  from h_batasan b left join pg_constraint c on c.conname = b.nama and c.conrelid = to_regclass('public.' || quote_ident(b.tabel))
  union all
  select 'Indeks', x.tabel || '.' || x.nama, case when i.indexname is null then 'KURANG' else 'OK' end
  from h_indeks x left join pg_indexes i on i.schemaname = 'public' and i.tablename = x.tabel and i.indexname = x.nama
  union all
  select 'Kebijakan akses', k.tabel || '.' || k.nama,
         case when p.policyname is null then 'KURANG'
              when k.potongan is not null and position(k.potongan in coalesce(p.qual, '')) = 0 then 'BEDA'
              else 'OK' end
  from h_kebijakan k left join pg_policies p on p.schemaname = 'public' and p.tablename = k.tabel and p.policyname = k.nama
  union all
  select 'Pemicu', m.tabel || '.' || m.nama, case when t.tgname is null then 'KURANG' else 'OK' end
  from h_pemicu m left join pg_trigger t on t.tgname = m.nama and t.tgrelid = to_regclass('public.' || quote_ident(m.tabel)) and not t.tgisinternal
  union all
  select 'Fungsi', f.skema || '.' || f.nama || '(' || f.args || ')',
         case when a.nama is null then 'KURANG'
              when a.isi <> f.isi then 'BEDA (isi bukan versi terbaru)'
              when a.au <> f.au or a.an <> f.an or a.sv <> f.sv then 'HAK BEDA'
              else 'OK' end
  from h_fungsi f left join ada_fungsi a on a.skema = f.skema and a.nama = f.nama and a.args = f.args
),
lingkungan(kategori, objek, status) as (
  select 'Lingkungan', 'Ekstensi pg_net (pengirim notifikasi ke HP)', case when exists (select 1 from pg_extension where extname = 'pg_net') then 'OK' else 'PERHATIAN (belum aktif: notifikasi tidak terkirim ke HP)' end
  union all
  select 'Lingkungan', 'Ekstensi pg_cron (pengingat harian 07.00 WIB)', case when exists (select 1 from pg_extension where extname = 'pg_cron') then 'OK' else 'PERHATIAN (belum aktif: pengingat harian tidak berjalan)' end
  union all
  select 'Lingkungan', 'Jadwal pengingat harian sigarda-pengingat',
         case when to_regclass('cron.job') is null then 'PERHATIAN (pg_cron belum aktif)'
              when (xpath('/row/n/text()', query_to_xml('select count(*) as n from cron.job where jobname = ''sigarda-pengingat''', false, true, '')))[1]::text::int > 0 then 'OK'
              else 'PERHATIAN (jadwal belum ada: jalankan ulang migrasi notifikasi)' end
  union all
  select 'Lingkungan', 'Konfigurasi push (select sigarda.push_atur(...))',
         case when to_regclass('public.push_konfigurasi') is null then 'KURANG (migrasi notifikasi belum dijalankan)'
              when (select count(*) from public.push_konfigurasi) > 0 then 'OK' else 'PERHATIAN (belum diisi: notifikasi ke HP tidak dikirim)' end
  union all
  select 'Edge Function', 'sigarda dan notif-push (tidak dapat diperiksa dari SQL)', 'PERIKSA MANUAL (Dashboard > Edge Functions: waktu deploy terakhir harus sesudah kode terbaru diterbitkan)'
)
select urut, kategori, objek, status
from (
  select 0 as urut, '== RINGKASAN ==' as kategori, h.kategori || ': ' || count(*) filter (where h.status = 'OK') || ' dari ' || count(*) || ' sesuai' as objek,
         case when count(*) filter (where h.status <> 'OK') = 0 then 'OK' else 'PERIKSA (' || count(*) filter (where h.status <> 'OK') || ' masalah)' end as status
  from hasil h group by h.kategori
  union all
  select 1, h.kategori, h.objek, h.status from hasil h where h.status <> 'OK'
  union all
  select 2, l.kategori, l.objek, l.status from lingkungan l
) t
order by urut, kategori, objek;
