// Tahap 3 (H1): akun Penegak hanya nama, NIS, rombel; isian data diri mandiri (sg_isian_saya_simpan), agama sebagai penjaga progres SKU, RLS baca (privasi antar-Penegak dan Dewan),
// templat dokumen (rubrik surat guru), sangga kosong, cadangan. Logika klien: uji/isian-klien.mjs. Migrasi: uji/migrasi-isian-penegak.mjs.
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { siapkanPg, buatKlienFake, sqlSebagai } from '../src/lokal/klienFake.js';
import { isiDataContoh } from '../src/lokal/seedLokal.js';
import { PIN_DEMO } from '../src/lokal/pinDemo.js';
import { buatApi } from '../src/lib/api.js';

const P = process.cwd().replace(/\\/g, '/');
let gagal = 0, lulus = 0;
const ok = (c, m) => { if (c) { lulus++; console.log('ok   :', m); } else { gagal++; console.log('GAGAL:', m); } };
const pg = new PGlite();
await siapkanPg(pg, { sqlStub: readFileSync(`${P}/supabase/lokal/stub.sql`, 'utf8'), sqlSkema: readFileSync(`${P}/supabase/skema.sql`, 'utf8').replace(/^﻿/, '') });
await isiDataContoh(pg);
await pg.query('update public.profiles set wajib_ganti_pin = false');
const q = async (sql, p = []) => (await pg.query(sql, p)).rows;
const masuk = async (nama, pin) => { const k = buatKlienFake(pg); const a = buatApi(k); const r = await a.masuk(nama, pin); return { k, a, id: r.id }; };
const K = { admin: await masuk('admin', PIN_DEMO.admin), pembina: await masuk('pembina', PIN_DEMO.pembina), dewan: await masuk('dewan', PIN_DEMO.dewan) };
const N = {}; for (const nis of ['10231', '10232', '10008']) N[nis] = await masuk(nis, PIN_DEMO.penegak);
const [ahmad, siti, nadia] = ['10231', '10232', '10008'].map((n) => N[n].id);
const sebagai = async (id, sql, args = []) => { try { return { ok: true, rows: (await sqlSebagai(pg, id, sql, args)).rows }; } catch (e) { return { ok: false, pesan: e.message }; } };
const cocok = (r, re) => !r.ok && re.test(r.pesan ?? '');
const simpan = (id, data) => sebagai(id, 'select public.sg_isian_saya_simpan($1::jsonb) as n', [JSON.stringify(data)]);
const isi = (id) => q('select kunci, nilai from public.penegak_isian where peserta_id = $1 order by kunci', [id]);

console.log('--- Akun Penegak baru: hanya nama, NIS, rombel ---');
let r = await K.admin.a.buatAkun('peserta', [{ no: 1, nama: 'Budi Baru', nis: '20001', kelas: 'X-01' }]);
ok(r.ok && r.hasil?.[0]?.ok, 'akun dibuat tanpa jenis kelamin, sangga, dan agama ' + JSON.stringify(r.hasil?.[0] ?? r.pesan));
const pinBudi = r.hasil?.[0]?.pin;
const budiRow = (await q(`select id, sangga, agama, jenis_kelamin, kelas from public.profiles where username = '20001'`))[0];
ok(budiRow && budiRow.sangga === null && budiRow.agama === null && budiRow.jenis_kelamin === null && budiRow.kelas === 'X-01', 'baris profil: sangga, agama, jenis kelamin kosong (NULL)');
r = await K.admin.a.buatAkun('peserta', [{ no: 1, nama: 'Tanpa Rombel', nis: '20002' }]);
ok(r.ok && r.hasil?.[0]?.ok === false && /Kelas kosong/.test(r.hasil[0].pesan), 'rombel tetap wajib');
r = await K.admin.a.buatAkun('peserta', [{ no: 1, nama: 'Agama Salah', nis: '20003', kelas: 'X-01', agama: 'Pagan' }]);
ok(r.ok && r.hasil?.[0]?.ok === false && /Agama tidak dikenal/.test(r.hasil[0].pesan), 'agama yang diisi tetap harus dikenal');
r = await K.admin.a.buatAkun('peserta', [{ no: 1, nama: 'Lengkap Sekali', nis: '20004', kelas: 'XI-02', sangga: 'Sangga Elang', agama: 'Hindu' }]);
ok(r.ok && r.hasil?.[0]?.ok, 'yang mengisi sangga dan agama tetap tersimpan');
const lengkap = (await q(`select sangga, agama from public.profiles where username = '20004'`))[0];
ok(lengkap.sangga === 'Sangga Elang' && lengkap.agama === 'Hindu', 'sangga dan agama dari admin tersimpan');
const budi = await masuk('20001', pinBudi);
await pg.query('update public.profiles set wajib_ganti_pin = false');
ok(!!budi.id && budi.id === budiRow.id, 'akun baru dapat masuk dengan PIN awal');

console.log('\n--- Agama sebagai penjaga progres SKU ---');
const butir = (await q(`select id from public.sku_unit where tingkat = 'Bantara' and agama is null order by id limit 1`))[0].id;
r = await sebagai(budi.id, `select public.sg_sku_ajukan($1, sigarda.hari_ini(), null::uuid, '')`, [butir]);
ok(cocok(r, /Isi agama Anda lebih dulu/), 'Penegak tanpa agama tidak dapat mengajukan SKU (pesan menuntun) ' + (r.pesan ?? ''));
try { await q(`insert into public.sku_progress (peserta_id, sku_id, status) values ($1, $2, 'diajukan')`, [budi.id, butir]); ok(false, 'penulisan progres langsung ditolak'); }
catch (e) { ok(/belum mengisi agama/.test(e.message), 'pemicu menolak penulisan progres SKU langsung (pesan untuk pihak lain)'); }
ok((await q('select count(*)::int n from public.sku_progress where peserta_id = $1', [budi.id]))[0].n === 0, 'tidak ada progres tersimpan');

console.log('\n--- sg_isian_saya_simpan: profil (sekali isi) ---');
r = await simpan(budi.id, { agama: 'Islam', jk: 'L', lahir: '2009-03-15', nta: '11.03.10.701.00001' });
ok(r.ok && Number(r.rows[0].n) === 4, 'jenis kelamin, agama, tanggal lahir, NTA terisi sekali (4 perubahan) ' + (r.pesan ?? ''));
const prof = (await q(`select agama, jenis_kelamin, nta from public.profiles where id = $1`, [budi.id]))[0];
ok(prof.agama === 'Islam' && prof.jenis_kelamin === 'L' && prof.nta === '11.03.10.701.00001', 'profil terisi');
ok((await q(`select tanggal::text t, dicatat_oleh = peserta_id as sendiri from public.tanggal_lahir where peserta_id = $1`, [budi.id]))[0].t === '2009-03-15', 'tanggal lahir tercatat (pencatat = pemilik)');
r = await simpan(budi.id, { agama: 'Islam', jk: 'L', lahir: '2009-03-15' });
ok(r.ok && Number(r.rows[0].n) === 0, 'mengirim nilai yang sama tidak mengubah apa pun dan tidak galat');
r = await simpan(budi.id, { agama: 'Hindu' });
ok(cocok(r, /Agama sudah tercatat/), 'agama yang sudah tercatat tidak dapat diganti sendiri');
r = await simpan(budi.id, { jk: 'P' });
ok(cocok(r, /Jenis kelamin sudah tercatat/), 'jenis kelamin yang sudah tercatat tidak dapat diganti sendiri');
r = await simpan(budi.id, { lahir: '2009-03-16' });
ok(cocok(r, /Tanggal lahir sudah tercatat/), 'tanggal lahir yang sudah tercatat tidak dapat diganti sendiri');
r = await simpan(budi.id, { nta: '99' });
ok(cocok(r, /NTA sudah tercatat/), 'NTA yang sudah tercatat tidak dapat diganti sendiri');
r = await simpan(budi.id, { agama: '', jk: '' });
ok(r.ok && (await q(`select agama from public.profiles where id = $1`, [budi.id]))[0].agama === 'Islam', 'kunci profil kosong = tidak diubah (agama tidak terhapus)');
r = await sebagai(budi.id, `select public.sg_sku_ajukan($1, sigarda.hari_ini(), null::uuid, '')`, [butir]);
ok(r.ok, 'sesudah agama diisi, SKU dapat diajukan ' + (r.pesan ?? ''));

console.log('\n--- sg_isian_saya_simpan: isian data diri ---');
r = await simpan(budi.id, { tempat_lahir: 'Purbalingga', alamat: 'Jl. Melati 5, Bukateja', ayah_nama: 'Slamet', ayah_hp: '0812-3456-7890', tinggi: '165', gol_darah: 'O', pend_smp_nama: 'SMPN 1', pend_smp_lulus: '2024', keg1_nama: 'Jambore Ranting', keg1_tingkat: 'kwarran', it1_nama: 'Canva', it1_level: 'bisa', bid1_nama: 'Menari' });
ok(r.ok && Number(r.rows[0].n) === 13, '13 isian tersimpan ' + (r.pesan ?? ''));
ok((await isi(budi.id)).find((x) => x.kunci === 'alamat')?.nilai === 'Jl. Melati 5, Bukateja', 'nilai tersimpan apa adanya');
r = await simpan(budi.id, { alamat: '   Jl.   Kenanga   9  ' });
ok(r.ok && (await isi(budi.id)).find((x) => x.kunci === 'alamat').nilai === 'Jl. Kenanga 9', 'spasi dirapikan');
r = await simpan(budi.id, { alamat: '' });
ok(r.ok && !(await isi(budi.id)).some((x) => x.kunci === 'alamat'), 'nilai kosong menghapus isian');
r = await simpan(budi.id, { alamat: 'A' });
r = await simpan(budi.id, { alamat: 'A' });
ok(r.ok && Number(r.rows[0].n) === 0, 'nilai yang sama = tidak dihitung berubah');
r = await simpan(budi.id, { alamat: 'B', kunci_asing: 'x' });
ok(cocok(r, /tidak dikenal/) && (await isi(budi.id)).find((x) => x.kunci === 'alamat').nilai === 'A', 'kunci asing menggagalkan seluruh permintaan (semua atau tidak sama sekali)');
r = await simpan(budi.id, { no_hp: '123' });
ok(cocok(r, /Nomor telepon/), 'nomor telepon salah ditolak');
r = await simpan(budi.id, { tinggi: '20' });
ok(cocok(r, /Tinggi badan/), 'tinggi di luar batas ditolak');
r = await simpan(budi.id, { gol_darah: 'C' });
ok(cocok(r, /Golongan darah/), 'golongan darah salah ditolak');
r = await simpan(budi.id, { keg1_tingkat: 'nasional' });
ok(cocok(r, /Tingkat kegiatan/), 'tingkat kegiatan salah ditolak');
r = await simpan(budi.id, { alamat: 'x'.repeat(201) });
ok(cocok(r, /maksimal 200/), 'terlalu panjang ditolak');
r = await simpan(budi.id, { alamat: '<script>' });
ok(cocok(r, /karakter yang tidak diizinkan/), 'karakter <> ditolak');
r = await simpan(budi.id, { alamat: 5 });
ok(cocok(r, /harus berupa teks/), 'nilai bukan teks ditolak');
r = await simpan(budi.id, [1]);
ok(cocok(r, /Data isian tidak sah/), 'bukan objek ditolak');
r = await simpan(budi.id, { lahir: '2030-01-01' });
ok(cocok(r, /masa depan/) || cocok(r, /sudah tercatat/), 'tanggal lahir masa depan/berbeda ditolak');

console.log('\n--- Hak: hanya Penegak aktif, untuk dirinya sendiri ---');
r = await simpan(K.pembina.id, { alamat: 'x' });
ok(cocok(r, /hanya untuk Penegak/), 'Pembina tidak dapat memakai isian Penegak');
r = await simpan(K.admin.id, { alamat: 'x' });
ok(cocok(r, /hanya untuk Penegak/), 'Admin tidak dapat memakai isian Penegak');
r = await simpan(K.dewan.id, { alamat: 'x' });
ok(cocok(r, /hanya untuk Penegak/), 'akun Dewan lama tidak dapat memakai isian Penegak');
r = await simpan(nadia, { alamat: 'Alamat Nadia' });
ok(r.ok, 'Penegak berjabatan Dewan tetap menyimpan isian sebagai Penegak');
const kelasSiti = (await q('select kelas from public.profiles where id = $1', [siti]))[0].kelas;
await sebagai(K.pembina.id, `select public.sg_anggota_status_atur($1, 'nonaktif', null, 'uji')`, [siti]);
r = await simpan(siti, { alamat: 'x' });
ok(cocok(r, /hanya dapat dilihat/), 'Penegak nonaktif tidak dapat menyimpan');
r = await sebagai(K.pembina.id, `select public.sg_anggota_status_atur($1, 'aktif', $2, '')`, [siti, kelasSiti]);
ok(r.ok, 'Penegak diaktifkan kembali ' + (r.pesan ?? ''));

console.log('\n--- RLS baca: pemilik, Pembina, Admin (bukan Dewan, bukan Penegak lain) ---');
await simpan(siti, { alamat: 'Alamat Siti' });
r = await sebagai(siti, 'select peserta_id from public.penegak_isian');
ok(r.ok && r.rows.length > 0 && r.rows.every((x) => x.peserta_id === siti), 'Penegak hanya membaca isian miliknya');
r = await sebagai(nadia, 'select peserta_id from public.penegak_isian');
ok(r.ok && r.rows.every((x) => x.peserta_id === nadia), 'Penegak berjabatan Dewan juga hanya membaca miliknya (alamat pribadi)');
r = await sebagai(K.pembina.id, 'select distinct peserta_id from public.penegak_isian');
ok(r.ok && r.rows.length >= 3, 'Pembina membaca semua');
r = await sebagai(K.admin.id, 'select distinct peserta_id from public.penegak_isian');
ok(r.ok && r.rows.length >= 3, 'Admin membaca semua');
r = await sebagai(K.dewan.id, 'select 1 from public.penegak_isian');
ok(r.ok && r.rows.length === 0, 'akun Dewan lama tidak membaca isian Penegak');
r = await sebagai(siti, `insert into public.penegak_isian (peserta_id, kunci, nilai) values ($1, 'alamat', 'lewat pintu belakang')`, [siti]);
ok(!r.ok, 'Penegak tidak dapat menulis langsung ke tabel');
r = await K.pembina.a.muatIsian(budi.id);
ok(r.ok && r.data.isian.tempat_lahir === 'Purbalingga' && r.data.lahir === '2009-03-15', 'api().muatIsian(id): Pembina membaca isian dan tanggal lahir satu Penegak');
r = await budi.a.muatIsian();
ok(r.ok && r.data.isian.tempat_lahir === 'Purbalingga' && r.data.lahir === '2009-03-15' && !('alamat_orang_lain' in r.data.isian), 'api().muatIsian(): Penegak membaca miliknya');
r = await N['10232'].a.muatIsian(budi.id);
ok(r.ok && Object.keys(r.data.isian).length === 0 && r.data.lahir === null, 'Penegak lain yang meminta isian Budi mendapat kosong (RLS)');

console.log('\n--- Templat dokumen: hak, validasi, upsert, baca ---');
const tpl = (id, ta, jenis, isiTpl) => sebagai(id, 'select public.sg_dokumen_templat_simpan($1, $2, $3::jsonb) as id', [ta, jenis, JSON.stringify(isiTpl)]);
const sahTpl = { uji: 'memahami UUD 1945', baris: ['# Pembukaan', 'Hafal pembukaan', 'Hafal jumlah pasal'], pita: ['Cukup', 'Baik', 'Sangat Baik'] };
r = await tpl(siti, '2026/2027', 'surat_uud', sahTpl);
ok(cocok(r, /Hanya Pembina dan Admin/), 'Penegak tidak dapat mengisi templat');
r = await tpl(K.dewan.id, '2026/2027', 'surat_uud', sahTpl);
ok(cocok(r, /Hanya Pembina dan Admin/), 'akun Dewan lama tidak dapat mengisi templat');
r = await tpl(K.pembina.id, '2026-2027', 'surat_uud', sahTpl);
ok(cocok(r, /Tahun ajaran harus/), 'format tahun ajaran salah ditolak');
r = await tpl(K.pembina.id, '2026/2028', 'surat_uud', sahTpl);
ok(cocok(r, /Tahun ajaran harus/), 'tahun ajaran tidak berurutan ditolak');
r = await tpl(K.pembina.id, '2026/2027', 'surat_lain', sahTpl);
ok(cocok(r, /Jenis templat tidak dikenal/), 'jenis tidak dikenal ditolak');
r = await tpl(K.pembina.id, '2026/2027', 'surat_uud', { ...sahTpl, lain: 1 });
ok(cocok(r, /Bentuk isi templat/), 'kunci tambahan ditolak');
r = await tpl(K.pembina.id, '2026/2027', 'surat_uud', { uji: 'x' });
ok(cocok(r, /Baris rubrik harus/), 'baris wajib ada');
r = await tpl(K.pembina.id, '2026/2027', 'surat_uud', { baris: [''] });
ok(cocok(r, /1 sampai 300 karakter/), 'baris kosong ditolak');
r = await tpl(K.pembina.id, '2026/2027', 'surat_uud', { baris: Array.from({ length: 41 }, (_, i) => `b${i}`) });
ok(cocok(r, /maksimal 40/), 'lebih dari 40 baris ditolak');
r = await tpl(K.pembina.id, '2026/2027', 'surat_uud', { baris: ['a'], pita: ['1', '2'] });
ok(cocok(r, /tiga teks/), 'pita harus tiga');
r = await tpl(K.pembina.id, '2026/2027', 'surat_uud', { baris: ['<b>'] });
ok(cocok(r, /karakter khusus/), 'karakter <> ditolak');
ok((await q('select count(*)::int n from public.dokumen_templat'))[0].n === 0, 'tidak ada templat tersimpan oleh isian yang ditolak');
r = await tpl(K.pembina.id, '2026/2027', 'surat_uud', sahTpl);
ok(r.ok, 'Pembina menyimpan templat ' + (r.pesan ?? ''));
const idTpl = r.rows?.[0]?.id;
r = await tpl(K.admin.id, '2026/2027', 'surat_uud', { baris: ['Satu', '  Dua   spasi  '] });
ok(r.ok && (await q('select count(*)::int n from public.dokumen_templat'))[0].n === 1, 'menyimpan ulang tahun ajaran dan jenis yang sama = mengganti (satu baris)');
const isiTpl = (await q('select isi from public.dokumen_templat'))[0].isi;
ok(JSON.stringify(isiTpl.baris) === JSON.stringify(['Satu', 'Dua spasi']) && !('pita' in isiTpl) && !('uji' in isiTpl), 'isi dirapikan; pita dan uji yang tidak dikirim tidak tersimpan');
r = await sebagai(siti, 'select 1 from public.dokumen_templat');
ok(r.ok && r.rows.length === 0, 'Penegak tidak membaca templat');
r = await sebagai(K.dewan.id, 'select 1 from public.dokumen_templat');
ok(r.ok && r.rows.length === 0, 'akun Dewan lama tidak membaca templat');
r = await K.pembina.a.muatTemplatDokumen();
ok(r.ok && r.data.length === 1 && r.data[0].jenis === 'surat_uud' && r.data[0].isi.baris.length === 2 && r.data[0].isi.pita === null, 'api().muatTemplatDokumen memetakan templat');
r = await K.pembina.a.simpanTemplatDokumen({ tahunAjaran: '2026/2027', jenis: 'surat_seni', isi: { uji: 'seni', baris: ['a'] } });
ok(r.ok, 'api().simpanTemplatDokumen');
r = await sebagai(siti, 'select public.sg_dokumen_templat_hapus($1::bigint)', [idTpl]);
ok(cocok(r, /Hanya Pembina dan Admin/), 'Penegak tidak dapat menghapus templat');
r = await K.pembina.a.hapusTemplatDokumen(idTpl);
ok(r.ok && (await q('select count(*)::int n from public.dokumen_templat'))[0].n === 1, 'api().hapusTemplatDokumen');
r = await sebagai(siti, `insert into public.dokumen_templat (tahun_ajaran, jenis, isi) values ('2026/2027', 'surat_tik', '{}')`);
ok(!r.ok, 'templat tidak dapat ditulis langsung');

console.log('\n--- Sangga kosong ---');
r = await sebagai(K.pembina.id, 'select public.sg_sangga_rombel($1) as d', ['X-01']);
const dat = r.rows?.[0]?.d;
ok(r.ok && dat.anggota.some((a) => a.id === budi.id && a.sangga === null), 'sg_sangga_rombel menampilkan Penegak tanpa sangga (null)');
ok(dat.peringatan.some((p) => /belum punya sangga/.test(p.teks) && p.sangga === null), 'peringatan rombel memuat jumlah Penegak tanpa sangga');
ok(!dat.peringatan.some((p) => p.sangga === null && /Sangga\s+belum/.test(p.teks)) && !dat.peringatan.some((p) => /Sangga\s+beranggotakan/.test(p.teks)), 'kelompok tanpa sangga tidak dihitung sebagai sangga bernama kosong');
r = await sebagai(K.pembina.id, 'select public.sg_sangga_atur($1, $2::jsonb) as d', ['X-01', JSON.stringify([{ id: budi.id, pinsa: true }])]);
ok(cocok(r, /belum punya sangga/), 'Pinsa tidak dapat dipilih dari Penegak tanpa sangga');
r = await sebagai(K.pembina.id, 'select public.sg_sangga_atur($1, $2::jsonb) as d', ['X-01', JSON.stringify([{ id: budi.id, sangga: 'Sangga Elang' }])]);
ok(r.ok && (await q('select sangga from public.profiles where id = $1', [budi.id]))[0].sangga === 'Sangga Elang', 'Pembina membagi sangga untuk Penegak yang belum punya');

console.log('\n--- Ubah anggota: sangga dan agama opsional ---');
const baru2 = await K.admin.a.buatAkun('peserta', [{ no: 1, nama: 'Cindy Baru', nis: '20005', kelas: 'X-02' }]);
const cindy = (await q(`select id from public.profiles where username = '20005'`))[0].id;
r = await sebagai(K.admin.id, `select public.sg_anggota_ubah($1, 'Cindy Baru Ubah', 'X-02', '', '', null)`, [cindy]);
ok(r.ok, 'Admin mengubah nama Penegak tanpa sangga dan agama ' + (r.pesan ?? ''));
const cRow = (await q('select nama, sangga, agama from public.profiles where id = $1', [cindy]))[0];
ok(cRow.nama === 'Cindy Baru Ubah' && cRow.sangga === null && cRow.agama === null, 'sangga tetap kosong dan agama tetap kosong');
r = await sebagai(K.admin.id, `select public.sg_anggota_ubah($1, 'Cindy Baru Ubah', 'X-02', '', 'Buddha', null)`, [cindy]);
ok(r.ok && (await q('select agama from public.profiles where id = $1', [cindy]))[0].agama === 'Buddha', 'Admin dapat mengisi agama');
r = await sebagai(K.admin.id, `select public.sg_anggota_ubah($1, 'Cindy Baru Ubah', 'X-02', '', '', null)`, [cindy]);
ok(r.ok && (await q('select agama from public.profiles where id = $1', [cindy]))[0].agama === 'Buddha', 'agama kosong = tidak diubah (agama yang sudah ada tidak dapat dikosongkan)');
r = await sebagai(K.admin.id, `select public.sg_anggota_ubah($1, 'Cindy', '', '', '', null)`, [cindy]);
ok(cocok(r, /rombel\) peserta wajib/), 'rombel tetap wajib');
r = await sebagai(K.admin.id, `select public.sg_anggota_ubah($1, 'Cindy', 'X-02', '', 'Pagan', null)`, [cindy]);
ok(cocok(r, /Agama tidak dikenal/), 'agama yang diisi harus dikenal');

console.log('\n--- Cadangan dan katalog ---');
r = await sebagai(K.admin.id, 'select public.sg_cadangan_admin() as d');
const cad = r.rows?.[0]?.d;
const tabel = cad?.tabel ?? cad?.data?.tabel ?? cad;
ok(r.ok && Array.isArray(tabel.penegak_isian) && tabel.penegak_isian.length > 0 && Array.isArray(tabel.dokumen_templat), 'cadangan data memuat penegak_isian dan dokumen_templat');
r = await sebagai(K.admin.id, `select has_table_privilege('authenticated', 'public.penegak_isian', 'insert') as t, has_table_privilege('authenticated', 'public.dokumen_templat', 'update') as u, has_table_privilege('authenticated', 'public.penegak_isian', 'select') as s`);
ok(r.ok && r.rows[0].t === false && r.rows[0].u === false && r.rows[0].s === true, 'tabel baru: hanya baca (tanpa hak tulis langsung)');

console.log(`RINGKASAN ISIAN-PENEGAK: ${lulus} lulus, ${gagal} gagal`);
process.exit(gagal ? 1 : 0);
