// Pinsa tertugas lintas rombel (persiapan uji coba 2 Okt 2026): Penegak Calon Laksana dari rombel lain ditugaskan menjadi Pinsa sebuah sangga (tabel pinsa_tugas). Server (PGlite):
// hak, validasi, jalur pra-uji lewat Pinsa tertugas, peringatan sangga, Periksa Data, sg_pendampingan_saya, pembersihan otomatis, RLS, dan cadangan.
// Klien: uji/pinsa-tugas-klien.mjs. Migrasi: uji/migrasi-pinsa-tugas.mjs.
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { siapkanPg, buatKlienFake, sqlSebagai } from '../src/lokal/klienFake.js';
import { isiDataContoh } from '../src/lokal/seedLokal.js';
import { PIN_DEMO } from '../src/lokal/pinDemo.js';
import { buatApi } from '../src/lib/api.js';
import { tahunAjaranKini } from '../src/lib/rombelLogic.js';

const P = process.cwd().replace(/\\/g, '/');
let gagal = 0, lulus = 0;
const ok = (c, m) => { if (c) { lulus++; console.log('ok   :', m); } else { gagal++; console.log('GAGAL:', m); } };
const pg = new PGlite();
await siapkanPg(pg, { sqlStub: readFileSync(`${P}/supabase/lokal/stub.sql`, 'utf8'), sqlSkema: readFileSync(`${P}/supabase/skema.sql`, 'utf8').replace(/^﻿/, '') });
await isiDataContoh(pg);
await pg.query('update public.profiles set wajib_ganti_pin = false');
const q = async (sql, p = []) => (await pg.query(sql, p)).rows;
const masuk = async (nama, pin) => { const k = buatKlienFake(pg); const a = buatApi(k); const r = await a.masuk(nama, pin); return { k, a, id: r.id }; };
const K = { admin: await masuk('admin', PIN_DEMO.admin), pembina: await masuk('pembina', PIN_DEMO.pembina), dewan: await masuk('dewan', PIN_DEMO.dewan) };
const NIS = ['10231', '10232', '10118', '10007', '10008', '10233', '10234'];
const N = {}; for (const nis of NIS) N[nis] = await masuk(nis, PIN_DEMO.penegak);
const [ahmad, siti, dimas, bagas, nadia, rizky, kevin] = NIS.map((n) => N[n].id);
const ta = tahunAjaranKini();
const sebagai = async (id, sql, args = []) => { try { return { ok: true, rows: (await sqlSebagai(pg, id, sql, args)).rows }; } catch (e) { return { ok: false, pesan: e.message }; } };
const cocok = (r, re) => !r.ok && re.test(r.pesan ?? '');
const ajukan = (id, sku) => sebagai(id, 'select public.sg_sku_ajukan($1, $2::date, $3::uuid, $4)', [sku, '2030-01-10', null, 'siap']);
const batal = (id, sku) => sebagai(id, 'select public.sg_sku_batal($1)', [sku]);
const catat = (id, pid, hasil, cat = '') => sebagai(id, 'select public.sg_pra_uji_catat($1, $2, $3) as h', [pid, hasil, cat]);
const antrian = (id) => sebagai(id, 'select public.sg_pra_uji_antrian() as a');
const menunggu = (pid, sku) => q(`select id, tahap from public.sku_pra_uji where peserta_id = $1 and sku_id = $2 and status = 'menunggu'`, [pid, sku]);
const progres = async (pid, sku) => (await q('select status from public.sku_progress where peserta_id = $1 and sku_id = $2', [pid, sku]))[0];
const tugaskan = (id, rombel, sangga, pid) => sebagai(id, 'select public.sg_pinsa_tugaskan($1, $2, $3::uuid) as h', [rombel, sangga, pid]);
const cabut = (id, rombel, pid) => sebagai(id, 'select public.sg_pinsa_cabut($1, $2::uuid) as h', [rombel, pid]);
const daftarTugas = () => q('select p.username, t.rombel, t.sangga from public.pinsa_tugas t join public.profiles p on p.id = t.penegak_id order by 1');
const tulisSku = (pid, tingkat) => q(
  `insert into public.sku_progress (peserta_id, sku_id, status) select p.id, u.id, 'lulus' from public.profiles p join public.sku_unit u on u.tingkat = $2 and (u.agama is null or u.agama = p.agama)
   where p.id = $1 on conflict (peserta_id, sku_id) do update set status = 'lulus'`, [pid, tingkat]);

console.log('--- Persiapan: X-01 (Siti Pinsa sangga Merak, Kevin Calon Laksana sangga Elang, Bagas dan Nadia Bina Damping) dan X-02 (Ahmad, Dimas Bina Damping, Rizky sangga Rajawali) ---');
const B = (await q(`select id from public.sku_unit where tingkat = 'Bantara' and agama is null order by butir_no, id limit 4`)).map((x) => x.id);
const [B1, B2, B3, B4] = B;
await q('delete from public.penugasan_rombel'); await q('delete from public.penugasan_peserta');
await q('delete from public.sku_progress where peserta_id = any($1::uuid[])', [[ahmad, siti, dimas, bagas, nadia, rizky, kevin]]);
await q(`update public.profiles set kelas = 'X-01', sangga = 'Sangga Merak' where id = $1`, [siti]);
await q(`update public.profiles set kelas = 'X-01', sangga = 'Sangga Elang' where id = any($1::uuid[])`, [[bagas, nadia, kevin]]);
await q(`update public.profiles set kelas = 'X-02', sangga = 'Sangga Rajawali' where id = any($1::uuid[])`, [[ahmad, dimas, rizky]]);
for (const id of [siti, bagas, nadia, dimas, kevin, rizky]) await tulisSku(id, 'Bantara');
await tulisSku(bagas, 'Laksana');
let r = await K.pembina.a.aturJabatanDewan([{ username: '10007', jabatan: 'Bendahara' }, { username: '10008', jabatan: 'Sekretaris' }, { username: '10118', jabatan: 'Humas' }]);
ok(r.ok, 'jabatan Dewan untuk Bagas, Nadia, dan Dimas');
await q(`update public.profiles set pinsa = true where id = $1`, [siti]);
await q(`insert into public.bina_damping (tahun_ajaran, rombel, penegak_id) values ($1, 'X-01', $2), ($1, 'X-01', $3), ($1, 'X-02', $4)`, [ta, bagas, nadia, dimas]);
r = await sebagai(K.pembina.id, 'select public.sg_pra_uji_sakelar(true) as h');
ok(r.ok, 'sakelar pra-uji dihidupkan');
ok((await q('select sigarda.tingkat_penegak($1) t', [kevin]))[0].t === 'calon-laksana', 'Kevin: Calon Laksana (Bantara selesai), tetapi dari rombel X-01');

console.log('\n--- Sebelum penugasan: sangga Rajawali (X-02) tanpa Pinsa ---');
r = await sebagai(K.pembina.id, 'select public.sg_sangga_rombel($1) as d', ['X-02']);
ok(r.ok && r.rows[0].d.pinsa_tugas.length === 0 && r.rows[0].d.peringatan.some((p) => /Sangga Rajawali belum punya Pinsa/.test(p.teks)), 'peringatan: Sangga Rajawali belum punya Pinsa');
r = await sebagai(K.pembina.id, 'select public.sg_pemeriksaan_data() as d');
ok(r.ok && r.rows[0].d.sanggaTanpaPinsa.some((x) => x.rombel === 'X-02' && x.sangga === 'Sangga Rajawali'), 'Periksa Data: Sangga Rajawali tampil di sanggaTanpaPinsa');
r = await ajukan(ahmad, B1);
ok(r.ok && (await menunggu(ahmad, B1))[0]?.tahap === 'bina_damping', 'tanpa Pinsa: tahap Pinsa dilewati, pengajuan ke Bina Damping');
await batal(ahmad, B1);

console.log('\n--- Hak dan validasi penugasan ---');
r = await tugaskan(siti, 'X-02', 'Sangga Rajawali', kevin);
ok(cocok(r, /Hanya Bina Damping rombel ini, Pembina, dan Admin Gudep/), 'Penegak biasa tidak dapat menugaskan Pinsa');
r = await tugaskan(bagas, 'X-02', 'Sangga Rajawali', kevin);
ok(cocok(r, /Hanya Bina Damping rombel ini/), 'Bina Damping rombel LAIN (Bagas, X-01) tidak dapat menugaskan Pinsa di X-02');
r = await tugaskan(K.dewan.id, 'X-02', 'Sangga Rajawali', kevin);
ok(cocok(r, /Hanya Bina Damping rombel ini/), 'akun Dewan lama tidak dapat menugaskan Pinsa');
r = await tugaskan(K.pembina.id, 'X-99', 'Sangga Rajawali', kevin);
ok(cocok(r, /Rombel tidak sah/), 'rombel tidak baku ditolak');
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Tidak Ada', kevin);
ok(cocok(r, /belum ada di rombel X-02/), 'sangga yang belum ada di rombel ditolak');
r = await tugaskan(K.pembina.id, 'X-02', '', kevin);
ok(cocok(r, /belum ada di rombel X-02/), 'sangga kosong ditolak');
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Rajawali', ahmad);
ok(cocok(r, /belum menyelesaikan SKU Bantara/), 'Penegak yang belum menyelesaikan Bantara tidak dapat menjadi Pinsa');
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Rajawali', K.pembina.id);
ok(cocok(r, /tidak ditemukan atau tidak aktif/), 'bukan Penegak ditolak');
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Rajawali', siti);
ok(cocok(r, /sudah menjadi Pinsa di sangga sendiri/), 'Pinsa sangga sendiri (Siti) tidak dapat sekaligus ditugaskan');
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Rajawali', rizky);
ok(cocok(r, /anggota sangga ini sendiri/), 'anggota sangga itu sendiri (Rizky) dijadikan Pinsa lewat centang, bukan penugasan');
ok((await daftarTugas()).length === 0, 'tidak ada penugasan tersimpan dari isian yang ditolak');

console.log('\n--- Calon Pinsa ---');
r = await sebagai(siti, 'select public.sg_pinsa_calon($1) as d', ['X-02']);
ok(cocok(r, /Hanya Bina Damping rombel ini/), 'Penegak biasa tidak dapat membuka daftar calon');
r = await sebagai(K.pembina.id, 'select public.sg_pinsa_calon($1) as d', ['X-02']);
const calon = r.rows?.[0]?.d?.calon ?? [];
ok(r.ok && calon.some((c) => c.id === kevin && c.kelas === 'X-01') && !calon.some((c) => c.id === ahmad) && !calon.some((c) => c.id === siti), 'calon: Kevin ada (dari X-01); Ahmad (belum Bantara) dan Siti (sudah Pinsa) tidak');
r = await sebagai(dimas, 'select public.sg_pinsa_calon($1) as d', ['X-02']);
ok(r.ok, 'Bina Damping rombel itu (Dimas) dapat membuka daftar calon');

console.log('\n--- Menugaskan Kevin (X-01) menjadi Pinsa Sangga Rajawali (X-02) ---');
r = await tugaskan(dimas, 'X-02', 'sangga rajawali', kevin);
ok(r.ok, 'Bina Damping X-02 (Dimas) menugaskan Kevin; nama sangga tidak membedakan huruf besar/kecil ' + (r.pesan ?? ''));
const t1 = await daftarTugas();
ok(t1.length === 1 && t1[0].username === '10234' && t1[0].rombel === 'X-02' && t1[0].sangga === 'Sangga Rajawali', 'tersimpan dengan nama sangga baku: ' + JSON.stringify(t1));
ok(r.ok && Array.isArray(r.rows[0].h.peringatan) && !r.rows[0].h.peringatan.some((p) => /Rajawali belum punya Pinsa/.test(p.teks)), 'peringatan "belum punya Pinsa" hilang');
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Rajawali', kevin);
ok(cocok(r, /sudah bertugas sebagai Pinsa sangga Sangga Rajawali rombel X-02/), 'satu orang hanya satu sangga per tahun ajaran');
r = await sebagai(K.pembina.id, 'select public.sg_pinsa_calon($1) as d', ['X-02']);
ok(r.ok && !r.rows[0].d.calon.some((c) => c.id === kevin), 'yang sudah bertugas tidak muncul lagi sebagai calon');
r = await sebagai(K.pembina.id, 'select public.sg_sangga_rombel($1) as d', ['X-02']);
const d2 = r.rows?.[0]?.d;
ok(r.ok && d2.pinsa_tugas.length === 1 && d2.pinsa_tugas[0].id === kevin && d2.pinsa_tugas[0].kelas === 'X-01' && d2.pinsa_tugas[0].sangga === 'Sangga Rajawali' && d2.pinsa_tugas[0].tingkat === 'calon-laksana', 'sg_sangga_rombel memuat Pinsa tertugas beserta rombel asal dan tingkat');
ok(!d2.peringatan.some((p) => /Rajawali belum punya Pinsa/.test(p.teks)), 'sangga_peringatan menghitung Pinsa tertugas');
r = await sebagai(rizky, 'select public.sg_sangga_rombel($1) as d', ['X-02']);
ok(r.ok && r.rows[0].d.pinsa_tugas.length === 1 && r.rows[0].d.pinsa_tugas[0].tingkat === null, 'anggota rombel dapat melihat Pinsa tertugas, tingkatnya disembunyikan');
r = await sebagai(K.pembina.id, 'select public.sg_pemeriksaan_data() as d');
ok(r.ok && !r.rows[0].d.sanggaTanpaPinsa.some((x) => x.rombel === 'X-02' && x.sangga === 'Sangga Rajawali'), 'Periksa Data: Sangga Rajawali tidak lagi tanpa Pinsa');

console.log('\n--- Batas dua Pinsa tertugas per sangga ---');
await q(`update public.profiles set kelas = 'X-01', sangga = 'Sangga Elang' where id = $1`, [rizky]);
await q(`update public.profiles set kelas = 'X-02', sangga = 'Sangga Rajawali' where id = $1`, [nadia]);
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Rajawali', bagas);
ok(r.ok, 'Pinsa kedua ditugaskan (Bagas)');
r = await tugaskan(K.pembina.id, 'X-02', 'Sangga Rajawali', rizky);
ok(cocok(r, /sudah punya 2 Pinsa tertugas/), 'Pinsa ketiga ditolak');
await cabut(K.pembina.id, 'X-02', bagas);
await q(`update public.profiles set kelas = 'X-01', sangga = 'Sangga Elang' where id = $1`, [nadia]);
await q(`update public.profiles set kelas = 'X-02', sangga = 'Sangga Rajawali' where id = $1`, [rizky]);

console.log('\n--- Jalur pra-uji lewat Pinsa tertugas ---');
r = await sebagai(kevin, 'select public.sg_pendampingan_saya() as d');
ok(r.ok && r.rows[0].d.pinsa === true && r.rows[0].d.pinsa_tugas.length === 1 && r.rows[0].d.pinsa_tugas[0].rombel === 'X-02' && r.rows[0].d.pinsa_tugas[0].sangga === 'Sangga Rajawali', 'sg_pendampingan_saya: Kevin tercatat sebagai Pinsa (menu Pra-uji muncul)');
r = await sebagai(ahmad, 'select public.sg_pendampingan_saya() as d');
ok(r.ok && r.rows[0].d.pinsa === false && r.rows[0].d.pinsa_tugas.length === 0, 'Ahmad (anggota biasa) bukan Pinsa');
r = await ajukan(ahmad, B2);
const w = await menunggu(ahmad, B2);
ok(r.ok && w.length === 1 && w[0].tahap === 'pinsa', 'Ahmad mengajukan: kini tahap Pinsa (Kevin) yang menilai ' + (r.pesan ?? ''));
r = await antrian(kevin);
ok(r.ok && r.rows[0].a.menunggu.some((x) => x.peserta_id === ahmad && x.sku_id === B2 && x.tahap === 'pinsa'), 'antrian Kevin memuat pengajuan Ahmad (lintas rombel)');
r = await antrian(siti);
ok(r.ok && !r.rows[0].a.menunggu.some((x) => x.peserta_id === ahmad), 'Pinsa sangga lain (Siti) tidak melihatnya');
r = await antrian(dimas);
ok(r.ok && !r.rows[0].a.menunggu.some((x) => x.peserta_id === ahmad), 'Bina Damping belum melihatnya sebelum Pinsa memutuskan');
r = await catat(dimas, w[0].id, 'lulus');
ok(cocok(r, /tidak dapat menilai pra-uji ini/), 'Bina Damping tidak dapat memutuskan tahap Pinsa');
r = await catat(kevin, w[0].id, 'belum');
ok(cocok(r, /catatan/i), 'keputusan "belum" wajib bercatatan');
r = await catat(kevin, w[0].id, 'lulus', '');
ok(r.ok && r.rows[0].h.tujuan === 'bina_damping', 'Kevin (Pinsa tertugas) meluluskan: diteruskan ke Bina Damping ' + (r.pesan ?? ''));
r = await antrian(dimas);
ok(r.ok && r.rows[0].a.menunggu.some((x) => x.peserta_id === ahmad && x.tahap === 'bina_damping'), 'Bina Damping X-02 (Dimas) kini melihat pengajuan itu');
const wb = await menunggu(ahmad, B2);
r = await catat(dimas, wb[0].id, 'lulus');
ok(r.ok && r.rows[0].h.tujuan === 'pembina' && (await progres(ahmad, B2))?.status === 'diajukan', 'Bina Damping meluluskan: diteruskan ke Pembina (antrian rombel)');
ok((await q(`select penilai_nama from public.sku_pra_uji where peserta_id = $1 and sku_id = $2 and tahap = 'pinsa'`, [ahmad, B2]))[0].penilai_nama.length > 0, 'nama penilai Pinsa tersalin pada baris pra-uji');

console.log('\n--- Aturan pengaman: butir Laksana, sangga lain, dan agama ---');
ok((await q(`select sigarda.pra_uji_penilai_ok($1, $2, 'pinsa', $3) as b`, [ahmad, B3, kevin]))[0].b === true, 'penilai_ok: Kevin sah untuk Ahmad pada butir Bantara');
await q(`update public.profiles set sangga = 'Sangga Lain' where id = $1`, [ahmad]);
ok((await q(`select sigarda.pra_uji_penilai_ok($1, $2, 'pinsa', $3) as b`, [ahmad, B3, kevin]))[0].b === false, 'pindah ke sangga lain: Kevin tidak lagi sah');
await q(`update public.profiles set sangga = 'Sangga Rajawali' where id = $1`, [ahmad]);
const L1 = (await q(`select id from public.sku_unit where tingkat = 'Laksana' and agama is null order by butir_no, id limit 1`))[0].id;
ok((await q(`select sigarda.pra_uji_penilai_ok($1, $2, 'pinsa', $3) as b`, [ahmad, L1, kevin]))[0].b === false, 'butir Laksana tidak melalui Pinsa (hanya Bina Damping)');
const agamaAhmad = (await q('select agama from public.profiles where id = $1', [ahmad]))[0].agama;
const agamaKevin = (await q('select agama from public.profiles where id = $1', [kevin]))[0].agama;
if (agamaAhmad !== agamaKevin) {
  const BA = (await q(`select id from public.sku_unit where tingkat = 'Bantara' and agama = $1 limit 1`, [agamaAhmad]))[0]?.id;
  ok(!!BA && (await q(`select sigarda.pra_uji_penilai_ok($1, $2, 'pinsa', $3) as b`, [ahmad, BA, kevin]))[0].b === false, `butir agama ${agamaAhmad}: Kevin (${agamaKevin}) tidak sah, tahap Pinsa dilewati`);
} else ok(true, 'Ahmad dan Kevin seagama pada data contoh: pengecekan butir agama dilewati');

console.log('\n--- Mencabut, pembersihan otomatis, RLS, cadangan ---');
r = await cabut(siti, 'X-02', kevin);
ok(cocok(r, /Hanya Bina Damping rombel ini/), 'Penegak biasa tidak dapat mencabut penugasan');
r = await sebagai(siti, 'select 1 from public.pinsa_tugas');
ok(!r.ok || r.rows.length === 0, 'Penegak tidak membaca tabel pinsa_tugas langsung (tanpa hak baca dan tanpa kebijakan)');
r = await sebagai(K.pembina.id, 'select 1 from public.pinsa_tugas');
ok(!r.ok || r.rows.length === 0, 'bahkan Pembina hanya lewat fungsi (tanpa hak baca langsung)');
r = await sebagai(siti, `insert into public.pinsa_tugas (tahun_ajaran, rombel, sangga, penegak_id) values ($1, 'X-02', 'Sangga Rajawali', $2)`, [ta, siti]);
ok(!r.ok, 'klien tidak dapat menulis langsung ke tabel');
r = await sebagai(K.admin.id, 'select public.sg_cadangan_admin() as d');
const cad = r.rows?.[0]?.d;
ok(r.ok && Array.isArray((cad.data ?? cad.tabel ?? cad).pinsa_tugas) && (cad.data ?? cad.tabel ?? cad).pinsa_tugas.length === 1, 'cadangan data memuat pinsa_tugas');
await batal(ahmad, B2);
await q(`update public.profiles set status = 'nonaktif' where id = $1`, [kevin]);
ok((await daftarTugas()).length === 0, 'Kevin nonaktif: penugasan Pinsa berakhir sendiri (pemicu)');
await q(`update public.profiles set status = 'aktif' where id = $1`, [kevin]);
r = await tugaskan(K.admin.id, 'X-02', 'Sangga Rajawali', kevin);
ok(r.ok, 'Admin dapat menugaskan kembali');
r = await cabut(dimas, 'X-02', kevin);
ok(r.ok && (await daftarTugas()).length === 0, 'Bina Damping rombel itu mencabut penugasan');
r = await cabut(dimas, 'X-02', kevin);
ok(r.ok, 'mencabut yang sudah tidak ada tidak galat');
r = await ajukan(ahmad, B4);
ok(r.ok && (await menunggu(ahmad, B4))[0]?.tahap === 'bina_damping', 'sesudah dicabut: tahap Pinsa kembali dilewati');

console.log('\n--- api ---');
r = await K.pembina.a.muatSanggaRombel('X-02');
ok(r.ok && Array.isArray(r.data.pinsaTugas), 'api().muatSanggaRombel memetakan pinsaTugas');
r = await K.pembina.a.calonPinsa('X-02');
ok(r.ok && r.data.calon.length > 0 && r.data.calon[0].id && r.data.calon[0].kelas, 'api().calonPinsa memetakan calon');
r = await K.pembina.a.tugaskanPinsa('X-02', 'Sangga Rajawali', kevin);
ok(r.ok, 'api().tugaskanPinsa ' + (r.pesan ?? ''));
r = await K.pembina.a.cabutPinsa('X-02', kevin);
ok(r.ok && (await daftarTugas()).length === 0, 'api().cabutPinsa');

console.log(`\nRINGKASAN PINSA-TUGAS: ${lulus} lulus, ${gagal} gagal`);
process.exit(gagal ? 1 : 0);
